### ISSUE TITLE
[FR] Handle Worker exceptions inside worker

### ISSUE THREAD

**Issue by iarspider** [ATLauncher/ATLauncher#110]
If something (e.g. NPE) happens inside a Worker thread it's often impossible to figure out what you (as a modpack dev) did wrong. Here is an example of a 99% useless stack trace: https://gist.github.com/iarspider/ec3026455a8d3f7d7ed8 . 

I will make a PR if I implement this before you do :)

**Comment by RyanTheAllmighty** [comment]
This has been cleaned up and hopefully better now
