### ISSUE TITLE
The "XX:+CMSIncrementalMode" Java argument crashes Minecraft with Java 9

### ISSUE THREAD

**Issue by Shegorath123** [ATLauncher/ATLauncher#116]
EDIT: Issue fixed by using custom arguments, please ignore!

**Comment by resinate** [comment]
how did u fix this issue excatly? or did u just revert back to java 8?

**Comment by jurf** [comment]
Just remove `XX:+CMSIncrementalMode` from the JVM Arguments in the Profile Editor.

**Comment by RyanTheAllmighty** [comment]
We removed that argument as a default argument for Java 9 and older anyway so should just work fine now

For reference: https://github.com/ATLauncher/ATLauncher/blob/76e91e351638aa24bcfb57521e9dab13c8e2cb12/src/main/java/com/atlauncher/mclauncher/MCLauncher.java
