### ISSUE TITLE
Launcher shouldn't follow links when deleting instances

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#118]
According to [this post](http://forums.atlauncher.com/thread-6503-post-28962.html#pid28962) on the forums the launcher seems to follow links when deleting instance files and folders. I'm quite sure that this is not intended, it would probably be better if the launcher deleted the links themselves rather than what they point to.

**Comment by RyanTheAllmighty** [comment]
Yeah this shouldn't happen. I shall take a look

**Comment by RyanTheAllmighty** [comment]
Should be fixed in the next update
