### ISSUE TITLE
"Select Recommended" vs "Select All" differentiation

### ISSUE THREAD

**Issue by Cherry** [ATLauncher/ATLauncher#120]
When every mod in a pack is marked as recommended (or not marked at all, as recommended is default), but some of these mods are optional, rather than displaying "select recommended", the launcher displays "select all". Whilst this does make sense, end-users may not understand that the optional mods are recommended, without the explicit display that they are so.

"Select Recommended" displays as expected when there is at least one mod that is explicitly marked as not recommended.

Let me know if you need any further information!

**Comment by RyanTheAllmighty** [comment]
So just to make sure what you want, you want it to show Select Recommended always even if there is no non recommended mods?

Been a while since I talked to you about this so just want to make sure.

**Comment by Cherry** [comment]
Kinda. The biggest thing is when every mod is marked recommended, but optional, the launcher still shows 'select all' rather than 'select recommended'. The end user at this point has no idea if the 'select all' button is selecting recommended mods, or just every single optional one.

**Comment by RyanTheAllmighty** [comment]
Gotcha
