### ISSUE TITLE
open folder butten

### ISSUE THREAD

**Issue by Goten87** [ATLauncher/ATLauncher#127]
open folder butten opens a other ATLauncer client insted of the folder

**Comment by RyanTheAllmighty** [comment]
I'm assuming you're using the code from source? Or this the official compiled builds from the website?

**Comment by Goten87** [comment]
offical release

**Comment by RyanTheAllmighty** [comment]
No idea what's caused this, can't even imagine what might cause it. Please reopen this with logs if still interested/broken
