### ISSUE TITLE
Adding a 1.8 dev version causes the launcher to hang

### ISSUE THREAD

**Issue by DrummingFish** [ATLauncher/ATLauncher#128]
This may be a problem uniquely to me but I thought I'd post the issue anyway.

When I added a 1.8 dev version with valid XML, the launcher hangs when you click on the "New Instance" button.

Those who don't have access to the dev versions don't have the problem so it looks as if there is a problem handling 1.8.

**Comment by RyanTheAllmighty** [comment]
I have no issues doing so in a 1.8 test version I made.

Is this still occuring? If so can you please let me know the packs name and dev versions name so I can take a look

**Comment by DrummingFish** [comment]
Yeah it's still occurring. Can't think what could be causing it though. I have to use the Task Manager to close the launcher as it hangs indefinitely.

Pack name: Monumental
Dev version: v3.0.0dev

**Comment by DrummingFish** [comment]
Are you making any headway with the problem? Sorry to be a bother.

**Comment by RyanTheAllmighty** [comment]
The error I'm getting is 'No Minecraft version found matching 1.8.0'

There is no 1.8.0 it's 1.8

I'll add some sanity checking in to the admin panel to prevent this

**Comment by DrummingFish** [comment]
Ahh that makes sense. 1.8.0 is just how I see the version number logically. Noted for future reference.
