### ISSUE TITLE
missing items/blocks in crackpack after uppdating java 7 to 8. and then downgrade to 7 again pls help

### ISSUE THREAD

**Issue by shockwave9898** [ATLauncher/ATLauncher#130]
hi. I was playing on my crackpack server when i got an update on java 8 and when i updated the java the at launcher said that some blokcs may not wotk with that java. i didnt know at first but afterwards i deleted the java 8 and installed java 7 but it still miss block/ items and alot of them. the nei had about 215 items or something like that and now i only have 188 items. any one who knows what to do i would be very greatfull.

**Comment by RyanTheAllmighty** [comment]
Crack Pack issues go to https://github.com/sciguyryan/TheCrackPack/issues
