### ISSUE TITLE
Searching isn't triggered until an additional keyPressed event

### ISSUE THREAD

**Issue by Cherry** [ATLauncher/ATLauncher#131]
Steps to reproduce:

- Search for "b" and nothing happens
- Enter another key such as "y" and all packs containing "b" are known shown
- Enter another key such as "z", and now all packs containing "by" are shown.

Alternatively, this can be seen further with any key press:

- Search for "b"
- Hit backspace, or an arrow key, function key, or any other keypress
- Search for "b" is now triggered

Using the [keyReleased] event rather than keyPressed event should resolve the issue [maybe](https://github.com/ATLauncher/ATLauncher/blob/2b33b482baa93724d7e784d067c8c7e97225afbe/src/main/java/com/atlauncher/gui/tabs/PacksTab.java#L129)?, so the text box actually contains text before you force a re-render.

**Comment by RyanTheAllmighty** [comment]
All fixed
