### ISSUE TITLE
[Feature Request]: Hideable Tabs

### ISSUE THREAD

**Issue by Lanse505** [ATLauncher/ATLauncher#133]
Essentially what i'm asking is, is it possible to implement the ability to give certain selection a tab/category "tag" where you can hide it and anything thats counted as a sub-category for the tab.

So essentially like this:

If Open:
[-]Sandbox:
    [] Lite
    [] Mainline
    [] Excessive
[+]Eras:

If Closed:
[+]Sandbox:
[+]Eras:

This would helpful it not Overloading players with visible selections and big amounts of information.

Also Within this function the ability to set extra tags like "Start Open", "Start Closed" makes it easy for us to give quick options to players, so like have all presets like with RR Sandbox Modes and Eras be open by default, while Modifiers and Optional Mods are closed by default :)

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

Many packs don't go into this level of detail of optional mods anymore.
