### ISSUE TITLE
User data redacting fails in offline mode

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#143]
...presumably because either the username, UUID or access token is an empty string, which causes a REDACTED to be inserted between all characters: http://paste.atlauncher.com/view/0c37e759

**Comment by RyanTheAllmighty** [comment]
Whoa that's a mess! I shall fix

**Comment by RyanTheAllmighty** [comment]
Wait no I already fixed this, when I fixed the offline support this should have been fixed also
