### ISSUE TITLE
ATLauncher main window completely blank sometimes.

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#145]
Forum thread: http://forums.atlauncher.com/thread-8402.html

OS: [Manjaro](https://manjaro.github.io/) Linux release 0.8.12
Window Manager: Enlightenment 0.19.2-1

**Comment by Alzarath** [comment]
I'm also having the issue.
It was reported by someone here as well: http://forums.atlauncher.com/thread-4567.html

Distro: Arch Linux x86_64
Window Manager: bspwm 0.9

I had the same issue with a similar launcher (feedthebeast-1:1.4.6_305).

Looking around the feed-the-beast forums, someone [linked a solution](https://wiki.haskell.org/Xmonad/Frequently_asked_questions#Problems_with_Java_applications.2C_Applet_java_console) for xmonad that also worked for me.

**Comment by s0cks** [comment]
This is an issue with painting in swing, not an ATL bug

**Comment by madyoda** [comment]
Having this issue too.
Distro: Arch Linux
Window manager: AwesomeWM

**Comment by theArchLadder** [comment]
For me this issue was solved by running with this variable:
_JAVA_AWT_WM_NONREPARENTING=1 java -jar ATLauncher.jar

**Comment by flaw600** [comment]
@RyanTheAllmighty should we put the above by @theArchLadder in the FAQ or should we try to solve this in code? From what I understand of @s0cks, it may not be blatantly code fixable unless we run the application  with those variables in code.

**Comment by RyanTheAllmighty** [comment]
@dgelessus manages the FAQ. May be worth mentioning this in the FAQ possibly?

**Comment by dgelessus** [comment]
@flaw600 @RyanTheAllmighty Done: https://forums.atlauncher.com/announcement-5.html#linux-blank-launcher

**Comment by RyanTheAllmighty** [comment]
Thank-you. I'll close this now
