### ISSUE TITLE
Twitter account issues

### ISSUE THREAD

**Issue by Cuppycake** [ATLauncher/ATLauncher#153]
Upon publishing an update I am not seeing our twitter account @secondarygaming tweeting the update but the ATL one is working fine. 

Also trying to add a pack specific twitter @mechandmagic but I get an error page saying "Oops an Error has occured." when clicking on "Authorize ATLauncher"

I have had this happen once before but I can't recall if it fixed itself or if we re-added the account. Can't do the later this time, though.

Thanks :)

**Comment by RyanTheAllmighty** [comment]
This should be fixed, if not let me know

**Comment by RyanTheAllmighty** [comment]
Okay it's actually fixed now :)

Also for future reference, site issues like this goes to https://github.com/ATLauncher/Website-Issues/issues :)
