### ISSUE TITLE
Issues cloning an instance

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#155]
Seems after cloning an instance and disabling a mod it acts funky.

http://forums.atlauncher.com/thread-1628.html

**Comment by s0cks** [comment]
How exactly does it (and what is it?) act funky?

**Comment by RyanTheAllmighty** [comment]
From the forums thread

'I tried cloning The Crack Pack and disabling some of the mods for a Local LAN setup, but when I looked at the normal Crack Pack, it also had the same mods disabled (which doesn't make sense, being that they are two different directories).'

So cloning an instance WITHOUT restarting the launcher will still link those two instances and when the edit mods dialog is used to disable/add mods it affects both

**Comment by s0cks** [comment]
well cloning an instance is using the java clone feature which imo shuoldnt be used. I believe that the java clone feature makes a pointer to the origin and calls that the clone....but then again Im not positive about that

**Comment by s0cks** [comment]
After a quick google search about cloning in java it turns out I was right, shallow cloning which is what we're doing will allow changes to affect the original....deep cloning will not so we need to implement a better cloning system that doesn't use Java's builtin cloning feature

**Comment by s0cks** [comment]
I tagged this for 3.3.0.0 because its important to write a proper cloning method for Instances, since shallow cloning wont cut it because of it becoming basically a pointer to the original. It's a simple fix though so should get on the 3.3.0.0 release

**Comment by flaw600** [comment]
Java's clone is shallow by default. To do a deep copy we'd need to implement our own clone method. @s0cks ?

**Comment by s0cks** [comment]
@flaw600 normally you implement your own clone method when you implement Cloneable because the contract for Cloneable states that you should use a deep copy of the object instead of a shallow one.

**Comment by flaw600** [comment]
Normally, yes, but have we done so here? I haven't really looked into it

**Comment by flaw600** [comment]
@RyanTheAllmighty @s0cks can I get comments on my commit? I basically attempted to do a deep copy. I got rid of the try-catch block because CloneNotSupported will never be thrown, however I'm not sure if other errors would be thrown or not. They shouldn't, as I'm literally just throwing the same parameters into a new Instance so any problems in the parameters should've been caught beforehand. Thoughts?

**Comment by RyanTheAllmighty** [comment]
I see no issues with this, feel free to PR and close

**Comment by RyanTheAllmighty** [comment]
If you want to port this to 3.2.3.2 also please feel free to.

**Comment by flaw600** [comment]
Yeah I'll do that, thanks.

**Comment by RyanTheAllmighty** [comment]
Released
