### ISSUE TITLE
[FR] Post-install patch

### ISSUE THREAD

**Issue by iarspider** [ATLauncher/ATLauncher#156]
The idea is to allow pack makers to change config files depending on mod selection. To avoid security risks, maybe only allow patching of text files (using *nix-style diff-patch). 

Suggested XML format:

```
<version>
  <patches>
    <patch patchFile="packs/ThisCoolPack/patches/ttCore_Calculator.patch" depends="ttCore, Calculator" configFile="config/ttCore/cropConfig.json"/>
```

Patch file example:

```
--- b/cropConfig.json   2015-04-09 15:08:04.000000000 +0300
+++ a/cropConfig.json   2015-04-09 20:52:32.865381300 +0300
@@ -456,6 +456,11 @@
             "seed":"PneumaticCraft:plasticPlant",
             "block":"PneumaticCraft:flyingPlant",
             "meta":13
+        },
+        {
+            "seed":"Calculator:BroccoliSeeds",
+            "block":"Calculator:BroccoliPlant",
+            "meta":7
         }
     ]
 }
```

The patch will be applied if both mods under "depends" are selected.

**Comment by RyanTheAllmighty** [comment]
I'm not even sure if Java can do patches, but I shall take a look into it :)

**Comment by iarspider** [comment]
We can invent our own format for these things...

**Comment by modmuss50** [comment]
I think there is a java lib to do this, diff4j comes to mind.

**Comment by Cherry** [comment]
+1 for this, would be awesome.

**Comment by flaw600** [comment]
I'm pretty sure Java allows patches. @modmuss50 seems to be correct. I'll place that in the very capable hands of..anyone else lol.

**Comment by RyanTheAllmighty** [comment]
Yeah this is definitely something that would be nice to have done, but I don't see it being done anytime soon unfortunately.

**Comment by iarspider** [comment]
Can't we just use system `patch` for this? I know there is no "system" patch on Windows, but I'm pretty sure there is a 3rd party implementation. 

As for Java implementation, [this](https://code.google.com/archive/p/google-diff-match-patch/) is probably what we need.

**Comment by RyanTheAllmighty** [comment]
Oh yeah I'm entirely sure there will be Java based libraries to do this, probably quite a few of them, just this is a very big picture item requiring a whole new subset of things to be added both to front and backend.

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

Many packs don't go into this level of detail of optional mods anymore.
