### ISSUE TITLE
Share Code Issue

### ISSUE THREAD

**Issue by devryb** [ATLauncher/ATLauncher#158]
The share code I9DJPW99 is supposed to be for Resonant Rise + Mainline + Biomes O Plenty + Opis however it gives invalid share code when trying to add

**Comment by RyanTheAllmighty** [comment]
Works fine here. You're using the wrong version of Resonant Rise most likely since this is for 3.2.5.0-RC-MAIN which isn't the latest.

You can use http://www.atlauncher.com/launch-tool-helper to generate downloadable links for that specific share code to install the right version

**Comment by devryb** [comment]
Ah ok thats probably the issue then when I grab the share code for the latest version it is the same one unless my launcher is having problems.  Can you tell me what the share code would be for the above with the latest version?

**Comment by RyanTheAllmighty** [comment]
No idea, you need to remake them for each version and they aren't generic so you'd need to make it yourself
