### ISSUE TITLE
[Feature Request] You should be able to generate a share code from a custom server created through the launcher

### ISSUE THREAD

**Issue by andrewring** [ATLauncher/ATLauncher#161]

**Comment by dgelessus** [comment]
FYI, once a server instance is installed, it is no longer "linked" to the launcher anymore, i. e. it is just a normal folder without any launcher data on what mods were selected. This means that share codes could only be generated during the installation process. Currently the best way to create server share codes is to get them from a matching client instance.

**Comment by RyanTheAllmighty** [comment]
Yeah the issue with this is that ATLauncher doesn't keep track of servers created and we have no real reason to.

The best way to go is to create the client you want first, then get a share code from that to use to create the server.
