### ISSUE TITLE
Change accounts on the launcher to use UUIDs

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#162]
As title says.

Currently username changes bork accounts.

Need to switch to UUID's and do some checks when loading to look for a username change and reflect that.

**Comment by dgelessus** [comment]
#134

**Comment by RyanTheAllmighty** [comment]
Yeah #134 is referencing allowed players/testers. This one is specifically for accounts on the launcher. But they both should be done at the same time

**Comment by RyanTheAllmighty** [comment]
This also needs to change the installedBy for instances to the UUID and not the username including updating a users current instances that may have that

**Comment by RyanTheAllmighty** [comment]
installedBy for instances are now UUID based

**Comment by RyanTheAllmighty** [comment]
Okay I think it's all moved over to UUID's now.

I just need some testers to help with making sure the transition goes smoothly since I don't wanna change my username

**Comment by RyanTheAllmighty** [comment]
This has been done now BTW
