### ISSUE TITLE
Performance Improvements Proposal

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#163]
Here's what I propose we do for improving the performance of the ATLauncher.

1.) Use Apache VFS to handle all file interactions

### Or
-------------------------------------------------------------------------------
1.) Use Java 7, so we have NIO & NIO.2

--------------------------------------------------------------------------------
Tell me what is doable and what isn't

**Comment by RyanTheAllmighty** [comment]
It's too late to try to fix the OSX Java 6 issue without some hacks unfortunately :(

**Comment by s0cks** [comment]
Whatever needs to be done to get the ATLauncher to java 7 i will do

**Comment by RyanTheAllmighty** [comment]
Problem is the OSX app we've been distributing is what is requiring Java 6.

Easy enough to start distributing one that doesn't have that requirement, but existing app users would then be forced to upgrade the app, causing issues

**Comment by s0cks** [comment]
Upgrade how?

**Comment by RyanTheAllmighty** [comment]
Even then, everytime I've tried to make a non Java 6 dependant OSX app, it's failed. But then again I haven't looked in over a year so I'm 100% sure it's doable.

Just not sure the requirement of users having to download a new app is a great user experience

**Comment by RyanTheAllmighty** [comment]
Well users with the existing app would need to redownload a new app, it's not something we can just update.

I'd also like to actually start signing the app as well if this is required

**Comment by s0cks** [comment]
The amount of bennifits of having java 7 as the devkit far outward having to update the app imo

**Comment by RyanTheAllmighty** [comment]
I agree 100%

**Comment by RyanTheAllmighty** [comment]
I'll investigate into getting the OSX app portion of things working with Java 7 and then we can go from there.

Putting this here as a starting point: https://github.com/tofi86/universalJavaApplicationStub

**Comment by s0cks** [comment]
Also I added some nice features (well am adding atm) using aspectj

**Comment by RyanTheAllmighty** [comment]
Please remember https://github.com/ATLauncher/ATLauncher/blob/master/STYLE.md especially the last point in the Coding Standards section :)

Also if you can pop it in it's own branch so it can be tested and whatnot before that'd be great :)

**Comment by dgelessus** [comment]
Re. the OSX app, my personal opinion is that the jar version is just *so* much better in almost every way:

* It gets launched using whatever the system default Java is
* Gatekeeper doesn't constantly get in its way, pretending that the app is corrupt
* Users can easily access their data without needing to "show package contents" on the app

The only downsides are that the jar is *slightly* less convenient to use (creating a new folder for the launcher is hard, y'know), it can only be placed on the "files and folders" side of the dock (not the "applications" side) and it has no icon.

Any idea how widely used the app version of the launcher is? (My opinion of the Mac app may have been affected by my experiences as a support forum person. The app is definitely working better now than it did a few versions ago, but I still find the jar version just as easy to use.)

**Comment by RyanTheAllmighty** [comment]
Yeah you've hit the nail on the head. It's hard to create a new folder :P

It's all about convenience at the end of the day. If this makes it more convenient for users then that's great.

The way this new app should work is no more gatekeeper since it would be signed under ATLauncher (if a developer account isn't way too overpriced) and it should give us control over which version of Java is required, so if the user doens't have Java 7 or up, it shows a message.

I still need to play around with it, but it SHOULD be straight forward and provide much better control.

As for usage numbers, unfortunately that's the one thing we don't track ATM is OS versions and launcher versions. I plan to add this to the next version as this kind of information is very wildly useful for these types of situations.

But yeah, still very early testing stages :)

**Comment by RyanTheAllmighty** [comment]
Alright new OSX bundling is now in and seems to run fine, at least on Yosemite.

Still not signed at this point but that's later.

@dgelessus you're on a Mac yes? Can you try out https://build.atlcdn.net/job/ATLauncher/22/ grabbing the zip

**Comment by s0cks** [comment]
So wait I can start coding with java 7 stuff now?

**Comment by RyanTheAllmighty** [comment]
Not yet. There's got to be a bit of testing before I'll be happy to give it the go ahead

**Comment by s0cks** [comment]
alright

**Comment by RyanTheAllmighty** [comment]
I'll need to keep tinkering with things, but so far it's a good sign that it will work.

**Comment by s0cks** [comment]
great :)

**Comment by dgelessus** [comment]
Nope, doesn't work for me sadly... Even though I have Oracle's Java 8 JRE installed, it gives me an error saying that I don't have the necessary Java version. I looked at the `universalJavaApplicationStub` script, and it seems that it trusts `/usr/libexec/java_home` more than anything else. That command is only aware of Apple's old Java 6 JRE though. (This is on OS X Mavericks, version 10.9.5.)

**Comment by RyanTheAllmighty** [comment]
Bugger. Works great on Yosemite with JRE 8.

I'm going to need to get a bunch of testers. I'll pop out a tweet later today after I get some more OSX version virtual machines

**Comment by RyanTheAllmighty** [comment]
I think the issue may be that it's checking for a set $JAVA_HOME variable first. @dgelessus what's yours set to?

If it's set to Java 6, I can probably remove that in the stub file and have it look for the rest first which will prompt for the right Java we want which is set to 1.7+

**Comment by RyanTheAllmighty** [comment]
Okay so installing Apples Java 6 causes me to get the same issue. This is fixable now \o/

**Comment by RyanTheAllmighty** [comment]
Seems when you install the JRE on OSX it doesn't update in the java_home command that it's installed. Installing the JDK seems to update that source, but requiring the install of the JDK is a last step measure, I'd rather not do it

**Comment by dgelessus** [comment]
Or don't error right away if `java_home` doesn't find anything and try the fallbacks instead? AFAICT those are never actually used.

**Comment by RyanTheAllmighty** [comment]
What I've done is if there is a suitable 1.7+ jdk installed it will use it, else it falls back on the JRE that's installed.

https://build.atlcdn.net/job/ATLauncher/lastSuccessfulBuild/ - This build seems to fix the issue with no JDK but has Java 7+ installed from Oracle

I just need to do some tests to make sure it's not using Java 6 and error if so

**Comment by RyanTheAllmighty** [comment]
Hurray it seems to be all fixed now and using the correct Java.

Now onto try different OSX versions

**Comment by RyanTheAllmighty** [comment]
Okay so it's now in it's own branch, for reference the last version on the build server which has these changes in it is https://build.atlcdn.net/job/ATLauncher/35/ anything past that won't have the new stuff

**Comment by RyanTheAllmighty** [comment]
Alright I've tested all the way back to OSX 10.7 Lion (that's the only virtual machines I could get running back to) and it works perfectly.

Once @s0cks and I get finished with the upgrades to Java 7, then I can begin user testing, but I have no doubts it will work A-Ok

**Comment by s0cks** [comment]
Any chance we can get Guice shaded in for the 3.3.0.0 release, would be wonderful to work on some decoupling :3

**Comment by RyanTheAllmighty** [comment]
Can you please open a new issue with details about it @s0cks such as what you plan to do with it, benefits etc?

**Comment by s0cks** [comment]
Sure

**Comment by s0cks** [comment]
I saw we pretty much covered this already
