### ISSUE TITLE
Display changelog for launcher

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#164]
1.) Tool to display the current version's changelog in the launcher

**Comment by s0cks** [comment]
Got a way for me to make this possible?

**Comment by RyanTheAllmighty** [comment]
Not at this time no. I'd like to stick with fixing and updating the launcher before adding anymore features

**Comment by s0cks** [comment]
Whys it tagged with the 3.3.0.0 milestone then?

**Comment by RyanTheAllmighty** [comment]
I mean I'd like to get everything performant and completely working bug free to Java 7 before adding any new features for 3.3.0.0, so I definitely wanna see this in 3.3.0.0 if possible, just don't wanna be getting work done on new features before everything is back to working how it was with 3.2.x series.

**Comment by s0cks** [comment]
Make another issue with all the known issues with that check off thing....Im bored

**Comment by RyanTheAllmighty** [comment]
All there is is Instances not being able to be deleted from #180 and general NIO improvements

**Comment by s0cks** [comment]
Interesting it deletes them on my machine....

**Comment by RyanTheAllmighty** [comment]
Closing in favour of #304
