### ISSUE TITLE
Abstract all mod types

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#167]
I want to abstract all mod types so that when installing an instance it's as simple as something like:

````java
mod.getModType().install();
````

And have each mod type having it's own class with implementation so it's easy to add/change the way a type is installed.

At the moment it's all shoved into the Mod class which is large, ugly and has code duplication.

**Comment by s0cks** [comment]
This done so I can close it @RyanTheAllmighty ?

**Comment by RyanTheAllmighty** [comment]
Looks good. Cheers
