### ISSUE TITLE
Split up massive Settings class into managers

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#169]
Mainly directed at @s0cks 

The Settings class is so large and convoluted. I think it definitely needs to be segmented up.

I'm thinking of using Managers to do this. So you'd have PacksManager, InstancesManager, AccountsManager etc all being static classes.

For instance PacksManager would have methods like getAllPacks(), getPackByName("name") etc.

This would separate the Settings class into better laid out and single responsibility classes to query when needed.

Thoughts?

**Comment by s0cks** [comment]
Im actually working on that

**Comment by RyanTheAllmighty** [comment]
Okay cool.

I feel the Settings class should be just that, controlling the settings of the launcher, not as this big monolithic class where everything is.

I'm thinking maybe we need a different entry point/loading point for the application and abstract the Settings out to it's own GSONable class if not doing that in the existing Settings class.
