### ISSUE TITLE
Show changelog to users when updating

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#170]
When an update is available to an instance there should be an option to open the changelog in the browser or possibly in the launcher (this would require possibly calling the ATLauncher API OR adding changelogs to the JSON returned for versions)

**Comment by s0cks** [comment]
I think it would be better to view the changelog in the launcher

**Comment by s0cks** [comment]
Got a way for me to do this as well?

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

If this is necessary later on, it can be recreated, but given the large change in the launchers scope over the years, this has not seemed necessary
