### ISSUE TITLE
Allow installing instances into the Vanilla client

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#171]
Providing this as an option might be a good idea for those who don't want to use ATLauncher for anything other than installing the instances.

**Comment by s0cks** [comment]
What about exporting to MultiMC as well?

**Comment by RyanTheAllmighty** [comment]
You can't export to MultiMC last time I looked, they used a strange structure and stuff

**Comment by s0cks** [comment]
I could look into it if its something you would be willing to do?

**Comment by RyanTheAllmighty** [comment]
Definitely feel this is out of scope of the goal of the launcher at this point in time so closing.
