### ISSUE TITLE
Codebase Improvements (Post 3.3.3.0 Release)

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#172]
Use AOP.
Use Guice to inject dependencies and create instances of classes.

**Comment by s0cks** [comment]
@RyanTheAllmighty thoughts?

**Comment by RyanTheAllmighty** [comment]
Not for 3.3.0.0 release no

**Comment by s0cks** [comment]
If you read in the topic it would be for post 3.3.0.0 release

**Comment by RyanTheAllmighty** [comment]
Then remind me to look at this again once it's out and done :)
