### ISSUE TITLE
Use OkHttp for Http requests as HttpURLConnection is bad stuff

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#173]
Topic says it all

**Comment by RyanTheAllmighty** [comment]
This is the exact library I've been looking for but Google-Fo failed me.

Moving the Downloadable class over to use this would be a fantastic idea

**Comment by s0cks** [comment]
I can do this for the 3.3.0.0 release

**Comment by RyanTheAllmighty** [comment]
It's a small enough binary as well so that's good

**Comment by s0cks** [comment]
Yeah

**Comment by s0cks** [comment]
Let me get crackin then XD
