### ISSUE TITLE
Change Event System to Guava's EventBus

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#176]
Title says it all, @RyanTheAllmighty questions, comments, or concerns? :3

**Comment by RyanTheAllmighty** [comment]
Problem is for such a small part of the system, it's a large end binary size change

**Comment by RyanTheAllmighty** [comment]
Goes from a 1.8MB binary to a 4MB which is over the 2MB I'd honestly like to see it stay around and under

**Comment by s0cks** [comment]
Wait isnt guava injected after it downloads the launcher library?

**Comment by RyanTheAllmighty** [comment]
It is but that's injected quite late into the process at the point where events may be fired before it's loaded.

Are there any parts of Guava besides the Events that would be useful? If there are other uses for it then I can consider shading it in

**Comment by RyanTheAllmighty** [comment]
I mean I'm happy to increase the size limit of the launcher if it leads to being more useful and performant in the end

**Comment by s0cks** [comment]
I benchmark'd hashing functions (Guava vs Commons-IO vs Java) and Guava is second in ops/s following Commons-IO but I would like to remove Commons-IO anyways you can see the results [here](https://gist.github.com/s0cks/d58ab983b20b569a418e)

**Comment by RyanTheAllmighty** [comment]
Yeah the difference is tiny. It's better than the Java benchmarks so either way it's an improvement.

The only reason I added in commons IO was because I couldn't be bothered to rework the hash functions for FileChannels and NIO and whatever.

**Comment by s0cks** [comment]
Well if we remove commons, which the hashing function implementation is shit for the commons one, we can use guava to do the hashing

**Comment by RyanTheAllmighty** [comment]
Yeah thats fine, as long as Guava isn't only being added for hashing and has some other meaningful use, it's fine

**Comment by s0cks** [comment]
Well hashing, the EventBus and stuff need any more reasons to add guava? :3

**Comment by RyanTheAllmighty** [comment]
I do. I still have no idea why we need EventBus over existing implementation. What's there is already fine and easily understandable. For a 2.2MB binary increase it's not worth it to me just for hashing and an EventBus

**Comment by s0cks** [comment]
Well the EventBus is a better implementation and shrinks the code extremely

**Comment by RyanTheAllmighty** [comment]
But is it really worth increasing the binary size by more than double just for the 6ish event and listeners we have?

**Comment by s0cks** [comment]
What about adding vert.x and use their EventBus its a smaller size

**Comment by s0cks** [comment]
Plus provides a lot of better concurrency practices than Java, and I'm planning on making more events

**Comment by s0cks** [comment]
Closed with 5ec3202407af7302fc05932d244f669791c461a9
