### ISSUE TITLE
Automatic file changelogs between modpack versions [suggestion]

### ISSUE THREAD

**Issue by BBoldt** [ATLauncher/ATLauncher#177]
Slightly related to #170 I think.

Would it be possible for atlauncher to actually check files or XML that have changed between versions and automatically generate a changelog based upon that data? Something similar to the system you have in place for checking for updates on curseforge.

Typing down what files have changed manually gets to be a pain.

Of course the ability to write your own changelogs for config and other changes in modpacks would still need to be there as well.

**Comment by RyanTheAllmighty** [comment]
Could this please be moved over to https://github.com/ATLauncher/Website-Issues/issues
