### ISSUE TITLE
Clean up InstanceInstaller

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#178]
I don't even wanna think about how bad InstanceInstaller is.

Needless to say this could use some cleaning up.

I'm not sure how to even tackle this at this point in time, any ideas @s0cks?

**Comment by s0cks** [comment]
I can take a look

**Comment by s0cks** [comment]
Done what do you think @RyanTheAllmighty

**Comment by RyanTheAllmighty** [comment]
All done then. See #180 for bugs on the list to fix

**Comment by s0cks** [comment]
Okay
