### ISSUE TITLE
Use Vert.x

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#179]
Title says it all

**Comment by RyanTheAllmighty** [comment]
Not sure what this is referring to. Can you provide some examples/sites of what you mean

**Comment by s0cks** [comment]
Vert.x includes an EventBus as well I would like to tap into that instead of having to use Guava's EventBus

**Comment by s0cks** [comment]
No good examples that arent web servers......

**Comment by RyanTheAllmighty** [comment]
Like I said in the other post about Guava, I really don't mind chucking in extra libraries, even if it means bigger binaries, if it will mean things are better and more performant.
