### ISSUE TITLE
Issues with 3.3.0.0 InstanceInstaller

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#180]
There's a few issues with the new InstanceInstaller process in 3.3.0.0 branch:

- [x] cannot reinstall an instance with Deletes (Resonant Rise for example)
- [x] cannot install an instance/server after already installing an instance/server without restarting
- [x] progress dialog doesn't show while downloading the JSON
- [x] after downloading the resources and switching to libraries, the sub progress bar isn't being set to indeterminate and keeps showing the previous resource downloading sub progress bar. Same happens when switching to download configs
- [x] progress dialog is showing the file size for all mods, not just the one's it's going to download
- [x] cannot delete instances due to java.nio.file.DirectoryNotEmptyException. The instance.json remains after deleting
- [x] downloading resources doesn't show it's name, instead it's hash value that it's downloading
- [x] the 'Download Libraries' prompt takes forever

**Comment by s0cks** [comment]
The second wasnt able to be replicated on my machine, and what do you mean while downloading the JSON

**Comment by RyanTheAllmighty** [comment]
Usually when you click Install after selecting a name and version for the pack it will bring up a dialog saying something while it loads the JSON and brings up the optional mod selection screen.

That dialog only now shows up a split second before the optional mods dialog comes up making me think something is blocking the UI

**Comment by s0cks** [comment]
Try deleting an instance?

**Comment by RyanTheAllmighty** [comment]
Yes deleting an instance, from restart or right after install, will not delete the instance.json (guessing it's possibly locked from loading all the instances still) and as it cannot delete that, it means it cannot delete the instances folder with a java.nio.file.DirectoryNotEmptyException

**Comment by s0cks** [comment]
Interesting Ill look into it

**Comment by s0cks** [comment]
Seems to be working right now?

**Comment by RyanTheAllmighty** [comment]
Nope, still happening for me
