### ISSUE TITLE
Guice

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#181]
By using Google's Guice we can control object creation better. Makes the code more modular and improves re-usability. For example [here](https://gist.github.com/s0cks/f9b0c69d838c60a9ea17) we create 2 instances of Dummy with its dependencies supplied for us just by calling Injector#getInstance(Dummy.class);

**Comment by RyanTheAllmighty** [comment]
Looking at that I have no idea what it will do TBH.

Looks like it might too overly complicate things, but I may be wrong with that.

Maybe if you branch of 3.3.0.0 and just do small real example, then I can see the benefit and use of it maybe

**Comment by s0cks** [comment]
Alrighty hold on

**Comment by s0cks** [comment]
Have to close as Guice uses Guava as a dependency, and if we add that to compilation libraries (which we would need to) then Guava will be added to the compilation libraries...Will write my own injector if possible.
