### ISSUE TITLE
Allow selection of folder to download curseforge updates to

### ISSUE THREAD

**Issue by BBoldt** [ATLauncher/ATLauncher#182]
Would like to have it work for all the updates on a version page, not a case by case basis. Just like a little selection menu up at the top of the updates section where you can pick the folder they get downloaded to.

**Comment by RyanTheAllmighty** [comment]
Please post this issue at https://github.com/ATLauncher/Website-Issues as this repository is for the Launcher itself

**Comment by BBoldt** [comment]
oops
