### ISSUE TITLE
Clean up InstanceInstaller communication with InstanceInstallerDialog

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#183]
I'd like to see the InstanceInstaller communicate more effectively with the InstanceInstallerDialog.

For instance the mess we have to do to set the sub progress bar as indeterminate or give it a byte count that it's downloading, seems, quite, messy.

There's alot of situations where it looks crappy, like downloadResources

``` java
    private void downloadResources() {
        this.fireTask(Language.INSTANCE.localize("instance.downloadingresources"));
        this.fireSubProgressUnknown();
        DownloadPool pool = this.getResources().downsize();
        this.totalBytes = this.downloadedBytes = 0;
        Network.setupProgressClient(this);
        this.totalBytes = pool.totalSize();
        this.fireSubProgress(0);
        pool.downloadAll(this);
        this.fireSubProgress(-1);
    }
```

There's just alot of method calls.

I'm thinking that maybe this can be better written and have the totalBytes/downloadedBytes moved to the InstanceInstallerDialog or a separate process maybe??

I just feel there should be a single call at the beginning of doing something to set the task and pass in if we need a sub progress bar, if it should be indeterminate etc, and then one method at the end to say we're done (this can probably be left off and left until the next starting call)

**Comment by s0cks** [comment]
I'll look into it

**Comment by RyanTheAllmighty** [comment]
I just feel that it's too much as it is at the moment.

I mean I was just looking at it and couldn't understand what the difference between this.fireSubProgress(-1); and this.fireSubProgress(0); was without looking back at the Dialog.

**Comment by s0cks** [comment]
Yeah

**Comment by flaw600** [comment]
@s0cks knows that I really dislike modularization, but in this case yeah, there's too much happening in one place. I'm not sure how to resolve it though without making the code more verbose. Not messier, mind you, but verbose. Thoughts?

**Comment by s0cks** [comment]
@RyanTheAllmighty @flaw600 I wanna rewrite the InstanceInstaller to work better. Maybe this weekend if I have some free time I'll conjure something up.

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.
