### ISSUE TITLE
Unify settings

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#186]
My plan is to make the Settings class be just that, the settings for the app, nothing else, just a simple Gson readable/writable class for the settings.

This will mean moving off the loading process to a different class.

A SettingsManager will handle all settings related calls, much like the other managers.

A few things will need to be done:

- [x] moving all the settings for the app to a Settings Gsonable class
- [x] handle migration of old properties style format of Settings
- [x] move everything over to use the new settings and remove all old references to the old properties
- [x] remove all references to App.settings everywhere
- [x] move loading code to another class

This should be pretty straight forward and provide a much cleaner interface than what the Settings class horribly does now

**Comment by s0cks** [comment]
Good stuff knocking down all teh issues today :D
