### ISSUE TITLE
Use ProGuard to shrink the size of the .jar

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#187]
I think you should look into using proguard to shrink the size of the jar. It also has more features like code obfuscation, optimization and pre-verification.

**Comment by RyanTheAllmighty** [comment]
Nope nope nope nope, never touching that again sorry

**Comment by s0cks** [comment]
I do want to know what happened with this XD

**Comment by Doomsdayrs** [comment]
@s0cks Sorry for the 7 year late reply, but, I can say this is incredibly difficult to setup.

While Android has first party support, Java/Kotlin has ###th class support.

**Comment by RyanTheAllmighty** [comment]
Lol. From my previous comment, can tell it was bad. Used it for version 1 and 2 of the launcher and while I don't remember specifics, I just remember it being a pain
