### ISSUE TITLE
Chop down and Cleanup Utils class

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#188]
I find the Utils class to be seriously crowded and full of garbage code that could be split up, optimized and cleaned up. Thoughts? @RyanTheAllmighty

**Comment by RyanTheAllmighty** [comment]
I definitely agree that this should be done as I already started with the file utils class

**Comment by s0cks** [comment]
Good we are on the same page then :)

**Comment by flaw600** [comment]
Have we finished with this? I think most of Utils has already been split up. @s0cks and @RyanTheAllmighty ?

**Comment by RyanTheAllmighty** [comment]
AFAIK it's still a mess in 3.3.0.0 and not extracted out into enough subclasses yet, but I've not specifically looked recently.

This is definitely one to look into after 3.2.3.2's release

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.
