### ISSUE TITLE
Editing mods for an instance won't show scrollbar when needs to

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#190]
On the edit mods dialog for an instance, if you have more than the height's worth of items (apparently 18) it won't show the scrollbar.

The issues seems to go away when you close and open it.

**Comment by s0cks** [comment]
Interesting, Ill take a look

**Comment by s0cks** [comment]
Not happening on my machine....

**Comment by flaw600** [comment]
Is this similar to #226 ?

**Comment by RyanTheAllmighty** [comment]
This is a separate issue but seems to not occur anymore so closing.
