### ISSUE TITLE
Create more versatile OS class

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#197]
Currently I think we just hook into the OS class in the Mojang package.

I think it would be better to have our own OS class to deal with all OS related things

**Comment by RyanTheAllmighty** [comment]
This should also push alot of the OS related things to this class.

Possibly things like opening file explorer and browser (make a much more versatile method to do so using all the fancy Linux things to determine that) and others

**Comment by s0cks** [comment]
I actually thought about doing that, but decided against it because I was being lazy...
