### ISSUE TITLE
Convert anonymous && non-static inner classes to top-level or static-inner classes

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#199]
I'm leaving this issue here because anonymous and non-static inner classes can cause memory leaks. We use a lot of them so this should be done XD

**Comment by flaw600** [comment]
I’m more interested in how big of a memory leak these types of classes actually cause. If it’s a trivial amount then is it really worth the effort to do go through all the classes?

**Comment by s0cks** [comment]
Its an instance of a class that cant be reached, the size depends on the size of the instance

**Comment by flaw600** [comment]
I know. I meant that the difference in memory usage needs to be measured to determine whether it’s even worth the effort. It’s a significant amount of work, if only cause of the amount of classes we have :P

**Comment by RyanTheAllmighty** [comment]
I personally see this as making things less readable, which if is only a small amount of memory is wasted, then I'd prefer to have things readable over being a tiny bit more memory efficent

**Comment by flaw600** [comment]
Indeed. It makes people have to scroll through code to find a class that’s only ever used once (if it’s used more than once then it shouldn’t be anonymous to begin with) which is extremely annoying because it breaks flow and more than likely scrolling will occur multiple times.

**Comment by flaw600** [comment]
@RyanTheAllmighty are we going to do this? It was my understanding that it was decided that this was unnecessary but I don't have the best memory atm

**Comment by RyanTheAllmighty** [comment]
Personally I'm not bothered, s0cks knows her Java so I usually trust what
she says

**Comment by flaw600** [comment]
@s0cks well now you have 2+ things to work on :P

**Comment by RyanTheAllmighty** [comment]
This has been done with #405
