### ISSUE TITLE
Launcher freeze

### ISSUE THREAD

**Issue by 7osCraft** [ATLauncher/ATLauncher#205]
The launcher freezes after getting player skin
Sorry if my english is bad i'm arabic

**Comment by s0cks** [comment]
Can I have your log?

**Comment by 7osCraft** [comment]
I'm a programmer and there's no anything good in the log it's normal and by the way i'm using version 3.3.0.0

**Comment by 7osCraft** [comment]
just after i added an account and the launcher asked me to switch to the account i clicked yes and it showed a dialog that says downloading skin and after it finished the launcher freezed

**Comment by 7osCraft** [comment]
And I can't give you my log because the launcher freezes and so I can't copy the log also the latest log file is empty i think because the freeze

**Comment by RyanTheAllmighty** [comment]
We don't support non released versions of the launcher. Please use a release version and post any issues with that to https://forums.atlauncher.com
