### ISSUE TITLE
Minecraft versions

### ISSUE THREAD

**Issue by 7osCraft** [ATLauncher/ATLauncher#206]
Why don't you get all minecraft version automatically from minecraft versions json on minecraft servers
so you can get all versions from https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
and get every version from https://s3.amazonaws.com/Minecraft.Download/versions/{VERSION}/{VERSION}.json
And this can add support for snapshots too

**Comment by RyanTheAllmighty** [comment]
We don't do this and have no plans to do this since we control the versions of Minecraft on our own backend and getting the client to get that means we lose that control which we aren't looking to do.
