### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by Wolf68k** [ATLauncher/ATLauncher#209]
Only the first warning messages is used.
I have 2 warning messages each with different names of course. Both mod entries end up using the same one.
I've switched the order that the warning messages are in and it just takes the first one.

**Comment by s0cks** [comment]
What are the warning messages?

**Comment by RyanTheAllmighty** [comment]
Again as per the other issue can you make a 'Ryan-Issue' dev version so I can tinker around :)

**Comment by RyanTheAllmighty** [comment]
Looking at the JSON the backend generates automatically

```
"warnings": {
    "warn1": "Warning message 1",
    "warn2": "Warning message 1"
},
```

It looks like this is something in the conversion process which will mean there should be no need to have to update the launcher to fix this specific issue.

I'll investigate and report back.

**Comment by RyanTheAllmighty** [comment]
Alright this was an issue with the backends code when converting XML->JSON which the launcher uses.

If you just resave any versions affected, it will update the JSON and fix the issue, no launcher update needed for this one!
