### ISSUE TITLE
Auto enable issue

### ISSUE THREAD

**Issue by Wolf68k** [ATLauncher/ATLauncher#210]
This is the only way I can describe it is to use the actual event.

In the DNSTechPack we have Voxel Map (VM) and WorldEdit (WE) set to depends and linked on LiteLoader (LL).
We are making a design change with the optional mods list. VM is still said to be depends but it's not linked. While WE is still depends and linked.
When I check VM it auto checks LL, which is normal and expected. However WE is still greyed out.
The work around is to uncheck and recheck LL, which is a bit of a hassle.

Shouldn't it be that if I check VM, it then auto checks LL, which then makes WE enabled and available to be checked?

**Comment by RyanTheAllmighty** [comment]
Can you make a dev version that I can play around with just called 'Ryan-Issue' so I have access to play around with it to get it to work please.

**Comment by RyanTheAllmighty** [comment]
Alright this is fixed and will be released with version 3.2.3.2 over the next couple of days

**Comment by RyanTheAllmighty** [comment]
LOL @above. It's been over a year and half since you said that you goof.

But for real going out for real in next couple days

**Comment by RyanTheAllmighty** [comment]
Released
