### ISSUE TITLE
When updating/reinstalling an instance on a different version, update optional mod selections as well

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#213]
Otherwise things like [this](http://www.resonant-rise.com/topic/6490-/#entry43576) happen, where when a mod's dependencies change they are not correctly updated. Resonant Rise uses the mod dependency features more extensively than usual, but this can also be an issue for other packs, when a mod gets a new dependency in an update.

**Comment by RyanTheAllmighty** [comment]
Released
