### ISSUE TITLE
New command line arguments

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#214]
Need some new command line arguments:

* --working-dir=C:/Blah: Sets the directory to place all the files in. Must already exist and be a directory
* --clear-downloadable-files: Clears all the files in Downloads/ and Config/Libraries/
* --no-launcher-update: Won't check for a launcher update
* --skip-integration: Won't write it's location to the APPDATA/Application Support folder

**Comment by RyanTheAllmighty** [comment]
Need --no-integration

**Comment by s0cks** [comment]
--working-dir could be replaced with changing the user.dir property

**Comment by RyanTheAllmighty** [comment]
The command line argument is needed for a specific use case in the future :)

**Comment by s0cks** [comment]
oh alright
