### ISSUE TITLE
Mod type options for custom mods should be dependent on Minecraft version

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#218]
Resource packs have completely replaced texture packs in Minecraft 1.6. Any version before that only has texture packs, any version including and after that only has resource packs. Coremods also only exist in versions older than 1.6.

**Comment by RyanTheAllmighty** [comment]
Sounds like a logical idea :+1:

**Comment by flaw600** [comment]
Where do we look at mod type options?

**Comment by RyanTheAllmighty** [comment]
Honestly this issue is so old now I'm not sure the context and issue here

**Comment by RyanTheAllmighty** [comment]
Oh no I know its for the Edit Mods Dialog actually, the drop down when adding a custom mod

**Comment by flaw600** [comment]
Yeah, I'm trying to go through all the issues for 3.2.3.2 so that we can get through them ASAP.

**Comment by flaw600** [comment]
Ok, so I think I found we're giving the various options. I'll try and see if I can close this by the end of the weekend.

**Comment by flaw600** [comment]
@RyanTheAllmighty can you take a look at this? ^

**Comment by flaw600** [comment]
or @dgelessus

**Comment by RyanTheAllmighty** [comment]
Sorry I missed the commit @flaw600, commented on the commit and with those changes ready for a PR to clear up the last of the 3.2.3.2 issues

**Comment by flaw600** [comment]
@RyanTheAllmighty I fixed one of the issues. The other I did a slightly different way because I couldn't figure out how to do it your way but it should end up the same regardless.

**Comment by RyanTheAllmighty** [comment]
Released
