### ISSUE TITLE
Convert Gson to RapidJson

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#222]
Well I wrote a parser for Json today, and we should totally replace Gson with it...it has all the features of Gson and is faster. And as a bonus the size is a total 54kb instead of Gson's 206kb

**Comment by RyanTheAllmighty** [comment]
Honestly I'm not sure about this.

GSON is a well known library with updates and helpful information out there, whereas what you've written isn't.

I mean look at the Toaster thingy we use that you wrote, it's not easily accessible and around anymore.

So at the moment I don't think it's a great idea sorry. There's already way too much going on without needing to bring in more work I'm afraid.

**Comment by s0cks** [comment]
Documentation is being written, and it works the same as Gson
