### ISSUE TITLE
Problem adding multiple extraarguments in XML

### ISSUE THREAD

**Issue by BBoldt** [ATLauncher/ATLauncher#223]
This: 

```
<version>
    <pack>
        <version>1.7.10.Release.5</version>
        <minecraft>1.7.10</minecraft>
        <mainclass>net.minecraft.launchwrapper.Launch</mainclass>
        <extraarguments depends="Minecraft Forge">--tweakClass=cpw.mods.fml.common.launcher.FMLTweaker</extraarguments>
        <extraarguments depends="VoxelMap">--tweakClass=com.mumfrey.liteloader.launch.LiteLoaderTweaker</extraarguments>
        <memory>2048</memory>
        <permgen>256</permgen>
    </pack>
```

Results in this: 
![](http://i.imgur.com/rt9qrOw.png)

https://github.com/ATLauncher/Website-Issues/issues/64

**Comment by RyanTheAllmighty** [comment]
From @majix560 on #286 

> I am thinking of adding liteloader and a minimap mod using liteloader as fully optional to my pack.
But have Forge be required.
Unfortunately though, through the course of a conversation with @RyanTheAllmighty I found out that I can't set liteloader's portion of the extraarguments tag as a depends without doing the same to forge's portion.
>
> [Pastebin of relevant Discord chat log](http://pastebin.com/tb1Jepjt).

**Comment by RyanTheAllmighty** [comment]
This is now possible to do with the new loader syntax from #336
