### ISSUE TITLE
Issue deleting the options.txt file

### ISSUE THREAD

**Issue by Thepiggy** [ATLauncher/ATLauncher#224]
So if I do this in my xml this happens:
<a href="http://imgur.com/86V40tQ"><img src="http://i.imgur.com/86V40tQ.png?1" title="source: imgur.com" /></a>
the first one works, but the second one does not, I've not tried switching them yet.

**Comment by Thepiggy** [comment]
ok so I switched them to look like this:
<a href="http://imgur.com/2PkFnqK"><img src="http://i.imgur.com/2PkFnqK.png?1" title="source: imgur.com" /></a>
Still did not work...

**Comment by RyanTheAllmighty** [comment]
I'm having issues replicating this. My tests show no issues deleting the options.txt file.

If this is still an issue can you please provide a dev version for me to test out where the issue occurs please.

**Comment by RyanTheAllmighty** [comment]
I know what this is.

During the process of updating/reinstalling the options.txt file is saved and kept between update/reinstall.

This is an intended feature to keep user data between update/reinstall and cannot be circumvented sorry since it contains custom user data.
