### ISSUE TITLE
Log upload errors should be more detailed

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#225]
Every now and then people on the forums have trouble with the Upload Log feature of the console, because they get a "Missing paste text" error. Is that just the message that the server returns, or could that be made more clear? (Looking at [com.atlauncher.thread.PasteUpload](https://github.com/ATLauncher/ATLauncher/blob/master/src/main/java/com/atlauncher/thread/PasteUpload.java), the log text is encoded in ISO-8859-1, would that cause issues with Unicode chars > 0xFF in the log?)

**Comment by RyanTheAllmighty** [comment]
Yes that's an error the server returns. I'm planning on at some point switching to a custom lighter paste system.

I'll check to see if UTF8 can be sent to the paste server and if so I'll switch it to that.

**Comment by RyanTheAllmighty** [comment]
Yup no issue with UTF-8 so I'll switch to that. No idea why I went with ISO-8859-1, but UTF-8 it is now.

**Comment by RyanTheAllmighty** [comment]
Alright all done pending update to 3.2.3.2

**Comment by RyanTheAllmighty** [comment]
Released
