### ISSUE TITLE
No scrollbar in "Packs" list

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#226]
Well, there is a scrollbar, but without the thing that scrolls in it. You can still click into the scrollbar and it will move up or down, but you can't "grab" the scroll thing anymore. Basically it acts like it is zero pixels high.

![missingscrollbar](https://cloud.githubusercontent.com/assets/6641959/9973360/e20a9ab2-5e71-11e5-8d16-187d92b97466.png)

This screenshot is taken on my main computer (Windows 7 running Java 8 Update 60, 64-bit), though I can reproduce this with a fresh ATLauncher install on a different computer (Windows 10 running Java 8 Update 64, 32-bit).

**Comment by RyanTheAllmighty** [comment]
Yeah a few people have reported this to me.

I have no idea when this issue appeared or the circumstances on which it appears, so I'll need to do some investigation

**Comment by craignagovan** [comment]
Wanted to report the same issue. Win 7, Java 8u71, 64-bit, offline.

**Comment by RyanTheAllmighty** [comment]
Yup. As far as I'm aware something changed in one of the Java updates which causes the issue where the scrollbar will disappear if there is too much in the panel that the scrollbar shrinks past some value at which it just disappears.

**Comment by flaw600** [comment]
So this is a Java issue specifically?

**Comment by RyanTheAllmighty** [comment]
Yes. I believe so anyway. Newer versions of JScrollPane I'm guessing messes with the default draw values or something as older versions of Java 7 didn't have the issue, only popped up in later Java versions

**Comment by flaw600** [comment]
So can we use custom draw values? Because if we can't do anything, I'm not sure that this is really a fixable bug

**Comment by RyanTheAllmighty** [comment]
I'm not sure. I'm hoping there is something, I've not researched into it so hopefully

**Comment by s0cks** [comment]
This is a timing bug in swing. Basically when the scrollbar is constructed its not getting placed into the scroller before its resized. Effectively giving you this

**Comment by flaw600** [comment]
@s0cks I'm not an expert at Swing. Can you deal with this please?

**Comment by RyanTheAllmighty** [comment]
Some examples of bug reports of this issue:

https://bugs.openjdk.java.net/browse/JDK-8134827
https://bugs.openjdk.java.net/browse/JDK-8134828

**Comment by RyanTheAllmighty** [comment]
This seems to solve the issue, for me anyway:

```java
UIManager.put("ScrollBar.minimumThumbSize", new Dimension(50, 50));
```

Put it in https://github.com/ATLauncher/ATLauncher/blob/master/src/main/java/com/atlauncher/App.java#L412

**Comment by RyanTheAllmighty** [comment]
Considering this stops being an issue in Java 8u72 it may be best to just advise users with the issue to upgrade Java and be done with it since it is an actual Java bug.

So with that I'll close this

**Comment by RyanTheAllmighty** [comment]
This is a Nimbus L&F issue only it seems and the code I posted above will sometimes work and sometimes won't work depending on the amount of content in the panes still

**Comment by RyanTheAllmighty** [comment]
Okay I'm adding in the workaround to both 3.2.3.2 and 3.3.0.0 branches and untagging the milestone but leaving the issue open

**Comment by flaw600** [comment]
Hmm. I'm really hoping that @s0cks can take a look at this because I don't
know a whole lot about debugging Swing.

On Mon, Feb 8, 2016 at 2:51 AM, Ryan Dowling <notifications@github.com>
wrote:

> Okay I'm adding in the workaround to both 3.2.3.2 and 3.3.0.0 branches and
> untagging the milestone but leaving the issue open
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ATLauncher/ATLauncher/issues/226#issuecomment-181258811>
> .
>



-- 
Jassi Sikand

jsikand@sbcglobal.net
sikand@gmail.com
gsikand@hotmail.com

**Comment by RyanTheAllmighty** [comment]
Released
