### ISSUE TITLE
Better handling of download="direct"

### ISSUE THREAD

**Issue by leagris** [ATLauncher/ATLauncher#228]
Having a resource pack as download="direct", ATLauncher store a cached copy of the file into the `Downloads` directory.

When upgrading or re-installing, it does not download the file again, but take the cached copy from `Downloads`.

This is an issue with our custom built and nightly updated `Fanver_Beyond_Reality.zip` resource pack file.

On reinstall or update, players are not getting the updated file from URL `http://soartex.cursecdn.com/fanver/modded/1.7.x/modpacks/atlauncher/Fanver_Beyond_Reality.zip`

Forcing an MD5 on the file is not an option as it would not reflect the remote file change.

What we need is; A bit of more clever check on cached Downlaods for `download="direct"` assets by ATLauncher.

When file is `download="direct"`, ATL should issue an HTTP HEAD request as example below:

``` HTTP
HEAD /fanver/modded/1.7.x/modpacks/atlauncher/Fanver_Beyond_Reality.zip HTTP/1.1
Host: soartex.cursecdn.com

HTTP/1.1 200 OK
Date: Wed, 28 Oct 2015 22:15:04 GMT
Content-Type: application/x-zip-compressed
Content-Length: 173279065
Connection: keep-alive
Set-Cookie: __cfduid=d96b57299ebf52d952c6287365a8709a61446070504; expires=Thu, 27-Oct-16 22:15:04 GMT; path=/; domain=.cursecdn.com; HttpOnly
Cache-Control: public, max-age=60480000
Last-Modified: Wed, 28 Oct 2015 00:13:20 GMT
CF-Cache-Status: REVALIDATED
Expires: Wed, 27 Sep 2017 22:15:04 GMT
Accept-Ranges: bytes
Server: cloudflare-nginx
CF-RAY: 23c9ff4cf1240c7d-AMS
```

Compare `Content-Length:` with cached file size in `Downloads`
Compare `Last-Modified:` with cached file date
If any of size or date differs: re-download file.

Optionally, this remote Head size and date checks could be switched on with some 
`download="direct newest"`

Our current setting for the resource file:

``` XML
    <mod name="Soartex Fanver Resource Pack" version="1.7.10-Latest" url="http://soartex.cursecdn.com/fanver/modded/1.7.x/modpacks/atlauncher/Fanver_Beyond_Reality.zip" file="Fanver_Beyond_Reality.zip" download="direct" type="resourcepack" server="no" client="yes" optional="yes" colour="brightred" recommended="no" website="http://soartex.net" authors="many" description="Soartex Fanver Resource Pack for Beyond Reality"/>
```

**Comment by RyanTheAllmighty** [comment]
This is kind of similar to #216 but you're seeking to use the headers as an indication to get the newest rather than force downloading it every time.

Adding to the list of download="" attribute options is not something I wish to do since it follows the same path as a direct normally would, so instead I'll opt for adding another attribute much as I did with force="" in #216 but have it check headers for 'newness'

Either way this is a good idea and I'll get it setup and let you know the details here how to activate it for the next launcher update, whenever that may be :\

**Comment by RyanTheAllmighty** [comment]
Okay so what I'm going to do is add in a check that when any direct download is provided for a mod, it will check 2 things:

- Content-Length
- MD5 if provided by a HEAD request

If one or both of these don't match the file already on a clients computer it will force a redownload of the file.

So there will be no extra steps necessary in your XML to enable this, it will just be there by default.

**Comment by RyanTheAllmighty** [comment]
Alright @leagris this is all done now. I'll ping you again and close this issue once version 3.2.3.2 is released with this fix in it.

**Comment by leagris** [comment]
@RyanTheAllmighty Awesome, 100 Thank-You!

**Comment by RyanTheAllmighty** [comment]
Released
