### ISSUE TITLE
404 Not found with Server files download from ATL Portal 

### ISSUE THREAD

**Issue by leagris** [ATLauncher/ATLauncher#229]
Look like server files are not uploaded to the CDN since a few days at least.
https://www.atlauncher.com/pack/BeyondReality
`404 Not Found
nginx`

```xml
<crawln> Hmm can anyone tell me why a Download server link is returning a 404 on the atlauncher site
```

**Comment by RyanTheAllmighty** [comment]
Yeah the drive on the storage server is full. I'll clean it up a bit and get it to regenerate the missing Beyond Reality ones and then close this issue when done.

**Comment by RyanTheAllmighty** [comment]
But for future use, please use ATLauncher/Website-Issues for anything that's not related to the launcher

**Comment by RyanTheAllmighty** [comment]
This issue was moved to ATLauncher/Website-Issues#71
