### ISSUE TITLE
Study on OSS maven library incompatiblities and vunerabilities: google-guava

### ISSUE THREAD

**Issue by raux** [ATLauncher/ATLauncher#230]
I originally wrote this email to certain members maybe this issue can get more visibility i the issue tracker.

Dear Github OSS Developer,

My name is Raula Kula, a research assistant prof at Osaka University, Japan. Currently I am studying the maintenance of Maven Libraries. I am currently focused on OSS incompatibilites, release management and the varying reasons for library migration.

As a part of my study I particularity focused on the google guava library. https://github.com/google/guava. Particuarly I am interested in the migration to guava library version 18.0. 

We noticed that your project on Github is still configured to depend on a previous incompatible version of guava (17) at https://github.com/ATLauncher/ATLauncher/blob/master/pom.xml

We understand that there are many reasons for not migrating, thus we be appreciate if you could simply detail the following:

1. Were you aware of this new library and what features it could add to your project?
2. What are some factors that influence you not to update?
3. What would be a key factor that would inspire you to migrate to the next release? 

Also feel free to detail any other information to help us understand your decision. Again, thank you for taking your time off your busy schedule and hope to hear from you soon.

Sincerely,
Raula

**Comment by RyanTheAllmighty** [comment]
External dependency, no control, 4 months without a commit so not being updated currently
