### ISSUE TITLE
Random Crash issue reading from theme zip

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#232]
More info at https://forums.atlauncher.com/thread-12145.html

**Comment by flaw600** [comment]
Is the issue still occurring. I wasn't sure if @dgelessus solved the issue or not

**Comment by RyanTheAllmighty** [comment]
I'm not sure if this is an issue with the launcher or not, possibly just an issue with the single user. I'm adding this as unconfirmed and closing this
