### ISSUE TITLE
cant compile under netbeans

### ISSUE THREAD

**Issue by resinate** [ATLauncher/ATLauncher#235]
i dont know what im doing excatly here so, al;l im doing is trying to make atlauncher work with the java 9 fix someone posted for this and compile it so i can play. i have constants.java in right place but in netbeans im seeing errors all over the place

**Comment by RyanTheAllmighty** [comment]
Would need to know more details. Logs and screenshots showing the errors as well as details about your environment such as IDE version and JDK version.

**Comment by resinate** [comment]
im trying to apply this
https://github.com/ATLauncher/ATLauncher/pull/117
so i can use at launcher to play on java 9

**Comment by RyanTheAllmighty** [comment]
That's a year old merged pull request meaning its been released in the main code base for a long time now. If you're having issues with Java 9 and the launcher please create a new issue, but be warned we don't officially support Java 9 as its not officially released.

**Comment by resinate** [comment]
how do u fully disable this? -XX:+CMSIncrementalMode it seems that its still in the launcher, and i just wanna disable it
