### ISSUE TITLE
Feature Request: Reverse Dependency

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#237]
At this time, mods that depend on a "parent" mod (a library or somesuch) will cause the parent mod to automatically be selected when it is selected.  However, if the user decides to disable a pre-enabled mod, there should be an option for dependencies to automatically disable when all dependents are disabled.

For example, ReactorCraft and ElectriCraft both depend on RotaryCraft.  All three depend on DragonAPI, as does Expanded Redstone and GeoStrata.  If all the mods are disabled, then DragonAPI should self-disable as well, since it does not do anything itself, and all the mods that depend on it are not going to be installed.

However, the option should still exist to not have a reverse-dependency; in the above example, ReactorCraft and ElectriCraft both depend on RotaryCraft.  However, unlike DragonAPI, RotaryCraft definitely has a purpose for the game, and should _not_ auto-disable if ElectriCraft and ReactorCraft are disabled.

**Comment by RyanTheAllmighty** [comment]
Sounds simple enough. If all child mods to a parent are unchecked then uncheck the parent mod as well.

**Comment by RyanTheAllmighty** [comment]
Could you provide some examples of XML and maybe a simple text diagram showing how it should look and work as I'm struggling to exactly grasp what your requesting.

**Comment by reteo** [comment]
For example, the following heavily-simplified XML entries:

```
      <mod name="DragonAPI" />
      <mod name="RotaryCraft" depends="DragonAPI" />
      <mod name="ElectriCraft"  depends="RotaryCraft"/>
      <mod name="ReactorCraft" depends="RotaryCraft"/>
```

DragonAPI is required by all the mods listed.  RotaryCraft is required by ElectriCraft and ReactorCraft.

As it stands now, if someone puts a check in "ReactorCraft" in the instance setup, it also adds a check for RotaryCraft, which adds a check for DragonAPI.  If they change their mind, and ReactorCraft is unchecked, the check marks for RotaryCraft and DragonAPI remain.

Now, this is not necessarily a bad thing; RotaryCraft _is_ a mod in itself, and may still be wanted by the player.

However, if the player then unchecks RotaryCraft, the check mark for DragonAPI will remain checked.  This is a bad thing; DragonAPI is solely a prerequisite for other mods, and if no mods are using it, it is taking up memory without actually being used for anything.  Some modpack authors (myself included) would take the extra step to add `hidden="yes"` to DragonAPI, in order to limit the player's view to those mods that the player actually chooses from, rather than their prerequisites.

What I am requesting is something like `ancestor="RotaryCraft,ReactorCraft,ElectriCraft"` for DragonAPI, so it knows to remove itself when all mods it is an ancestor for are no longer enabled.

**Comment by RyanTheAllmighty** [comment]
Alright that makes more sense. I was kind of getting the idea from the original issue but this explanation makes it cleared.

**Comment by reteo** [comment]
Hmmm... maybe the attribute name should be "supports" instead of "ancestor"; after all, the mods are not the ancestors of this one, it's the other way around. ;)

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

Many packs don't go into this level of detail of optional mods anymore.
