### ISSUE TITLE
Feature Request: Multiple-Level Nesting

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#238]
Linked mods are a really nice feature; for example, having all the buildcraft modules being linked to Buildcraft makes it very clear they're sub-components of the whole.  However, it would be nice for multiple levels of nesting to be possible.

To expand on the example:  Buildcraft consists of several modules:  Core, Energy, Factory, Builders, Transport, Silicon, and Robots.  There are also expansions to Buildcraft; for example, Logistics Pipes.  Logistics Pipes depends on Buildcraft Transport, because the mod is an overhaul of Buildcraft's pipe system.

As the launcher currently stands, linking Logistics Pipes to Buildcraft Transport will simply put them both at the same level under Buildcraft, and disabling Buildcraft will disable Buildcraft, but Logistics Pipes will remain checked and accessible.  The only way to resolve this issue is to make Logistics Pipes depend on Buildcraft Transport, but while this does force LP down when Buildcraft is disabled, it does not explicitly show the relationship between Buildcraft Transport and Logistics Pipes.

What I am requesting is multi-level nesting, so that Logistics Pipes can be a child of Buildcraft Transport, which itself can be a child of Buildcraft, so that the resulting menu will show as follows:

```
+-Buildcraft
  +-BC Energy
  +-BC Factory
  +-BC Transport
    +-Logistics Pipes
  +-BC Builders
```

...and so on.

**Comment by RyanTheAllmighty** [comment]
This is a large change so may not become available for a while.

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

Many packs don't go into this level of detail of optional mods anymore.
