### ISSUE TITLE
Feature Request: Orphan Mod File Identification

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#239]
The admin website includes the ability to automatically upgrade mods to new versions.  However, unless the player manually removes the now-orphaned versions of the mods, the jarfiles will continue to build up, and cleanup of orphaned files would be a real grind, as the modpack admin would have to go through all available versions of the modpack to make sure that each single jarfile is not otherwise being used before they could comfortably remove it, as deleting a file linked to an existing modpack version could cause that version to be removed from the launcher due to missing files.

So, what I would request is for a way for the folder view to show the admin if a file is being used by any of the versions' XML files.  This allows modpack authors to ensure that they are not taking any more of the launcher server's hosting space than is actually necessary for the modpacks they're hosting.

**Comment by RyanTheAllmighty** [comment]
This issue was moved to ATLauncher/Website-Issues#74
