### ISSUE TITLE
High DPI issues

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#240]
Something something High DPI, something something doesn't scale well, more details at https://forums.atlauncher.com/thread-12353.html

**Comment by flaw600** [comment]
Just to make a note, but High DPI seems to be a Windows issue and not an ATLauncher issue specifically. That's not to say that ATLauncher may not have issues, but that Windows does weird stuff with High DPI screens. I'll take a look at it probably sometime this week.

**Comment by flaw600** [comment]
Actually, it's a Java issue. There are a couple of work arounds but it's a known Java issue, especially in Java 8. The link that follows shows the workarounds. It doesn't seem like something that we can fix on our end but instead we could probably make a warning to show users how to get around it. [](http://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display)

**Comment by RyanTheAllmighty** [comment]
Alright good to know

**Comment by flaw600** [comment]
So I researched a bit more. It's a Java issue but one that we could potentially work around if we added the [JNA library](http://stackoverflow.com/questions/606820/is-there-a-java-library-to-access-the-native-windows-api) and if the Win32 API called setDPIAware() still exists, we call it to make the system not try and scale which should result in better looking windows per [here](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6395346). However, imo, it'd be better to wait for Oracle to fix this themselves in Java than us trying to haphazardly implement a little-known API. Your call as always, @RyanTheAllmighty

**Comment by RyanTheAllmighty** [comment]
Yeah it can be fixed with compatibility options in Windows for those who run into the issue so for now I don't feel it necessary to take any action.

**Comment by flaw600** [comment]
Yup. Although, maybe put it in the FAQ so that the users who do run into it can know what to do?

**Comment by RyanTheAllmighty** [comment]
Yup @dgelessus if you can update the FAQ about this issue that'd be great. It shouldn't come up much but a simple entry should be great.

This is a quick how to I've found for Windows since I believe you're on a Mac.

Right click the exe and select properties, go to Compatibility tab and check the "Disable display scaling on high DPI settings."

**Comment by dgelessus** [comment]
Done: https://forums.atlauncher.com/announcement-5.html#windows-high-dpi
