### ISSUE TITLE
Possible issue with Curse direct links

### ISSUE THREAD

**Issue by GodNero** [ATLauncher/ATLauncher#241]
Attempting to download Journey Map I kept getting a html file instead, while this issue might be attributed to my poor XML coding I figured i would share this for your review.

Here are the two code snippets I used:
---
Broken snippet:

```xml
<mod name="Journey Map" version="5.1.3" url="http://minecraft.curseforge.com/projects/journeymap-32274/files/2269314/download" file="journeymap-1.7.10-5.1.3-unlimited.jar" download="direct" type="mods" optional="yes" selected="no" recommended="no" server="no" group="minimap" website="http://journeymap.techbrew.net/" donation="https://www.patreon.com/techbrew?ty=h" authors="techbrew" description="JourneyMap is a client mod for Forge which maps your Minecraft world in real-time as you explore. You can view the map in a web browser or in-game as a Minimap or full-screen." />
```

File that it downloads (appears to be a renamed html file) - https://onedrive.live.com/redir?resid=65FABF74A53FA5BE!277362&authkey=!AOLbyFGLZ3A83IE&ithint=file%2cjar

---
Working snippet:

```xml
<mod name="Journey Map" version="5.1.3" url="http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2269314/download" file="journeymap-1.7.10-5.1.3-unlimited.jar" download="direct" type="mods" optional="yes" selected="no" recommended="no" server="no" group="minimap" website="http://journeymap.techbrew.net/" donation="https://www.patreon.com/techbrew?ty=h" authors="techbrew" description="JourneyMap is a client mod for Forge which maps your Minecraft world in real-time as you explore. You can view the map in a web browser or in-game as a Minimap or full-screen." />
```

This second snippet does download the correct file.
---
If this is not an error on my part the biggest change in the code used was changing *curse.com/projects* to *curse.com/mc-mods/*

**Comment by dgelessus** [comment]
The [first link](http://minecraft.curseforge.com/projects/journeymap-32274/files/2269314/download) gives a HTML code of "307 Temporary Redirect" (pointing to [here](http://addons.cursecdn.com/files/2269/314/journeymap-1.7.10-5.1.3-unlimited.jar), which returns "302 Found" and redirects [here](http://addons-origin.cursecdn.com/files/2269/314/journeymap-1.7.10-5.1.3-unlimited.jar)). The [second one](http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2269314/download) gives a "301 Moved Permanently" and redirects to the first link. And apparently that makes a difference? Odd.

**Comment by RyanTheAllmighty** [comment]
Odd that this is now working correctly for me now.

I've just tested with the following XML:

```xml
<version>
    <pack>
        <minecraft>1.7.10</minecraft>
        <version>1.0.0</version>
    </pack>
    
    <mods>
        <mod name="Journey Map (Not Working)" version="5.1.3" url="http://minecraft.curseforge.com/projects/journeymap-32274/files/2269314/download" file="journeymap-1.7.10-5.1.3-unlimited-not-working.jar" md5="6c2ec9c84f91e44e9b37e7aacc96da8f" download="direct" type="mods" server="no" website="http://journeymap.techbrew.net/" donation="https://www.patreon.com/techbrew?ty=h" authors="techbrew" description="JourneyMap is a client mod for Forge which maps your Minecraft world in real-time as you explore. You can view the map in a web browser or in-game as a Minimap or full-screen." />
        
        <mod name="Journey Map (Working)" version="5.1.3" url="http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2269314/download" file="journeymap-1.7.10-5.1.3-unlimited-working.jar" md5="6c2ec9c84f91e44e9b37e7aacc96da8f" download="direct" type="mods" server="no" website="http://journeymap.techbrew.net/" donation="https://www.patreon.com/techbrew?ty=h" authors="techbrew" description="JourneyMap is a client mod for Forge which maps your Minecraft world in real-time as you explore. You can view the map in a web browser or in-game as a Minimap or full-screen." />
    </mods>
</version>
```

So it must have been a temporary issue with Curse's CDN @GodNero

I'll add in checks for 307 redirect code they used and make sure the launcher follows it regardless in the future.
