### ISSUE TITLE
Switch to Gradle

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#242]
As title states, I'd like to look into switching to Gradle again on a more serious and technical perspective

**Comment by jamierocks** [comment]
Yes - Dreams do come true.

I'm happy to help with this ;)

**Comment by flaw600** [comment]
But I just got used to Maven on Eclipse not that long ago :p

**Comment by RyanTheAllmighty** [comment]
Alright I'm happy to give the go ahead with this for the 3.3.0.0 branch.

I won't have the time to completely do this conversion since I'm unfamiliar with Gradle. If you're more familiar and willing @jamierocks, please feel free to work on this and make a PR, it'd be very much appreciated :)

**Comment by jamierocks** [comment]
I'll get to that tonight, if not tomorrow ;)

**Comment by flaw600** [comment]
When you do this, can you provide a guide on how to transition from maven to gradle?

**Comment by RyanTheAllmighty** [comment]
We are now using Gradle. It's much clearer
