### ISSUE TITLE
Provide dropdown for Java versions

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#252]
I'd like to include a dropdown in the Settings/Java tab to allow selecting any version of Java installed on the users system to better control environments for those who have multiple versions.

This should also allow us to list all Java versions on startup and pick the best one on startup if one isn't provided. This will solve the issue of users with 32 and 64 bit Java and 32 bit is used by default.

**Comment by flaw600** [comment]
You can set 32 bit Java to be the default on a 64 bit system? Interesting. Anyway, I made a note on #253 about this.

**Comment by RyanTheAllmighty** [comment]
Java can be very weird sometimes.

I've seen many cases where a 32 bit install will take precedence over a 64 bit install on a 64 bit system. It's Java

**Comment by RyanTheAllmighty** [comment]
But this issue may also be directly affected by the outcome of #255.

If we're bundling in a JRE version with the launcher to use for Minecraft, this dropdown will even more necessary in order to still allow control to users so we're not forcing them to run our JRE.

So if #255 is completed for 3.2.3.2 then this may also need to be pushed up to 3.2.3.2 milestone.

**Comment by dgelessus** [comment]
Sadly this doesn't fix the issue for servers, which still use the system default Java...

**Comment by RyanTheAllmighty** [comment]
Yeah unfortunately not to much we can do about that without writing a complete custom wrapper.

**Comment by RyanTheAllmighty** [comment]
This was released
