### ISSUE TITLE
Better system information logging

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#253]
I'd like to include some more information when logging on startup to assist troubleshooting.

I'd like to include things such as:
- GPU information
- CPU information
- Java installs (listing all installs on the computer) related in part to (#252)

I'm not sure what can be retrieved or not, this will have to be investigated.

**Comment by flaw600** [comment]
I'm not sure about the CPU/GPU info, but Java installs should be able to be gotten. We may have to use native method calls for the first 2 which would be burdensome imo

**Comment by RyanTheAllmighty** [comment]
Yeah this information can be retrieved using commands unique to each system.

While a pain yes, it could become vital to possible troubleshooting.

**Comment by s0cks** [comment]
@RyanTheAllmighty I know how to do said things but it requires some C/C++ code, I don't mind writing the code for it but we should figure out a portable way of doing it first.

**Comment by RyanTheAllmighty** [comment]
I don't see why C/C++ is required for this?

Windows provides wmic for querying that stuff and if Windows can do it, I'd assume linux and osx would have their own version.

A quick Google leads me to believe each OS has a command to get them.

**Comment by s0cks** [comment]
GPU and CPU information to get it programmatically I believe you have to use C/C++ for it, but I could be wrong @RyanTheAllmighty

**Comment by RyanTheAllmighty** [comment]
AFAIK it's a simple process run and parsing much like is already done for Java version parsing at the moment

**Comment by s0cks** [comment]
@RyanTheAllmighty Getting it programmatically is better than running a process to get it. Its a bit more code to do, but isnt dependent on having to spawn a process and manage that.

**Comment by RyanTheAllmighty** [comment]
Honestly that doesn't bother me whatever way it's done as long as it works in the end

**Comment by flaw600** [comment]
Better is subjective. Personally I'd prefer doing a process because I don't want to have to deal with C++ code (and it'd be significantly more code imho) but I'm not working on it so do whatever @s0cks

**Comment by flaw600** [comment]
@RyanTheAllmighty ooc, what do you want in terms of CPU and GPU info?

**Comment by RyanTheAllmighty** [comment]
Just names really

**Comment by flaw600** [comment]
I'd like to posit something. The CPU/GPU Info is given in dxdiag on Windows. It's given in System Information on Mac. I'm going to posit that Linux users are advanced enough to find them. So why do we need to get it again ourselves?

**Comment by flaw600** [comment]
Apparently the [SIGAR API](https://support.hyperic.com/display/SIGAR/Home) can be used for this, although it's been known to have quirks with 64-bit systems. Again, I'd like to posit the above, that if we need debug info, we can have Windows users use dxdiag, Mac users use System Information or sysdiagnose, and linux users can use /proc. It'd be a lot easier than trying to log the stuff you want.

**Comment by RyanTheAllmighty** [comment]
It's really not difficult to log this stuff. Every OS has it's own way of querying this information with a single command line probably, I wont really know until I look into it, but definitely not something that should be difficult.

As for getting users to provide this information, sure for more detailed stuff, if they're competent enough to be able to do so, but having 2 simple lines stating the CPU and graphics card name would be excellent in quick diagnosis.

**Comment by flaw600** [comment]
It's certainly not easy. You have to call a process and then parse that info. Is it difficult? It's certainly time consuming as there's no standard Linux way to do it, and Mac is weird. Personally I think it'd be easier to look this up on system info but obviously it's your call

**Comment by RyanTheAllmighty** [comment]
Would like to combine this with the current `getMemory` go binary if possible to avoid having multiple binaries.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.0.0
