### ISSUE TITLE
Switching between different operating systems bungs up the libraries

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#257]
When an instance is installed it will install the platform specific libraries for the operating system/arch it was installed on.

So when installing an instance on Windows on a USB drive and then taking that to a OSX computer it won't launch as it has the Windows libraries.

This is definitely something that could be sorted out on launch so that it doesn't require a reinstall.

A very minor inconvenience but one that is definitely worth looking at.

**Comment by flaw600** [comment]
What do you want as a solution? That all libraries be installed?

**Comment by RyanTheAllmighty** [comment]
Not sure just yet, needs to be looked into.

Installing them all may lead to issues, not sure, don't think so since they're classpath loaded in on launch.

I think the best option would be to check the libraries when play is clicked and create new fields in the instance.json for the OS and version it was installed on so that if they change, the libraries are reloaded in. Sounds like the best solution, but may be other ones.

**Comment by flaw600** [comment]
Can this be pushed back to 3.3.0.0? I feel like pushing this onto the present milestone will only delay this from being launched, especially since testing this will take up significant time

**Comment by RyanTheAllmighty** [comment]
Unfortunately this cannot. This must be released in the 3.2.3.2 branch as third parties are awaiting for this fix.

**Comment by flaw600** [comment]
Has a direction been settled on for this?

**Comment by RyanTheAllmighty** [comment]
Moving to backlog to resolve at a later date

**Comment by RyanTheAllmighty** [comment]
This has been implemented
