### ISSUE TITLE
Feature Request: Auto-unselection without exclusion

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#261]
In more recent layouts of my modpack, I came across a situation where mods under the normal layout should be recommended, but with an alternate option, should be disabled by default, but still made available for players if they wish.

To clarify: I am adding a "Skyblock" option to Survival Industry.  By default, the game balance requires Somnia and Spice of Life to make the game sufficiently difficult.  However, in the case of a skyblock game, these mods would make the game hardcore; too difficult for the average skyblock player.

What I would like to be able to do is set it so that Somnia and Spice of Life are recommended by default, but then they are unselected when Ex Nihilo is selected.  Additionally, I want them to be re-selectable, meaning that a player can select "Ex Nihilo," which unchecks "Spice of Life" and "Somnia," but when the player decides he wants the added challenge of those mods, selecting them won't uncheck Ex Nihilo as a conflict.

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

Many packs don't go into this level of detail of optional mods anymore.
