### ISSUE TITLE
Unable to run ATLauncher on El Capitan with Java 8.

### ISSUE THREAD

**Issue by ghost** [ATLauncher/ATLauncher#263]
Hi,

I needed to use https://github.com/federkasten/appbundle-maven-plugin to make it work with El Capitan and Java 8.  Otherwise I only get the `Need Java 6 SE` popup.

Thoughts?  I'll gladly submit I PR if desired.

**Comment by RyanTheAllmighty** [comment]
Yeah we resolved this issue in our 3.3.0.0 branch.

Unfortunately it won't be put in the current 3.2 series due to it introducing gotchas for OSX users. 

But thanks for bringing it up regardless.

**Comment by MindTooth** [comment]
The issue were on the 3.3.0 branch if I recall correctly.

**Comment by RyanTheAllmighty** [comment]
Hmm it definitely shouldn't happen on 3.3.0.0 branch.

Please provide some more information, logs etc that you can.

**Comment by MindTooth** [comment]
I can manually run the `.jar` file.  I suspect the `Info.plist` file to be broken.  I'll try to debug more though.

http://dclunie.blogspot.no/2014/10/keeping-up-with-mac-java-bundling-into.html

**Comment by RyanTheAllmighty** [comment]
Odd.

I'd tested the 3.3.0.0 branch in a bunch of VM's ages ago and it worked great, even had others do it also.

It's possible El Capitan broke something, I hate having to deal with OSX bundling, it seems to be the worse, plus I have no test environments which sucks :)

I'm happy to accept a PR on the 3.3.0.0 branch with your solution.

**Comment by MindTooth** [comment]
DISLAIMER!  I don't program in Java.  So I really don't know what I'm doing, only trying to make it work for my self.

The changes I've done so far.  Not sure if I need to remove the check, or alter it.
https://github.com/MindTooth/ATLauncher/tree/new_appbundle
