### ISSUE TITLE
Are localization files of ATLauncher still being updated?

### ISSUE THREAD

**Issue by claybiockiller** [ATLauncher/ATLauncher#266]
I'm Clayblock, mod localizer from China.
I found that Weblate of ATLauncher replaced by Jenkins. Is localization work still in progress?

**Comment by RyanTheAllmighty** [comment]
Short answer no.

We have a ATLauncher/Translations repository here on github which holds the Translations, but the weblate instance is currently offline.

I hope to get it back up and running when I get to do some server maintainence in the coming weeks.
