### ISSUE TITLE
ATL Servers List not correctly showing uptime.

### ISSUE THREAD

**Issue by Zilacon** [ATLauncher/ATLauncher#268]
Alright so this has been a problem for a while. My servers are online 24/7, every other vote site can confirm this with a 95%+ uptime rating. However with ATL it constantly shows my server offline even when players are online playing.

Right now it shows my server offline, my server shows over 55 minutes uptime from its last 6 hours restart.

This is my listing: https://servers.atlauncher.com/server/ApocalypticGamingNetwork

Any fix for this would be nice, as showing the server being so unstable makes us look bad.

**Comment by RyanTheAllmighty** [comment]
Website outside go to https://www.github.com/ATLauncher/Website-Issues
