### ISSUE TITLE
Deleting an instance happily deletes files elsewhere too

### ISSUE THREAD

**Issue by StefanTT** [ATLauncher/ATLauncher#270]
I have my resourcepacks in an extra directory somewhere else, outside the minecraft instances.
To use the texture pack I make a symbolic link from the resourcepacks directory to the texture pack.
When the instance is deleted, the symbolic link is followed and the resource packs are deleted too.

This is a quite critical bug for me as the resource pack happens to be a project directory as I work on icon packs. The whole directory structure gets deleted :-1: 
Luckily I did not loose anything vital this time. Hopefully.

**Comment by dgelessus** [comment]
What operating system are you on? This has been reported (and fixed) previously,the launcher *should* ignore symlinks when deleting instances...

**Comment by StefanTT** [comment]
This is on Linux with openjdk version "1.8.0_91"
The launcher is version 3.2.3.1

I had a quick look at the launcher's code. It looks like you have your own code for deleting files, which looks similar to the apache commons file utils.  Would it be an option to use the original file utils for doing the job? If yes then I can do a quick test if this would fix the problem.

**Comment by RyanTheAllmighty** [comment]
We shouldn't be deleting symlinks as per https://github.com/ATLauncher/ATLauncher/blob/master/src/main/java/com/atlauncher/utils/Utils.java#L968

But it's possible that code is failing on your machine for some reason.

We don't include Apache commons file utils due to not wanting to increase the file size, but a quick test on that bit of code comparing it to what they do in apache commons might help diagnose the issue

**Comment by StefanTT** [comment]
My problem is a symlink from the resourcepacks to a directory with the textures:
..../resourcepacks/myres  ->  /somewhere/else/myres

I did a quick test with a symlink.
A File object of a symlink to a directory states:
It is a directory?       true
It is a file?                false
It is a symlink?         true

Looking at the code https://github.com/ATLauncher/ATLauncher/blob/master/src/main/java/com/atlauncher/utils/Utils.java#L960 it shows that the recursive deletion in line 960 happens before the symlink detection in line 968 happens. I think the symlink detection needs to be done prior to the recursive deletion.

**Comment by RyanTheAllmighty** [comment]
That is correct. Nice spot. Just bringing it up above that check should do

**Comment by StefanTT** [comment]
In 6 hours I could test if this fixes the problem, if that helps.

**Comment by RyanTheAllmighty** [comment]
Sorry for the delay. Please feel free to make a PR with the fix in and I'm happy to accept it :)

**Comment by StefanTT** [comment]
Ok I'll create a PR.

Never mind about the delay, I was too busy the last days anyways.

**Comment by RyanTheAllmighty** [comment]
Released
