### ISSUE TITLE
Java path / 64 bit

### ISSUE THREAD

**Issue by seema84** [ATLauncher/ATLauncher#271]
Java Path: C:\Program Files\Java\jre1.8.0_91\
64 Bit Java: false

Why i can't change the Java Version in Java Path?
I can change the Path but it is not used.

The Help Page https://www.atlauncher.com/help/32bit/ is ...
I need the 32 and 64 bit (JRE and JDK) Versions. The solution to remove 32 bit is very bad.
In all other Launcher i can change the Path and the switch from 32 to 64 works fine.
Whats the problem?

**Comment by RyanTheAllmighty** [comment]
All non launcher code issues should be posted on the forums at https://forums.atlauncher.com

Once posted if deemed an issue, an issue will be posted here.

**Comment by seema84** [comment]
and why i cant change the memory if i set a 64 bit path? please remove to use the system variable
