### ISSUE TITLE
Max memory allocation not saving

### ISSUE THREAD

**Issue by F4ndroid** [ATLauncher/ATLauncher#272]
Checking ATLauncher.conf I see an entry for permgen but no max memory, which leads me to believe it's not saving the global limit. Changing the setting through the Java tab in the Tools menu does nothing, as when a pack is launched or the launcher is closed it returns to the default. This behavior is present on Mac OS X 10.11.5 and Windows 8.1. I have not tested it on Linux.

**Comment by dgelessus** [comment]
Mine has `ram=4096`. Did you click the Save button to save the settings after changing?

**Comment by F4ndroid** [comment]
Save button wasn't rendering. Launcher restart fixed it.
