### ISSUE TITLE
First time run dialog always shows

### ISSUE THREAD

**Issue by 7osCraft** [ATLauncher/ATLauncher#273]
The first time run dialog to choose the language and enable or disable leader board always comes up event if it's not the first time to run the launcher this problem is only in 3.3.0.0
And I looked at the source code and found that `SettingsManager.settings.firstTimeRun` is never set to false it's always true

**Comment by dgelessus** [comment]
#277 should fix this, among other things.

**Comment by dgelessus** [comment]
OK, #277 has been merged, so this should be fixed in 3.3.0.0 (master isn't affected).
