### ISSUE TITLE
"Version To Install"-dropdown too narrow for some packs

### ISSUE THREAD

**Issue by Svish** [ATLauncher/ATLauncher#279]
The version dropdown selector thing when installing packs is too narrow for some mod packs.

Either the window needs to be resizable (and the dropdown box follow its width), or the dropdown that appears when clicking on it needs to expand its width so its content is visible (don't know if a dropdown, the box that actually "drops down" can extend outside of its window?).

![capture](https://cloud.githubusercontent.com/assets/142162/18224719/a74fc762-71df-11e6-9506-28a9a1142ece.PNG)

**Comment by flaw600** [comment]
I might take a crack at this

**Comment by RyanTheAllmighty** [comment]
Everything goes into develop now :)

**Comment by flaw600** [comment]
Will do thanks

**Comment by flaw600** [comment]
@RyanTheAllmighty I used to use my brother's account for MC but it's been awhile and I don't have access to it at the moment to test my changes, so could you do that for me? If you don't want to go into my repo I can submit a PR. Thanks!

**Comment by RyanTheAllmighty** [comment]
Make the PR anyway and I can test :)

**Comment by RyanTheAllmighty** [comment]
Alright this is all done and will be released with 3.2.3.2 within the next few days

**Comment by RyanTheAllmighty** [comment]
Released
