### ISSUE TITLE
Error when loading world after Update

### ISSUE THREAD

**Issue by Lerosen** [ATLauncher/ATLauncher#280]
[crash-2016-09-11_11.39.26-server.txt](https://github.com/ATLauncher/ATLauncher/files/465887/crash-2016-09-11_11.39.26-server.txt)
Hello,
the instance crashes a I try to open my world, I clicked on "Play selected world" then it says loading world and after some seconds it just exits and the AT Launcher window comes into foreground. I attached the crash report below

**Comment by RyanTheAllmighty** [comment]
This is not for support. Please use the forums at https://forums.atlauncher.com
