### ISSUE TITLE
Missing FORGE version 10.13.4.1558

### ISSUE THREAD

**Issue by lkettle** [ATLauncher/ATLauncher#281]
Trying to launch CrundeeCraft and get this message.  
![mc_forge](https://cloud.githubusercontent.com/assets/14791604/18794648/82ce9e4a-818e-11e6-828a-061a414c40ea.png)

I got a new school computer (it worked fine on old computer 3 days ago) so these are all the latest downloads,

**Comment by RyanTheAllmighty** [comment]
This is not support. Use the forums at https://forums.atlauncher.com or our Discord at https://atl.pw/discord
