### ISSUE TITLE
Upgrade/reinstall reselects default selections.

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#283]
For some reason, when attempting to reinstall or upgrade the Survival Industry modpack, the default selections inside "linked" lists are being reselected, even when they were unselected in the original install.  This happens even when the selection could conflict with a "group" option.

**Comment by RyanTheAllmighty** [comment]
Alright this is fixed and will be pushed out with 3.2.3.2 within the next few days

**Comment by RyanTheAllmighty** [comment]
Released

**Comment by RyanTheAllmighty** [comment]
Released
