### ISSUE TITLE
Messages issue

### ISSUE THREAD

**Issue by topher2010** [ATLauncher/ATLauncher#284]
When putting the <messages> section in the XML for the pack, it appears the xml is causing the message to appear twice, doesn't matter whether it is a fresh pack install, updating, or a reinstall of the pack.

pack: Breakfast Special
Version: 2.5b

**Comment by RyanTheAllmighty** [comment]
@topher2010 can you please provide an XML snippet so I can test this as it seems 2.5b doesn't exist anymore and latest versions don't have messages

**Comment by topher2010** [comment]
2.7f has a test message code in the xml now (i had forgotten to leave that dev version up and running, my apologies).

**Comment by topher2010** [comment]
dev-2.7f

**Comment by RyanTheAllmighty** [comment]
All fixed and will be out with 3.2.3.2 in the next couple days

**Comment by RyanTheAllmighty** [comment]
Released
