### ISSUE TITLE
[Feature Request] Ability to require Forge's <extrarguments>, but make liteloader's optional.

### ISSUE THREAD

**Issue by majix560** [ATLauncher/ATLauncher#286]
I am thinking of adding liteloader and a minimap mod using liteloader as fully optional to my pack.
But have Forge be required.
Unfortunately though, through the course of a conversation with @RyanTheAllmighty I found out that I can't set liteloader's portion of the extraarguments tag as a depends without doing the same to forge's portion.

[Pastebin of relevant Discord chat log](http://pastebin.com/tb1Jepjt).

**Comment by RyanTheAllmighty** [comment]
Closed and merging in with #223
