### ISSUE TITLE
No UI scaling for high dpi display

### ISSUE THREAD

**Issue by SplitInfinitive** [ATLauncher/ATLauncher#287]
I recently upgraded my computer to 4k gfx capability and now that I am running in high resolution, high dpi settings I have discovered that the AT Launcher window hasn't been programmed to scale up to these resolutions.

I have found a workaround that allows me to "fake" a high resolution UI scale for a second monitor but would greatly appreciate it if support for 4k in the app could be arranged.

**Comment by dgelessus** [comment]
This is a Java issue and not something that can be fixed in the launcher, as far as I know. For a fix, see this FAQ question: https://forums.atlauncher.com/announcement-5.html#windows-high-dpi

**Comment by flaw600** [comment]
@RyanTheAllmighty @dgelessus 

This is actually fixed in Java 9 (see [here](https://www.reddit.com/r/java/comments/49ip70/java_swing_is_tiny_on_hidpi_displays_what_can_be/), but Oracle/OpenJDK never issued a fix for Java 8

It seems that the relevant command is `-Dsun.java2d.dpiaware=true` but whether anyone wants to test it is up to ya'll

**Comment by ThisNekoGuy** [comment]
Using newer Java versions causes the launcher to view properly but not all menus do so.
Some forms or windows are either crippled or cut off from view.
(Such as Instance Exporting, adding Curse mods when they have dependencies, and individual instance settings menus)

I use a 4K display and running the launcher in Java 8 just makes UI elements mostly not appear at all, so it's kind of a problem.

**Comment by sybenx** [comment]
> This is a Java issue and not something that can be fixed in the launcher, as far as I know. For a fix, see this FAQ question: https://forums.atlauncher.com/announcement-5.html#windows-high-dpi

link is dead

**Comment by dgelessus** [comment]
Here you go:

> **I'm on Windows and the launcher window is really small on my high DPI display!**
> 
> This is an issue with Java not properly telling Windows that it does not support high DPI displays. To fix this, right-click on the launcher exe, go to Properties, go to the Compatibility tab and enable the checkbox "Disable display scaling on high DPI settings".

For reference, you can also find [an old copy of the FAQ via the Wayback Machine](https://web.archive.org/web/20190417185543/https://forums.atlauncher.com/announcement-5.html).

**Comment by sybenx** [comment]
ty, I'm on Linux

**Comment by dgelessus** [comment]
#449 is the current issue for DPI problems on Linux, and there are a few more workarounds posted there (if you haven't seen them already). If none of those help, please leave a comment in that issue.

**Comment by Eidelmaim** [comment]
i have the same issue as posted. as per @dgelessus suggestion i modified the settings, although they were different in Windows 11. see screen shot for settings i used to achieve better scaling of the application.

![Screenshot_3](https://user-images.githubusercontent.com/13890144/185704237-4dec4ef6-0ef6-4efd-8d36-8da953ea1b3c.png)
