### ISSUE TITLE
Launcher crashes if user has java opt less than 5 characters

### ISSUE THREAD

**Issue by seldonPlan** [ATLauncher/ATLauncher#291]
I previously had a java opt of `-d64` in my Java parameters (yes, I know it is a useless option, and has now been removed). This caused the launcher process to fail with 

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 5
    at java.lang.String.substring(Unknown Source)
    at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:176)
    at com.atlauncher.data.Instance$2.run(Instance.java:1204)
```

The issue can be traced to [this line](https://github.com/ATLauncher/ATLauncher/blob/develop/src/main/java/com/atlauncher/mclauncher/MCLauncher.java#L176). Any java option that is not long enough for the call to `arg.substring(0, 5)` will cause it to fail in the same way.

**Comment by RyanTheAllmighty** [comment]
Fixed with release 3.2.3.5
