### ISSUE TITLE
Update AuthLib

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#302]
The version of AuthLib we use currently was accurate as of about 2 years ago.

Should be looked into updating it and possibly moving them to be directly shaded into the jar when building.

**Comment by 7osCraft** [comment]
I could do that if you want but i'll work on it tommorow if you like

**Comment by 7osCraft** [comment]
Also there are some other libraries that needs to be updated like gson and guava

**Comment by RyanTheAllmighty** [comment]
I'm looking into it now.

I think I might just start distributing the libraries with the launcher. Ease of use in the future and just makes things easier

**Comment by RyanTheAllmighty** [comment]
Changes made in https://github.com/ATLauncher/ATLauncher/tree/feature/203-Update-AuthLib

Libraries are all compiled in. AuthLib must've updated as we don't need Guava or Log4J now so they're removed.

@dgelessus this should solve the class loading issue for Java 9 also correct?

This does increase the JAR size to about 6MB, but it's 2017, I'm over worrying too much about filesize. This makes things easier and less complex with no need to have to download and load jars on launch, making launch a little quicker and means no need to worry about it possibly failing causing issues.

Thoughts?

**Comment by dgelessus** [comment]
Yes, if we bundle authlib and its dependencies with the launcher directly, then no class loader hacks should be necessary, and it should work fine on Java 9.

And yeah, I think a 6 MB one-time (per update) jar download is okay, especially considering how big the modpacks are that people download with the launcher. If someone has a limited bandwidth or data allowance, then the size of the launcher won't be their main concern.

**Comment by RyanTheAllmighty** [comment]
This is done and will be released with 3.2.5.5
