### ISSUE TITLE
Automatically install Legacy Java Fixer when necessary

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#303]
People ask frustratingly often on the Discord why their 1.6 packs crash right at the start. Maybe the launcher should automatically install the Legacy Java Fixer into any new 1.6 instances. Since the fix is compatible with all Java versions, even the ones that don't trigger the crash, I'd say we install it no matter what Java the user has, in case someone has Java 7 and updates to Java 8 later.

**Comment by RyanTheAllmighty** [comment]
Are you sure it doesn't affect anything if installed when not necessary? 

If not then best to check the forge version and add it in 1.7 packs on affected forge versions also. 

Considering the number of packs running on 1.6 or low versions of 1.7, I think this should be implemented because it's a pretty good idea to prevent support issues

**Comment by dgelessus** [comment]
Yes, the fixer should be okay to install on any 1.7.10 version actually. The method which is fixed is `cpw.mods.fml.relauncher.CoreModManager.sortTweakList`, and all [changes to CoreModManager.java](https://github.com/MinecraftForge/FML/compare/cbe2ccbda461ec0ecf4d776fcd19ab31930cc3f1...1.7.10#diff-940b9eb5574b63697f8b39936ffa9201) since the fix do not change the `sortTweakList` method. This means that the patched method provided by the Legacy Java Fixer is equivalent to the one in the latest 1.7.10 FML, so it's safe to install the Legacy Java Fixer on any modpack on 1.6, 1.7.2 or 1.7.10.

In any case we should add an option in the launcher settings to turn this off though, just to be sure. And perhaps also add a link to https://github.com/LexManos/LegacyJavaFixer next to the option. (We don't have to include the full license text with the launcher as far as I can tell, because it's already included in the mod jar, but we should be nice and give credit.)

**Comment by RyanTheAllmighty** [comment]
Alright I'll redistribute the jar with the launcher (have it download on startup) then correct me if I'm wrong here @dgelessus but it should auto install in these cases:

 - Installs a pack on Minecraft 1.6 or less
 - Installs a pack on Minecraft 1.7.10 with an older version of forge

I'm not sure which version of forge on 1.7.10 is broken up until, need to go through their changelog I think to figure that out

**Comment by RyanTheAllmighty** [comment]
Actually looks like the Forge version it was fixed in was 10.13.1.1217

I think simply checking the Forge version to see if the last number is < 1217 should be an easy indicator to make it simple rather than checking mc versions. Luckily forge always keeps that number incrementing

**Comment by dgelessus** [comment]
It should be fine to install the fixer on any 1.7.10 version, because the code in Forge (for 1.7.10) hasn't changed since the fix was released, see my previous comment. But yes, an extra check for the build number would be nice, to stop it from being installed unnecessarily.

If you're going to distribute the fixer with the launcher instead of downloading it, I think we do need to include the license somewhere. I don't think we have an "About" tab with credits and such yet, maybe this would be the time to add one and list all the libraries that we're using.

**Comment by RyanTheAllmighty** [comment]
Fixed with 3.2.7.0
