### ISSUE TITLE
Add About Tab

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#304]
We should add in an about page (as mentioned by @dgelessus in #303)

This should list all the libraries we use and maybe a little snippet with contributors as well as a little blurb about ATLauncher.

**Comment by Doomsdayrs** [comment]
I'm working on this currently on my branch, I'll make a PR shortly

**Comment by Doomsdayrs** [comment]
![image](https://user-images.githubusercontent.com/38189170/163519545-fa44f085-b18a-4980-806c-6e3d80e2430a.png)

@RyanTheAllmighty How does this look to you as a rough draft of what the UI should look like?
