### ISSUE TITLE
Unused xml methods in Pack.java

### ISSUE THREAD

**Issue by 7osCraft** [ATLauncher/ATLauncher#306]
I've found some methods (idk if you know they were there) in the Pack class which are xml methods that are unused exept some like:

- getMods, used in ViewModsDialog

- hasDeleteArguments used in InstanceInstaller

- getDeletes also used in InstanceInstaller

I can completely remove them and remove old XML stuff and add the json methods like it is in 3.3.0.0 branch

Edit: also why is some classes in com.atlauncher.data.json is the same as some classes in com.atlauncher.data?

**Comment by RyanTheAllmighty** [comment]
Please feel free to PR those changes through.

As for the duplicates, I'm not entirely sure, can you tell me some which are the same?

**Comment by 7osCraft** [comment]
The duplicates are like some classes in com.atlauncher.data and com.atlauncher.data.json.
An example is ModType.class.

And If we remove them there will be no issues at all.

**Comment by 7osCraft** [comment]
Ok so can you first merge my PR #309 so I can work on this?

**Comment by RyanTheAllmighty** [comment]
Fixed with 3.2.7.0
