### ISSUE TITLE
Share code issues

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#311]
There are currently some reported issues with some share codes.

Reported share codes are selecting all mods. The codes reported are:

 - 6ANo8pGL for Resonant Rise version 3.4.0.3
 - AzpuW4Ur for Beyond Reality version 2.4.3-r1

**Comment by leagris** [comment]
* keWMH8x4 for Beyond Reality: Farscapes version 1.1.0-r1 selects everything

**Comment by gathercole3** [comment]
awJKxEtu for Resonant Rise version 3.4.0.3 selects everything

**Comment by nevercast** [comment]
gff4KQ4L Resonant Rise 3.4.0.3 also selects everything.

**Comment by RyanTheAllmighty** [comment]
Closing as share codes are fundamentally broken and have been for a while and are planned to be removed.
