### ISSUE TITLE
Ability to change/remove warning indicator next to message popups

### ISSUE THREAD

**Issue by tenten8401** [ATLauncher/ATLauncher#312]
Can we have the ability to change or remove entirely the little yellow warning indicator next to message boxes?

Like the one shown below:
![image](https://cloud.githubusercontent.com/assets/6174343/22618985/6ea2e4ec-eab8-11e6-8fe8-bfc5e13c65b1.png)

**Comment by Doomsdayrs** [comment]
Why?

**Comment by tenten8401** [comment]
Tbh it's been so long since I sent this I have no idea. I haven't played Minecraft for years

-Isaac
________________________________

**Comment by RyanTheAllmighty** [comment]
Heh yeah I'll close this one given the ATLauncher platform is winding down
