### ISSUE TITLE
XML code generator does not %encode characters in file-name part of URL

### ISSUE THREAD

**Issue by leagris** [ATLauncher/ATLauncher#313]
#### Generated code is:
```XML
<mod
  name="HelpFixer"
  version="1.4+17"
  url="packs/BeyondReality/files/1.11mods/HelpFixer-1.11-1.4+17.jar"
  file="HelpFixer-1.11-1.4+17.jar"
…
/>
```
but url fails to resolve and it raises an error
![image](https://cloud.githubusercontent.com/assets/1111474/22710460/a8e4713a-ed7d-11e6-812f-bf6e01953dae.png)
#### url should be %coded like this:
```XML
<mod
  url="packs/BeyondReality/files/1.11mods/HelpFixer-1.11-1.4%2B17.jar"
…
/>
```

**Comment by RyanTheAllmighty** [comment]
This has been fixed by the way
