### ISSUE TITLE
Java Error When Attempting Any Network Connection

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#316]
Log Upload: http://paste.atlauncher.com/view/6ea37fa1

Whenever I attempt to do anything network-wise with the ATLauncher client, errors happen.  There are various errors, but one I see the most often is this: "java.security.ProviderException: java.io.IOException: Only uncompressed point format supported".  This happens when I attempt to install a game, or when I start a game, or even after I wiped out the entire folder, downloaded the latest ATLauncher from the website, and tried to log into my account.

Since this error isn't happening for anyone else (or they're not reporting it), it might be on my end, but I'll be plaz-nabbed if I know what the hangup is.  Any ideas where I should look?

**Comment by RyanTheAllmighty** [comment]
Wow that is not something this is easily google-able.

Umm my first guess looking at the area it's in is SSL stuff. So check your certs on your system, update them from apt (google for your OS specifically as I think different distro's do their cert stores differently).

**Comment by reteo** [comment]
Looks like the problem is limited to OpenJDK; Oracle's Java (ugh) works as it should.  I guess I'll have to use it, although I hope the issue can be ironed out, though.
