### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by brat112** [ATLauncher/ATLauncher#317]
I'd love to be able to have a new background instead of greyness pls updat ATLauncher to support backgrounds

**Comment by GeoRCCraft** [comment]
brat112, you can change it to any solid color using themes. For more information you can look here: https://forums.atlauncher.com/thread-8428.html

**Comment by brat112** [comment]
umm acualy
i want ful custome

**Comment by brat112** [comment]
Like udertale genocide sans battle tith an epic image
just dont know how to

**Comment by brat112** [comment]
sorry for the inconvenience of that being useless

**Comment by brat112** [comment]
RyanTheAllmight the dleted messages dont tell me much all i wanted was fully cusomizable backgrounds Ex: the ability to have sans battle (undertale genocide) fan art as the background Better idea is thi 
![image](https://user-images.githubusercontent.com/32232494/30787275-ce1b5700-a139-11e7-9503-6c9865356d52.png)
s

**Comment by brat112** [comment]
please allow this

**Comment by RyanTheAllmighty** [comment]
@brat112 please don't spam, only need to post once.

Issue locked due to down
