### ISSUE TITLE
Add Minecraft Version filter to Packs

### ISSUE THREAD

**Issue by Svish** [ATLauncher/ATLauncher#318]
Would it be possible to add a Minecraft Version filter to the Packs "finder"? I.e. something that'd show for example only mod packs made for Minecraft version `1.10.2`.

Basically something, in the launcher, that would filter on Minecraft Version column that can be seen on the website, e.g. at https://www.atlauncher.com/packs/public.

On the website you can type in the version in the search box and it will do it, but when I do that in the launcher I get "Nothing to show". Guessing it's searching in the name and/or description only, while the website searches through all the meta data available?

**Comment by Aguinore** [comment]
@Svish Do you want to find only packs with the latest version `1.10.2` or just compatible with it? Because for example searching for version 1.7.10 can cause almost no effects if it will show any compatible modpack

**Comment by Svish** [comment]
@Aguinore Basically, my use cases are these two:

1. I've not played Minecraft for a while and I want to get back into it, and since I've been gone a while, I want to check out `Minecraft vLatest` . Vanilla Minecraft is boring though, so, what modpacks are available to me for this `Minecraft vLatest`?

2. If I find no interesting mod packs for `Minecraft vLatest`... how about for `Minecraft vPrevious`?

That way I could start with the latest version, check what's available for it, and if nothing is interesting, nudge the version down a step, look again, and repeat until I find something interesting.

Not quite sure what you mean by the `1.7.10` issue, but yeah, I assume the lower version you'd enter, the less useful the filtering would be as eventually you'd get almost every modpack... although there are modpacks which has started later too I think, which would then not be shown... Either way, I think that should be up to the user? If they want to play `1.7.10`, they should get that long list of every compatible modpack and be able to install that version of minecraft, with the newest version of the modpack compatible with that version of minecraft... if that makes sense... and then, that list being long, one should be able to filter it further down with the regular search.

Hope this makes sense... and sorry for the late reply, I've been on vacation for a while. 😛

**Comment by GeoRCCraft** [comment]
You can go to https://www.atlauncher.com/packs/public and search for the version in the search bar.

**Comment by RyanTheAllmighty** [comment]
Closing this as the search box on the website does filtering by Minecraft version.
