### ISSUE TITLE
Compatibility issue with customstuff 2

### ISSUE THREAD

**Issue by wormzjl** [ATLauncher/ATLauncher#322]
I've used CS2 to add items and fluids to my pack and I've encountered issues while testing on ATL.

Wherever I tries to add a mod, it shows that there is a non-existing duplicate of my mod:
![image](https://user-images.githubusercontent.com/2989009/33047678-48d2cb5a-ce57-11e7-92f1-5a54ef00f8a1.png)
Where PerFabricaadAstra is the base folder name
![image](https://user-images.githubusercontent.com/2989009/33047756-b76934fa-ce57-11e7-95d4-efab39672d20.png)

This does not happen on normal launchers (vanilla, multimc, etc.)

Download and information of this mod can be found here:
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1275500-cubex2s-mods-all-mods-available-for-1-8-9

**Comment by wormzjl** [comment]
To replicate: 
Drop customstuff 2 jar and rhino js.jar into the mods folder
Inside the mods folder create a folder called CS2_blablabla
Lauch the game and let CS2 generated the necessary files, close the game
Restart the game, now you get the dupe

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

If this is still an issue, please re raise the issue with logs so it can be investigated on current version.
