### ISSUE TITLE
ATLauncher Network test fails. 

### ISSUE THREAD

**Issue by iceman11a** [ATLauncher/ATLauncher#325]
I never used this before, My friend has been trying it and I tried it. and it seems to stop working when it reaches 40/50. I thought I should let someone know about this issue. I'm all so discord in the ATLauncher channels. You can reach me there. I have one more issue to report. 

Iceman11a

**Comment by RyanTheAllmighty** [comment]
Can you provide the console logs please.

**Comment by iceman11a** [comment]
[ATLauncher-Log_2018-01-23_16-22-58.log](https://github.com/ATLauncher/ATLauncher/files/1657996/ATLauncher-Log_2018-01-23_16-22-58.log)

This is the only log I know of. I didn't see anything in the logs folder that was just for the console

**Comment by RyanTheAllmighty** [comment]
Run the network test, once it errors then click the 'Upload Log' button on the console

**Comment by iceman11a** [comment]
here's the link for that log. The error I saw was \ by 0, http://paste.atlauncher.com/view/5baaea4c and to show you between 10 minutes. That the network tester locked up or froze. 
![screenshot_1](https://user-images.githubusercontent.com/8973574/35324577-20ed7104-00bf-11e8-8b86-4d9ecd402a64.png)
![screenshot_3](https://user-images.githubusercontent.com/8973574/35324579-21caa68c-00bf-11e8-8e29-fdbabe63a2db.png)

**Comment by iceman11a** [comment]
If you look at the screen shots you will see that the screen shots were taken more the 10 minutes apart.

**Comment by RyanTheAllmighty** [comment]
Yeah I think I know what the issue is. I'll take a look this weekend

**Comment by RyanTheAllmighty** [comment]
Fixed for release 3.2.5.5
