### ISSUE TITLE
ATLanucher's Menu become disorder or all mess up. 

### ISSUE THREAD

**Issue by iceman11a** [ATLauncher/ATLauncher#326]
When I try and use the add mods menu. This seems to start the graphics issues with the menu. I just updated my graphics drivers like 3 or 4 days ago. So I don't think that could be the issue. I do that the ATLaunchers memory up high because of all the mods I use. I never had any problems running the software. I did post screen shots and so on in the support channel on discord. 

Iceman11a

**Comment by iceman11a** [comment]
I'm having the same issue when I try and Install a new Instance of Minecraft 1.10.2. (this doesn't include modpacks). Try and install a new Instance of Vanilla Minecraft and see if it asks you to install forge all so. Mine doesn't do that. I downloaded another copy of the launcher and that doesn't seem to work. When I install a new Instance of Vanilla Minecraft it's all ways ask me if I want to install forge and some basic mods. Like journeymap and a few others. I just seem to get this to work any more. Has anyone come up with any idea.

**Comment by jamierocks** [comment]
It would be helpful, if you could add those screenshots to this issue.

**Comment by iceman11a** [comment]
The screen shots I took are on discord. Look in the support channel and the help channels. Just scroll up until you see my name. Try it for your self and see if you get the same results.

**Comment by iceman11a** [comment]
https://cdn.discordapp.com/attachments/193304339941556225/404594713254035456/unknown.png

**Comment by iceman11a** [comment]
that should give you an idea of what happens in ATLauncher.

**Comment by RyanTheAllmighty** [comment]
There's probably just some extreme edge case between ATLauncher, your version of Java and your graphics card.

Did it work fine before you updated your graphics card drivers 3-4 days ago?

**Comment by iceman11a** [comment]
well no, it's been doing the for a long time now. I have friends that have this same issue. I don't know if any one else is having this issue since no one replied on discord.

**Comment by jamierocks** [comment]
It would be nice to know more about your environment so someone can try replicate this.

**Comment by iceman11a** [comment]
well what did you want to know. My PC is a AMD Fx 8350 8 core. I have 16gbs or ram with a AMD R9 270 Video card with 2 gbs on board. The drivers for the card are updated offen. See I have had this issue for a long time and never bothered to report it. Thinking that you all ready knew about it and would release a fix. Just earlier last year wel still had the same issue. So that when my friends and I were using the ATL more, and had all kinds of issues with the ATL. That's when I thought I would post this issue. I have issues with the ATL and Forge and newer versions of Minecraft that I have to post on that all so. when I can take the time out from other projects. Let me know what you need.

**Comment by RyanTheAllmighty** [comment]
Closing this as it seems to be an edge case which cannot be replicated so will be next to impossible to fix. Only recommendation to people coming into this issue is to use the recommended setup installer from https://atlauncher.com/downloads
