### ISSUE TITLE
forge wont install in any version 1.8 and up

### ISSUE THREAD

**Issue by nythawkman** [ATLauncher/ATLauncher#327]
tried to installed forge but no versions above 1.7.10  has forge or optic fine either can u guys please fix

**Comment by jamierocks** [comment]
Just to clear any confusion, which of the following is the case?

1. There is no option to install 'Minecraft Forge' or 'Optifine' for any version greater than 1.7.10
2. 'Minecraft Forge' or 'Optifine' fails to install for any version greater than 1.7.10
3. Something else entirely

(*I ask as your issue title conflicts with the issue subject*)

**Comment by nythawkman** [comment]
number 1

**Comment by jamierocks** [comment]
Then this is not an issue with the launcher, but likely a decision of Ryan's not to add optional mods to Vanilla Minecraft anymore.

Maintaining the recommended versions to use would be a right pain for Ryan to do, when installing mods isn't exactly difficult (its an eternity easier than jarmodding was) - so I'd guess that that's likely why.

**Comment by nythawkman** [comment]
Well cause I have a pack that me and 5 buddies play with cause my computer
can't handle some of the atlauncher packs and the pack that we use has like
45 mods and most of the packs has like 5 or 6 of the mods we use and
doesn't allow for us to remove the ones we don't want to use cause most of
them are required mod such a shame that those options aren't there cause
the atlauncher is one of the best launcher out there

**Comment by nythawkman** [comment]
because the option is on 1.7.10 but most of the mods for 1.7.10 stop
offering support cause they moved on to later versions

**Comment by GeoRCCraft** [comment]
If you are trying to run your own mod pack it is recommended that you run it though a program like MultiMC. The ATLauncher wasn't really built for building modpacks. Here is a link to MultiMC: https://multimc.org/

**Comment by RyanTheAllmighty** [comment]
Yeah ATLauncher doesn't have 'pick your own forge' version selectors.

It's completely manual and not something we do often.

Your best bet is to use MultiMC as it has easy forge version installation.
