### ISSUE TITLE
Reinstallation Conflicts

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#331]
### Description

Assume you have a setup where two items are in a single group (for the sake of unselecting one in favor of the other).  Now, assume someone installed a modpack and chose the non-default option in a group (the one that did not have "recommended" and "selected" set to "yes").

A bit of time passes, and now the modpack updates to a new version.  When the player goes to upgrade the pack, it doesn't work right.  They go back and find out some of their options were disabled.  What happened was that the default options overrode the changes the player made in their original installation during the update.

### Steps to Reproduce

1. Choose the desired modpack in the "Packs" tab
2. Select and install the non-default "group" option (which will automatically deselect the default one).
3. Finish installation.
4. In the "Instances" tab, select "Reinstall" or "Update"
5. Look at the list of optional mods.

**Expected behavior:** All the mods you selected during the initial installation should remain selected during the reinstallation/update.

**Actual behavior:** All the mods you selected during the initial installation will remain selected during the reinstallation/update, except for those grouped options where you selected the non-default option.  In this case, the installer will re-select the default option.

### Additional Information

The current issue is associated with the next release of "Survival Industry" (called "carniverous_coconut").  The grouped items in question are "MAtmos" and "Skyblock Game"; if a player selects "Skyblock Game," and then goes to reinstall or update it later, the installer forces MAtmos to be re-enabled, which disables "Skyblock Game."  If you need to be added on the list for testing players (this version is not yet released), please let me know.

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

Many packs don't go into this level of detail of optional mods anymore.
