### ISSUE TITLE
Add fake 'Create Account' page in launcher

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#344]
One of the biggest things I see in the Discord is people asking where to create an account.

Adding a button or something for 'Create Account' and then explain it's a Mojang login, and that they must have a valid Minecraft paid account, would be good.

Might be good to have some wording on the Login page also to explain this

**Comment by GeoRCCraft** [comment]
Perhaps add something about how the ATLauncher does not work with cracked accounts as well?

**Comment by RyanTheAllmighty** [comment]
Released with 3.2.6.0
