### ISSUE TITLE
New version of authlib requires Java 8

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#346]
The last update to authlib now requires minimum Java version of Java 8.

This has caused a few support messages around this.

Two options:

- Force the use of Java 8 and warn users not using Java 8
- Revert the package back to the older version

**Comment by RyanTheAllmighty** [comment]
Fixed with 3.2.7.0

**Comment by jamierocks** [comment]
Are there statistics for how many people use ATLauncher with SE 7?

Given Minecraft targets SE 8 now, would make sense for ATL to follow suit.

**Comment by RyanTheAllmighty** [comment]
Unfortunately no. I'll update the user agent to include the java version so I can see what's being used
