### ISSUE TITLE
Switch to java-mojang-api for making calls to Mojang api

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#347]
https://github.com/SparklingComet/java-mojang-api/blob/master/README.md

**Comment by RyanTheAllmighty** [comment]
This library requires Java 8 so we need to update to Java 8 first

**Comment by jamierocks** [comment]
I wouldn't bother with that library, it looks to overlap with authlib in part and the rest is so trivial seems overkill to use a library for.

**Comment by RyanTheAllmighty** [comment]
As a JavaScript developer in the npm ecosystem, I'm not sure what the word overkill means :)

Remember left pad? Haha

Yeah I implemented this library and realised it was java 8 after I was done. We only use it for like 2 things and the library used Apache http which bloated the shadow jar by 1mb, so yeah you're right
