### ISSUE TITLE
Warning not getting triggered when mod depends

### ISSUE THREAD

**Issue by SirOMGitsYOU** [ATLauncher/ATLauncher#353]
When adding a warning to one mod then requiring others to depend on it, it doesn't trigger the warning, I have a warning for the chaos line of mods to advise its not compatible with the main server, this didn't work how I was intending to and actually looked like I may have run into a bug or an un-thought of feature

Here's a look at the issue in action
https://i.imgur.com/rmaaXUI.gifv

**Comment by Doomsdayrs** [comment]
Is this still an issue?
