### ISSUE TITLE
Vanilla with Forge not able to install on linux

### ISSUE THREAD

**Issue by DallasEpperson** [ATLauncher/ATLauncher#356]
**Describe the bug**
When attempting to install a new instance of Vanilla with Forge, the application fails with 
```
Failed to process argument with value of **USERSDIR**/libraries/de/oceanlabs/mcp/mcp_config/1.14.3-20190624.152911/mcp_config-1.14.3-20190624.152911-mappings.txt as the local file **USERSDIR**/Temp/VanillaMinecraftwithForge_1143/loader**USERSDIR**/libraries/de/oceanlabs/mcp/mcp_config/1.14.3-20190624.152911/mcp_config-1.14.3-20190624.152911-mappings.txt doesn't exist
```

**To Reproduce**

1. Open ATLauncher
2. Click the `Vanilla Packs` tab
3. Click the `New Instance` button for "Vanilla Minecraft with Forge"

**Expected behavior**
The pack should install and appear in the "Instances" tab

**Desktop (please complete the following information, or remove if not applicable):**

- OS: Fedora 29, Linux kernel 5.1.6-200.fc29.x86_64
- ATLauncher Version: 3.2.9.2

**Comment by RyanTheAllmighty** [comment]
Released with update 3.2.9.6
