### ISSUE TITLE
AT Launcher stopped working in Linux because jar is not in its own directory

### ISSUE THREAD

**Issue by aggro80** [ATLauncher/ATLauncher#362]
I added comment here explaining what change I suspect to have caused the error:

https://github.com/ATLauncher/ATLauncher/commit/cfa8e0d3caa7cc7f46ee6edc025df029583eb4b0#diff-24f206115c4b803ce3a38c55a6b8a2f5R46

As I fixed this already on my machine by renaming directories, I can't test possible fix nor is this a problem for me any more. I just wanted to give you heads up in case you want to fix this before bug reports start coming in.

Feel free to close or do what ever you want with this issue, it is unlikely that I will report back to this.

**Comment by RyanTheAllmighty** [comment]
Will be fixed with 3.3.0.1 of the launcher

**Comment by RyanTheAllmighty** [comment]
Released with version 3.3.0.1
