### ISSUE TITLE
Full-screen decoration-less windowed mode not working since 3.3.x.x

### ISSUE THREAD

**Issue by leagris** [ATLauncher/ATLauncher#365]
**Start Minecraft Maximised not working anymore**
![Start Minecraft Maiximised](https://cdn.discordapp.com/attachments/193304339941556225/604795674437091350/unknown.png)

**To Reproduce**

1. Upgrade Bobs3r's to 3.7.1 or DNSTechPAck to 12.2.2 (works as intended with older non-upgraded versions of these packs.
2. Click on Start
3. See a tall window not taking all screen width, with decorations and borders, instead of a full-screen decoration-less window

**Expected behavior**
full-screen decoration-less window

**Screenshots**
![image](https://user-images.githubusercontent.com/1111474/62000677-69c09300-b0dd-11e9-8f61-bb5fc8a9c1be.png)

**Desktop (please complete the following information, or remove if not applicable):**

- OS: Linux Ubuntu 19.04
- Browser: Firefox
- Version: 68.0.1 64-bit Linux

**Additional context**
Desktop environment: Gnome Flash-Back
Window decorator: Emerald
Window manager: Compiz

**Comment by RyanTheAllmighty** [comment]
Can confirm this also happens on Windows, so is not OS specific

**Comment by RyanTheAllmighty** [comment]
We're launching Minecraft with the correct arguments (`--width=1920, --height=1080`)

**Comment by RyanTheAllmighty** [comment]
Using version 3.2.9.7 of the launcher I don't see the issue pop up, so something is different between the two versions of the launcher that broke this.

**Comment by leagris** [comment]
With the same 3.3.0.2 Version of the Launcher, I could start Bobs3r's pack that was on version to 3.7.0. It ran with the full-screen window as expected.
Then I upgraded it to 3.7.1 as the launcher proposed.
And then it showed the same issue.
I'd say there is a trigger of the issue when upgrading a pack.

**Comment by RyanTheAllmighty** [comment]
Okay I've found the issue. Seems we're launching with `--tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --versionType, Forge` twice which causes the issue for some strange reason.

I'll fix it so it doesn't duplicate arguments

**Comment by RyanTheAllmighty** [comment]
Released with version 3.3.0.3

**Comment by leagris** [comment]
awesome thank you :bowing_woman:
