### ISSUE TITLE
Doesn't work with AdoptOpenJDK?

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#368]
Question came up on Discord:

> Not exactly sure where I should report this, so I'm just going to report it here because it is launcher related:
> ATLauncher.exe whines about java not being installed when you have AdoptOpenJDK.
> ATLauncher.jar seems to work fine tho. (Both on Windows)

**Comment by dgelessus** [comment]
I remember having a similar issue with another Java-based application with an exe launcher (Logisim). I was able to fix it by rerunning the AdoptOpenJDK installer and enabling an option called "register Oracle JDK paths" or something like that. I assume these exe launchers search for Java using some mechanism specific to Oracle JDK, which won't work with AdoptOpenJDK by default.

**Comment by RyanTheAllmighty** [comment]
I would think they would look in the registry to find the java versions. I personally use Corretto JDK by amazon and don't have any issues, I'm guessing Adopt does something a wee bit differently

**Comment by RyanTheAllmighty** [comment]
Closing as known workaround
