### ISSUE TITLE
Curseforge packs downloads resourcepacks into wrong folder

### ISSUE THREAD

**Issue by GameBurrow** [ATLauncher/ATLauncher#378]
**Describe the bug**
When installing CurseForge modpack instance, resource packs included in the modpack are downloaded into mods folder.

**To Reproduce**

1. Install Curseforge pack from link https://www.curseforge.com/minecraft/modpacks/the-society-transportcraft
2. Start the instance
3. Check the resourepacks folder in the instance and you'll see it's empty but you will find all the resourcepacks in the mods folder (notice .zip archives being there)

**Expected behavior**
Resourecpacks should be downloaded into resourcepacks folder

**Screenshots**
![image](https://user-images.githubusercontent.com/4341091/68749188-7a523600-0606-11ea-96f7-fe0283312160.png)
![image](https://user-images.githubusercontent.com/4341091/68749228-89d17f00-0606-11ea-90d3-5b8a0fd1585c.png)

**Desktop (please complete the following information, or remove if not applicable):**

- OS: Windows 10 x64 Professional 18362.476

**Comment by RyanTheAllmighty** [comment]
This has been fixed with version 3.3.4.3

Sorry for the lack of communication, this issue seemed to have missed me somehow
