### ISSUE TITLE
Skin preview displays wrongly on accounts page for 1.8+ skins

### ISSUE THREAD

**Issue by lenaclariel** [ATLauncher/ATLauncher#379]
**Describe the bug**
The skin shown on the accounts tab when using a 1.8+ skin does not display properly, displaying similarly to when a 1.8+ skin is used in Minecraft 1.7.10 i.e. with both arms and both legs the same.

**To Reproduce**

1. Upload an asymmetric 1.8+ version skin (i.e. one with different content for left and right arms, or left and right legs) to an account.
2. Log in to account in ATLauncher and switch to it.
3. Go to accounts tab.

**Expected behavior**
Skin preview displays properly, with different arms and different legs based on the skin.

**Screenshots**
![Screenshot from 2019-12-09 15-01-54](https://user-images.githubusercontent.com/51832843/70468690-87dbce00-1a95-11ea-8557-a6db7d168f65.png)

**Desktop:**

- OS: Ubuntu 18.04.3 LTS
- Version: ATLauncher 3.3.1.4

**Additional context**
The issue is with the skin preview construction in com.atlauncher.data.Account.getMinecraftSkin(), I believe.

**Comment by RyanTheAllmighty** [comment]
Will be released with version 3.3.5.3 of the launcher likely on the 2nd of July due to some caching issues the launcher had.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.0.0
