### ISSUE TITLE
When right-clicking on an instance image, the create share code option doesn't show up

### ISSUE THREAD

**Issue by sora-jp** [ATLauncher/ATLauncher#384]
Title describes the bug, as far as I can see there is no way to create a share code currently.

**Comment by RyanTheAllmighty** [comment]
Will be released with version 3.3.5.3 of the launcher likely on the 2nd of July due to some caching issues the launcher had.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.0.0
