### ISSUE TITLE
Cannot paste password when adding account

### ISSUE THREAD

**Issue by cfstiff** [ATLauncher/ATLauncher#387]
**Is your feature request related to a problem? Please describe.**
When adding an account to ATLauncher, it prohibits pasting in the password field. I use a password manager, which is something that people should be doing! However, being unable to paste discourages people from using password managers, and can encourage people to take unsafe steps (like using 'remember password' on a shared computer or making their password more simple) 

**Describe the solution you'd like**
Please allow pasting into this field

**Describe alternatives you've considered**
Don't think there really is one here?

**Additional context**
Running on Mac

**Comment by dgelessus** [comment]
The issue seems to be that on Mac the password field doesn't understand the Cmd+V shortcut for pasting. Ctrl+V works for me on Mac though (which is what you'd also use on non-Mac systems). Strangely, this only affects the password field - all other text fields in the launcher support Cmd+V correctly on Mac (in addition to Ctrl+V).

**Comment by cfstiff** [comment]
Oh that's so wild! Yeah I eventually got around it by pasting into the username field and thats why i thought it was a choice to make password only non pastable

**Comment by RyanTheAllmighty** [comment]
Yeah this has been an issue for a long time. I noticed it way back when I used to run a Mac like 5 years ago.

We currently do register custom actions for OSX to enable command pasting, but maybe that never worked

Code: https://github.com/ATLauncher/ATLauncher/blob/ce7a3280c58953169a8f865c02f638ccd74a33d4/src/main/java/com/atlauncher/App.java#L508-L513

Commit that added it: https://github.com/ATLauncher/ATLauncher/commit/2526c86620545be91b67903df0171b6c07cba920

Maybe it never worked?

@cfstiff can you do me a favour and try this download and see if it allows you to paste with Command key. I don't have a Mac anymore and setting up a VM is a good days work with OSX unfortunately:

[ATLauncher-3.3.5.1.zip](https://github.com/ATLauncher/ATLauncher/files/4739396/ATLauncher-3.3.5.1.zip)

**Comment by RyanTheAllmighty** [comment]
Ignore the above file. I've setup a VM and managed to track the issue down.

I've verified using OSX Catalina that Cmd shortcuts are working in the password field now.

I'll release this tonight with the next launcher update.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.3.5.2 of the launcher
