### ISSUE TITLE
Add browser for installing non ATLauncher packs

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#394]
Currently you need a CurseForge zip or link to install a pack.

Adding in some UI for browsing modpacks from CurseForge and with #392 from modpacks.ch

**Comment by jamierocks** [comment]
Might be worth looking at how MultiMC handles this, will grab a screenshot next I'm at a pc.

**Comment by jamierocks** [comment]
MultiMC handles this (for CurseForge) with a search interface.

![https://i.imgur.com/DWfMxDn.png](https://i.imgur.com/DWfMxDn.png)

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
