### ISSUE TITLE
Extremely High CPU usage on instance creation and constantly failing downloads

### ISSUE THREAD

**Issue by hypherionmc** [ATLauncher/ATLauncher#402]
**Describe the bug**
I just downloaded AT Launcher for the first time ever and tried to install a modpack. The downloading of mods failed about 15 times already, each time a different mod, but the error being the same. Also while downloading, AT is using 85-100% of my CPU just to download.

**To Reproduce**

1. Install a fresh copy of AT Launcher
2. Create a new instance from a modpack
3. Keep an eye on the CPU usage

**Expected behavior**
For mods to download without issue and for my PC still to usable while this is happening

**Logs**
https://hastebin.com/hasaboxumi.cpp

**Screenshots**
![image](https://user-images.githubusercontent.com/63595580/90061895-14a2ef80-dce7-11ea-8076-25007a09ba45.png)

**Desktop (please complete the following information, or remove if not applicable):**

- OS: Windows 10 64-bit
- Java: 1.8.0_181 (64-bit)
- AT Version: 3.3.5.2

System specs if helpful:

CPU: Intel Core i3 3.3GHZ
Ram: 8GB
GPU: Gigabyte GV-N950XTREME-2GD

**Comment by RyanTheAllmighty** [comment]
Failed downloads are not something we can fix, this is on your end, some antivirus or firewall on your computer or network/router, even possibly on your ISP's side. You can try changing the concurrent connections in the launchers network tab down to a low number like 4, maybe even 2 or 1 and save it and try again, it might solve the issue.

As for the high CPU usage, likely related to the download failing as it's attempting multiple times to get each file, each has http connections, gzip compression and hash checking, all of which takes cpu time, all while multithreading 8 downloads at the same time.
