### ISSUE TITLE
Updated Discord Integration

### ISSUE THREAD

**Issue by BenjaMenja** [ATLauncher/ATLauncher#403]
**Is your feature request related to a problem? Please describe.**
Feature is not related to a problem.

**Describe the solution you'd like**
I would like the discord integration setting in ATLauncher to be compatible with modpacks that arent normally found on the launcher. For example, packs added from curse.

**Describe alternatives you've considered**
None, it already works fine, just thought this would be a good addition.

**Additional context**
None

**Comment by RyanTheAllmighty** [comment]
This will go out with update 3.4.0.0 sometime in the future. No real ETA at the moment as there's some outstanding issues to fix first

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.0.0
