### ISSUE TITLE
Developer Packs - Developer Packs section

### ISSUE THREAD

**Issue by SirOMGitsYOU** [ATLauncher/ATLauncher#406]
**Is your feature request related to a problem? Please describe.**
As a Developer on ATLauncher myself, I have a few different packs present on there and it would be nice to have them all in one place. 

**Describe the solution you'd like**
Enter the "Developer Packs" section only visible to pack creators or pack testers. This would help alleviate the need to bog down the players/developers Instances tab with test packs and preparing for updates. 

This would also be handy as well if the developer packs section would install to a separate folder as this would mean that they don't get mixed up with the normal instances.

Another thing that also would be interesting to see that's the same sort of request would be the option to disable/enable certain tabs on the launcher i.e I don't want to see vanilla packs or the tools tab so I want to turn those off, for now, this would be a nice option in the settings to just untick and launcher restart and those tabs are no longer visible. 

**Describe alternatives you've considered**
I've tried using Twitch & GDLauncher for updates and test packs, However - usually in my case the twitch packs have separate visual mods as well as changes to the menu&loading screens due to twitch's obsession with a stupid load resolution so images have to be changed, due to this it ends up getting mixed up with the ones for ATLauncher.

I've also tried just bundling them in with my normal playing instances which has caused a few issues as I eventually mounted up to 10-20 instances and have just given up with playing and reverted to just using them for updates. 

**Additional context**
Example of developer packs in play;
![developerpacks](https://user-images.githubusercontent.com/20475516/97804865-6e61e880-1c4a-11eb-9ad9-0ea455aa1902.png)

Example of that tab hiding - Would be eligible for all tabs apart from News, Instances & Settings. 
![exampletabs](https://user-images.githubusercontent.com/20475516/97805006-5474d580-1c4b-11eb-8187-b5350b4304b5.png)

**Comment by Doomsdayrs** [comment]
@RyanTheAllmighty You [said](https://github.com/ATLauncher/ATLauncher/issues/312#issuecomment-2267525258) the ATLauncher platform was winding down, closing.
