### ISSUE TITLE
Launching servers is not using the java version specified in settings

### ISSUE THREAD

**Issue by CarlAndersson** [ATLauncher/ATLauncher#408]
**Describe the bug**
When launching servers from the servers tab, they will use the default system java version instead of the one specified in settings. 

**To Reproduce**

1. Install a sever from the packs tab.
2. Manually specify the java path in the settings/java pane.
3. Have java 9 as the system java version.
4. Launch the server, which only runs the launch command in a terminal, which will then use the system default java.

**Expected behavior**
Servers should launch with the specified java version in settings.

**Desktop (please complete the following information, or remove if not applicable):**

- OS: macOS 10.15.7
- ATLauncher: 3.4.0.1

**Comment by RyanTheAllmighty** [comment]
This is the expected behaviour. The server scripts will use the system default not the one set in the launcher. If you wish to change it, you can modify the LaunchServer scripts
