### ISSUE TITLE
Ability to check for all mod updates at once without unchecking non-CurseForge mods

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#409]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have to select all mods then uncheck the ones that aren't from CurseForge before I can press Check for Updates

**Describe the solution you'd like**
I'd like Check for Updates to be clickable when at least one mod in the selection is from CurseForge, and for updates to be checked for the mods in the selection that are on CurseForge

**Describe alternatives you've considered**
A separate "Update all CurseForge mods" button would also work, but I feel like that's extra clutter when select all and Check for Updates exist. However, I can see a potential advantage to that, I imagine it would be easier to skip the popups for mods that don't have updates available without impacting existing functionality that way.

**Comment by RyanTheAllmighty** [comment]
Definitely need to skip mods without updates when doing it in this batching mode.

It's not ideal, was hacked in to begin with, so could do with some refinement for sure

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.1.0
