### ISSUE TITLE
Add ability to disable "Move out of Program Files" warning

### ISSUE THREAD

**Issue by Jack-McKalling** [ATLauncher/ATLauncher#410]
**Is your feature request related to a problem? Please describe.**
Everytime I launch the launcher, I'm warned "We have detected that you're running ATLauncher from within Program Files". I'm aware of this, I don't need to be notified about this every time, because I _want_ to have all my software installed in there.

**Describe the solution you'd like**
I would like to have the option to "remember this choice" for this dialogue, so that I'm not bothered about a warning that (apparently) does not have any meaning for me.

**Describe alternatives you've considered**
Alternatively there could be a checkbox in the Settings tab, where you can disable the check completely (having the same result as clicking the No button here).

**Additional context**
On the discord I was told it might be related to Window's UAC system, but I'm not using it. So the warning is completely moot to me and this warning effectively takes the place of the UAC's annoying messages, literally not solving anything.
![ATLauncher Program Files warning](https://user-images.githubusercontent.com/14236702/98725975-23587b80-2396-11eb-9b4a-6f81ac7ed77c.png)

**Comment by Jack-McKalling** [comment]
Thanks. It sure would help. I've been running from Program Files for months, and until this warning nothing seemed to have been causing issues by doing so.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.1.0
