### ISSUE TITLE
Reinstall switches folders if the instance has been renamed, resulting in a new instance

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#411]
**Describe the bug**
When using Reinstall after renaming an instance, the reinstalled instance is in a different folder.

**To Reproduce**

1. Create an instance
2. Go to the instances tab and rename that instance
3. Reinstall that instance
4. The new instance will be in a different folder than the original instance.

**Expected behavior**
I expected the instance to be in the same folder.

**Desktop:**
- OS: MX Linux
- ATLauncher Version 3.4.0.2

**Additional context**
A few side effects this has that may be worth noting:
If save mods was checked on the reinstall dialog, they are not copied to the new folder.
This results in two instances with the same name, which isn't normally possible in the launcher. The old instance only shows up again once you restart the launcher.
The launcher shows the old mod list when you go to edit mods on the new instance. None of the mods are actually present on it.

**Comment by RyanTheAllmighty** [comment]
Providing some debug logs will help out (https://atlauncher.com/help/debug-mode) provide the logs after the issue happens using the Upload Log button on the launchers console then providing the link here

**Comment by The-Fireplace** [comment]
https://paste.atlauncher.com/view/82f1cab7

**Comment by The-Fireplace** [comment]
Here, I made a quick video demonstrating the issue too
https://youtu.be/qioM8Gco9iU

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.1.0
