### ISSUE TITLE
Show mod icon/image on mod browser 

### ISSUE THREAD

**Issue by homemmakako** [ATLauncher/ATLauncher#414]
It would be nice to render the mod icon/image on the mod browser. Not only it makes it easier to find what you are looking for but the images also tell a lot about the mod (such as mod theme or quality).

The problem here would be how capable is the curseforge API of doing so; never looked into it but should (hopefully) be possible?

The image could be rendered before the text (mod description) or else I imagine a UI rework would be required.

**Comment by RyanTheAllmighty** [comment]
The mod browser currently is a mess. Java UI I just can never make pretty.

The api provides the images, but rendering them in Java ui might be difficult and finding a spot for them may make it difficult.

But would be a good improvement

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.3.0
