### ISSUE TITLE
Add support for new Microsoft accounts

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#415]
New purchases of Minecraft now require a Microsoft account. Migrations will start early 2021 for existing accounts.

These users cannot use ATLauncher along with some other third party tools.

We'll need to add support for these.

Details in MultiMC/MultiMC5#3475 from reverse engineering by the person who did it.

High level details of what needs to be done and what is done:

- [x] `Account` needs to be made generic allowing both a Mojang and a Microsoft account
- [x] Button in `AccountsTab` to open up a dialog to `Login with Microsoft`
- [x] Figure out bundling JavaFX web to open the auth flow as per https://wiki.vg/Microsoft_Authentication_Scheme and make sure that it works still on different Java versions on different OS once bundled
- [x] Potentially look at using a custom Oauth application on Azure as per https://github.com/ATLauncher/ATLauncher/issues/415#issuecomment-741497001
- [x] Existing Mojang accounts are converted from `Account` to `MojangAccount` correctly without loss
- [x] Allow removing Microsoft accounts
- [x] Error flow for when Microsoft account has no purchase
- [x] What happens when accessToken expires? How do we refresh it before launching Minecraft?
- [x] Release update

Once the migration side of things has started with Microsoft, then we can add in the flow for converting accounts, but for this it's not required

**Comment by RyanTheAllmighty** [comment]
From brief chat in #development channel on Discord with @jamierocks here's some initial observations:

Seems like a simple oauth flow, but you need to intercept the redirects to grab the token. It's a generic "Minecraft Launcher" oauth client. May be support for third party specific ones later on??

We'd need to add in some way to do JavaFX bundling (if possible) as we'd need to show a complex web view to allow the user to login and us to intercept the oauth token, the same as the vanilla launcher does.

JavaFX stuff may be the complex part of this, as it's not included in Java 11 and onwards, and before then I think it was only bundled with JDK, but I'm honestly not sure, anytime I've looked at it in the past it was a mess.

AFAIK there's no way around needing JavaFX, as we need that webview since we can't use a custom redirect url to do something with say protocol handlers.

**Comment by rbrick** [comment]
I had been reverse-engineering this myself, and you can actually use your own Azure application, meaning you can have a custom redirect URL

https://gist.github.com/rbrick/be8ed86864fc5d77aa6c979053cfc892#file-msa-go-L20

**Comment by RyanTheAllmighty** [comment]
@rbrick nice.

I'll have to give that a try, might make it easier

**Comment by phit** [comment]
that should remove the need for JavaFX, open login page in the users browser and have the redirect to a localhost port that has a small webservice to get the reply, no reason to bundle that huge webview component

**Comment by RyanTheAllmighty** [comment]
Yeah depending on the direction and guidance that Microsoft comes out with on how third parties should connect, will switch to custom azure application.

Running a local server as part of the launcher though may bring on some issues with virus scanning software, they tend to trigger on that sort of thing, but as long as it's only started when the login flow is started, it might be okay.

**Comment by RyanTheAllmighty** [comment]
Majority of work is done. All seems to be well. 🤞 I'll get a release out for this within the next couple of days. I expect there to be some issues, but hopefully minimal and should only affect those using Microsoft accounts.

**Comment by RyanTheAllmighty** [comment]
Support is done and tested as best as I can. Awaiting release now

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.1.0

**Comment by phase** [comment]
Hello! Can you tell me what you did on the Azure end to make the OAuth not require a client secret? I noticed you're not sending one: https://github.com/ATLauncher/ATLauncher/blob/119083a7016869b37669378eb19007f0fc05b346/src/main/java/com/atlauncher/data/Constants.java#L92-L95

**Comment by RyanTheAllmighty** [comment]
> Hello! Can you tell me what you did on the Azure end to make the OAuth not require a client secret? I noticed you're not sending one:
> 
> https://github.com/ATLauncher/ATLauncher/blob/119083a7016869b37669378eb19007f0fc05b346/src/main/java/com/atlauncher/data/Constants.java#L92-L95

I followed https://wiki.vg/Microsoft_Authentication_Scheme and ignored anything to do with client secret. It's not required for this flow

**Comment by rbrick** [comment]
That's my bad 😅 I had wrote that part not knowing about the Mobile/Desktop
flow and had created it with Web which does require a client secret (Azure
didn't make it super obvious). I can update the page later today
