### ISSUE TITLE
Don't show "No updates where found for ModName" popup when checking for updates

### ISSUE THREAD

**Issue by Jummit** [ATLauncher/ATLauncher#416]
**Is your feature request related to a problem? Please describe.**
When checking for updates in a large pack, the "No Updates" popup has to be closed a lot of times.

**Describe the solution you'd like**
Either don't show a popup, as the information that the mods don't have an update is implied by only showing a popup for mods with update.

**Describe alternatives you've considered**
Use a autoclicking script to click the "Ok" button for all popups.

![image](https://user-images.githubusercontent.com/28286961/101978825-2a560080-3c58-11eb-9a1f-b63f09f81029.png)

**Comment by RyanTheAllmighty** [comment]
Duplicate/covered in #409
