### ISSUE TITLE
Ability to define file version when exporting a modpack

### ISSUE THREAD

**Issue by Profilename1** [ATLauncher/ATLauncher#419]
**Is your feature request related to a problem? Please describe.**
When I export a modpack the version field in the manifest file defaults to the minecraft version. To change this, have to unzip the file, modify the manifest.json manually, and then rezip everything back up.

**Describe the solution you'd like**
It would be a lot cleaner if there was just a way to enter that information when exporting the pack, similarly to how you can name an author.

**Describe alternatives you've considered**
I suppose the alternative is doing this manually, which I'll admit does work.

**Additional context**

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
