### ISSUE TITLE
Disabled mods included when exporting modpack

### ISSUE THREAD

**Issue by Profilename1** [ATLauncher/ATLauncher#420]
**Describe the bug**
When a modpack is exported it includes mods that have been disabled.

**To Reproduce**

1. Create vanilla w/ forge instance
2. Add mods using in-launcher mod manager
3. Disable mods using in-launcher mod manager
4. Export modpack
5. Import modpack into admin panel. The disabled mods will be in the xml. I assume they would also be there if you just imported the zip into the launcher as well but I haven't tested that.

**Expected behavior**
Expected behavior would be for disabled mods to not be included in an export unless the folder is checked.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
