### ISSUE TITLE
Enabling the "Remember window size and position" config in the settings crashes on relaunch.

### ISSUE THREAD

**Issue by ProxyNeko** [ATLauncher/ATLauncher#423]
**Describe the bug**
When you enable the "Remember window size and position" option in the settings tab then save, quit and restart the launcher, it crashes while loading. The only way to undo the crash is to delete or manually edit the config file for the launcher in the folder it's stored/installed in.

**To Reproduce**

1: Start the launcher and go to the settings tab.
2: Enable the "Remember window size and position" option and save.
3: Exit out of the launcher fully and then restart it.
4: The crash happens right after the "Made By Bob*" and "*(Not Actually)" message shows in the launchers console. 

**Expected behavior**
The launcher *should* start up without issue and position itself where it was last moved to in the same size it was last used in.

**Logs**
https://paste.atlauncher.com/view/c12706b4

**Screenshots**
N/A

**Desktop (please complete the following information, or remove if not applicable):**

- OS: Windows 10
- Version: 10.0.19041 Build: 19041

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
