### ISSUE TITLE
Launcher Doesn't Honor System Default Web Browser (Linux)

### ISSUE THREAD

**Issue by ThisNekoGuy** [ATLauncher/ATLauncher#424]
**Describe the bug**
When clicking ```view``` on a mod, when adding a Curse mod and more than one web browser is installed, the launcher will prioritize Chromium/Chrome over any default web browser set by the system.

**To Reproduce**

1. Go to "Instances"
2. Click on "Add Mod"
3. Click "View" on any mod

**Expected behavior**
System default web browser opens, as with any other application that requests a page to be open.

**Desktop (please complete the following information, or remove if not applicable):**

- OS: EndeavourOS (Arch-linux based distro)
- Desktop Environment: KDE
- Browser(s): Firefox & Chromium
- Version: Rolling Release
- Java Used for Launcher: Java 11

**Comment by jamierocks** [comment]
For reference, the implementation of opening a URL is https://github.com/ATLauncher/ATLauncher/blob/b32ab65c115236706a857455e90a567ddf928ce2/src/main/java/com/atlauncher/utils/OS.java#L146-L160

**Comment by RyanTheAllmighty** [comment]
> For reference, the implementation of opening a URL is
> 
> https://github.com/ATLauncher/ATLauncher/blob/b32ab65c115236706a857455e90a567ddf928ce2/src/main/java/com/atlauncher/utils/OS.java#L146-L160

Guessing the if else needs to be switched. Guess Java is maybe doing something odd when it calls `Desktop.getDesktop().browse(uri);`

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
