### ISSUE TITLE
Unable to see Version to Install without opening the dropdown on mods with long file names

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#427]
**Describe the bug**
When updating mods that have long file names, I am unable to see the Version To Install until I click the dropdown.

**To Reproduce**

1. Select a mod that has an update available and long file names, such as mod menu
2. Check for updates
3. See the dropdown

**Expected behavior**
The contents of the dropdown are visible before clicking on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/5914284/103433150-a5ed0280-4bb1-11eb-88ea-39b2511112ff.png)
![image](https://user-images.githubusercontent.com/5914284/103433042-d338b100-4baf-11eb-8cba-410be9699eee.png)
![image](https://user-images.githubusercontent.com/5914284/103433049-f9f6e780-4baf-11eb-8e9d-5202c7c62f6c.png)

**Desktop:**
- OS: MX Linux 19.3
- ATLauncher 3.4.1.1

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
