### ISSUE TITLE
More helpful date format selector when the day and month are the same

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#429]
**Is your feature request related to a problem? Please describe.**
When the day and month are the same (ex. 01/01, 02/02, etc) it's hard to tell what date format is selected in the dropdown.

**Describe the solution you'd like**
Use a set date for the dropdown that clearly shows what format it is in for all of the options (ex. `12/31/2020`)

**Describe alternatives you've considered**
Show letters for the options instead of the date (ex. `mm/dd/yyyy`)
Show letters in parenthesis beside the options and continue showing what the current date will look like. Ex. `01/01/2021 (mm/dd/yyyy)`

**Additional context**
![image](https://user-images.githubusercontent.com/5914284/103444371-62d07500-4c2d-11eb-9b5e-b9d950d69c8d.png)

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
