### ISSUE TITLE
Unable to install Fabric instance

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#433]
**Describe the bug**
When attempting to install or reinstall a Fabric instance, the install fails (The logs show that it's getting a 404 response)

**To Reproduce**

1. Go to Vanilla Packs
2. Create a new Vanilla Minecraft With Fabric instance
3. Click install

**Expected behavior**
Fabric installs successfully

**Logs**
https://paste.atlauncher.com/view/11a7c723

**Desktop (please complete the following information, or remove if not applicable):**

- OS: MX Linux 19.3
- ATLauncher 3.4.2.2

**Comment by RyanTheAllmighty** [comment]
Released with 3.4.2.3
