### ISSUE TITLE
ARM64 lwjgl needs workaround

### ISSUE THREAD

**Issue by theofficialgman** [ATLauncher/ATLauncher#437]
Minecraft does not distribute an arm64 lwjgl 2 or 3 dependency (even with the official launchers)

In order to fully support arm64 and arm32 launching minecraft. An arm system configuration needs to be detected and the lwjgl dependency can be downloaded (precompiled) from the website https://www.lwjgl.org/browse/stable/linux

**Comment by RyanTheAllmighty** [comment]
This is something that Mojang will need to address with the release of the M1 macs. Once they address it, we'll support it.

**Comment by mobilegmYT** [comment]
Oh hey! I was searching to make an issue on this actually. There was a method to run MC java on RPI as described here: https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=284448. You could just yoink them and make it so ATLauncher auto-downloads and links to them.

**Comment by RyanTheAllmighty** [comment]
As I said, once Mojang support it, it will come for free. I have no intention of hacking it in sorry.

**Comment by CoolCat467** [comment]
@mobilegmYT https://github.com/CoolCat467/fix-lwjgl is a temporary wrapper script that can fix this until Mojang gets it done themselves
