### ISSUE TITLE
0KB mod files

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [ATLauncher/ATLauncher#438]
**Describe the bug**
Mods folder has lots of empty jar files which is 0KB, when i start minecraft it says 'missing mods'

**To Reproduce**

1. Adding a FTB pack via launcher, in this case FTB stoneblock 2
2. Click on 'Play'
3. 'Missing Mods:...'
4. Click on 'Open Mods Folder'
5. All the missing mods 0KB large but with names

**Expected behavior**
Download mods correctly

**Logs**
[latest.log](https://github.com/BecksIsAlreadyTaken/Troubleshooting/blob/main/latest.log)

**Screenshots**
[missing mods](https://github.com/BecksIsAlreadyTaken/Screenshots/blob/main/missing.png)

**Desktop (please complete the following information, or remove if not applicable):**

- OS: [Windows10]
- Browser [Chrome]
- Version [ATlauncher 3.4.2.5]

**Additional context**
-Tried reinstalling still the same;
-Tried using proxy still the same.

**Comment by RyanTheAllmighty** [comment]
Yeah this is unfortunately the issue with the modpacks.ch API used. Their API didn't return correct file sizes and hashes so we cannot verify if you were able to correctly download files or not.

All you can do is keep reinstalling it until it finally worked and downloads correctly. Their downloads can be slow and API unreliable at times, so you may have better luck waiting some time and trying again later.

**Comment by RyanTheAllmighty** [comment]
I've added a fix going forward so that files that download with 0 size won't be considered valid since it's a valid case that a file with no size is highly likely to have broken, but unfortunately doesn't fix the root issue present in the api.

**Comment by BecksIsAlreadyTaken** [comment]
Appreciate it, keep up the good work !
