### ISSUE TITLE
Not fullscreen but it shows full screen once I click on that setting minecraft shuts

### ISSUE THREAD

**Issue by Tealhawk1511** [ATLauncher/ATLauncher#441]
<img width="2560" alt="Screen Shot 2021-01-23 at 11 52 42 PM" src="https://user-images.githubusercontent.com/78020596/105831892-4ab20280-5fed-11eb-9aae-38fba1d00e5a.png">

**Comment by RyanTheAllmighty** [comment]
Please provide more information, including detailed steps to reproduce and logs

**Comment by RyanTheAllmighty** [comment]
Please visit our Discord at https://atl.pw/discord for support issues. The GitHub issue tracker is not for these types of issues
