### ISSUE TITLE
Videos tab not displaying videos of my modpack, instead displaying links to adult novel audiobooks

### ISSUE THREAD

**Issue by BBoldt** [ATLauncher/ATLauncher#442]
**Describe the bug**
The videos tab for my modpack shows tons of unrelated videos, and a lot of them are a bit risqué.

**To Reproduce**
Visit: https://atlauncher.com/pack/Unabridged/videos
Browse all the adult audiobooks that show up. 🤣

**Expected behavior**
Should show these videos instead of random adult novel audiobooks:
https://www.youtube.com/results?search_query=unabridged+modpack

**Screenshots**
![image](https://user-images.githubusercontent.com/1463458/105846118-908cad80-5f90-11eb-9e66-38b504f9e845.png)

**Additional context**
It would be nice if we could specify the search terms for this page, or even just add the word "modpack" to whatever is being used to search for videos, there are tons of videos of my pack on youtube.

**Comment by RyanTheAllmighty** [comment]
This is not a launcher issue, closing
