### ISSUE TITLE
[Linux] Icon name for AUR desktop file

### ISSUE THREAD

**Issue by TecCheck** [ATLauncher/ATLauncher#448]
**Is your feature request related to a problem? Please describe.**
I have the [papirus icon pack](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/) installed on my linux machine which is nice, because  all the icons have a similar look to them, but the `.desktop` file of AT Launcher gives a path for the icon, so the icon pack can't override the icon.

**Describe the solution you'd like**
In the .desktop file instead of writing
```ini
Icon=/usr/share/pixmaps/atlauncher.png
```
you could name an icon like so:
```ini
Icon=atlauncher
```
I tested this change and it works.

**Describe alternatives you've considered**
A user could create his own `.desktop` file and change to line, mentionen above by himself, but this is not beginner friendly and the solution above is quite easy.

**Additional context**
After I wrote all this I saw that the deb package already has this change.

**Comment by RyanTheAllmighty** [comment]
I've added in a scalable icon to mimic what we do for the deb/rpm packaging and changed the desktop file. Will go out with the next update to AUR
