### ISSUE TITLE
Change all java arguments

### ISSUE THREAD

**Issue by Dragonlord1005** [ATLauncher/ATLauncher#451]
**Is your feature request related to a problem? Please describe.**
I am frustrated and annoyed by the fact that I can't change all of Atlaunchers arguments

**Describe the solution you'd like**
Ability to alter all the java arguments used to launch Minecraft through Atlauncher

**Describe alternatives you've considered**
The only alternative I have considered was adding a developer mode to Atlauncher to allow you to do this

**Comment by RyanTheAllmighty** [comment]
What arguments in particular are you looking to control? User has full control of every Java argument outside of the ones that Minecraft adds for launching

**Comment by Dragonlord1005** [comment]
Well for starters, it forces it to use the latest intel drivers, and you should be able to change that via Java arguments

**Comment by RyanTheAllmighty** [comment]
What are you going on about? You can't set drivers from the command line  if your talking about the argument about tricking drivers, that's coming from Mojang and on Windows 10 and ensures dedicated GPUs are used, not discrete ones, there's no need to turn that off.

Provide examples and proof of what your seeing along with real reasoning behind why you don't want them and it'll be considered. But closing for now as you've not provided any real issue or
