### ISSUE TITLE
Installing Mod window too small for dependencies to display

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#452]
**Describe the bug**
When trying to install a mod that has dependencies, the window size is too small to actually see most of the details. The screenshot is worth a thousand words. The arrow on the right belongs to the dropdown for the mod version. No dropdown is visible for dependency versions.

**To Reproduce**
1. Go to add mods to an instance (In this case I am using a Fabric 1.16.5 Instance, with the option enabled to show all mods for the major version, 1.16.X)
2. Attempt to install Blockshifter (It happens with other mods too but I don't know which off the top of my head)

**Expected behavior**
All details are visible so I can see what dependency I'm installing

**Screenshots**
![image](https://user-images.githubusercontent.com/5914284/108605676-4e7e3e00-737b-11eb-8e7b-3d640f28897b.png)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): MX Linux 19.3
- Java Version: Java 8

**Comment by RyanTheAllmighty** [comment]
Looks to be OS/Java dependent. It's fine on Windows. As a workaround I'll set that dialog to be resizable. I wanna get most windows to be resizable to cater for these types of issues anyway

**Comment by The-Fireplace** [comment]
That sounds like a reasonable workaround to me. If there's any info I can provide to help get the default sizing right, let me know. If it's logs, I can post them; I just didn't expect data on how it's figuring out the window size to be logged by default.

**Comment by RyanTheAllmighty** [comment]
Okay so I got a MX Linux box booted up, and was able to replicate on Blockshifter mod. Adding a minimum size to the dialog fixes the issue and it shows correctly now

I'll still make these dialogs resizable to prevent more issues in the future around sizing, but the root issue should be fixed next update

**Comment by The-Fireplace** [comment]
Amazing, thanks!
