### ISSUE TITLE
Render skin on a 3D model

### ISSUE THREAD

**Issue by KraXen72** [ATLauncher/ATLauncher#456]
**Is your feature request related to a problem? Please describe.**
Currently the skin is loaded on a flat model and can't be rotated

**Describe the solution you'd like**
a 3D animated model you can rotate that the skin is loaded on (like in the official launcher)

**Comment by RyanTheAllmighty** [comment]
Telling you now, this is not likely at all to be implemented. It's very complex and outside my understanding to do. Welcoming a PR to implement though

**Comment by KraXen72** [comment]
is this launcher in electron? if yes, i can implement it

**Comment by RyanTheAllmighty** [comment]
No, it's Java based

**Comment by KraXen72** [comment]
i don't know any java, so sorry, i can't pr it. it would be a cool feature tho, so if you are bored sometime you might give it a shot. anyway thanks for responding, im closing this now.

**Comment by KraXen72** [comment]
feel free to reopen if you decide to implement it
