### ISSUE TITLE
automatically build mod jar from github

### ISSUE THREAD

**Issue by KraXen72** [ATLauncher/ATLauncher#457]
probably a bit of a crazy request lol, but would be super cool if you could add a github repo to a mod (like sodium) and it would build a .jar in the background from the latest commit. (not take the latest release, builld from latest commit)

i can imagine it would be pretty hard to implement lol, but if this was a thing, it would be really useful (latest sodium patches, etc)

**Comment by KraXen72** [comment]
this problem could also be solved by being able to add github repos as source for mods and have it pull jars from automatic build artifacts. i think this would be a lot more easier since the jars are already built. (if the repo has it set up, otherwise it would pull releases)

**Comment by Doomsdayrs** [comment]
@RyanTheAllmighty I think the amount of effort for this feature would be way too high for, the benefit it may have. Closing as out of scope.

**Comment by KraXen72** [comment]
alright, and how about being able to retrieve build artifacts if the repo has set up CI builds of the mod?

**Comment by Doomsdayrs** [comment]
> alright, and how about being able to retrieve build artifacts if the repo has set up CI builds of the mod?

More possible, best to make a separate issue focused on that.

**Comment by KraXen72** [comment]
it's alright. it was just an idea anyway. this issue was mainly created during the period starlight didn't have proper builds on modrinth or curseforge. since then, not only starlight is no longer needed, but modrinth became a lot more capable and has almost all, if not all, mods i want on it.

if anyone is interested in this alternative solution with ci artifacts, feel free to create a new issue!
