### ISSUE TITLE
XDG Base Directory support for config files (Linux)

### ISSUE THREAD

**Issue by benstockil** [ATLauncher/ATLauncher#461]
In order to reduce home directory clutter, please consider storing configuration files in `$XDG_CONFIG_HOME/atlauncher` instead of `$HOME/.atlauncher`, according to the XDG Base Directory Specification. 

More information: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.

**Comment by TecCheck** [comment]
For legacy compatability the `$HOME/.atlauncher` folder could have a higher priority, so if it exists the files will be read from there. This way users can keep thier files and have the option to move the folder to the new location.

**Comment by RyanTheAllmighty** [comment]
We currently use `INSTDIR="${XDG_DATA_HOME-$HOME/.local/share}/atlauncher"`

You're likely using the jar itself in guessing in which case you can use the `--workingDir` command line argument
