### ISSUE TITLE
Check for updates gives results when the only newer files are incompatible with the current instance

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#466]
**Describe the bug**
When using "Check for Updates", the popup will show for some mods that don't actually have compatible updates available. A common pattern I'm seeing here is that these mods have more recent files which aren't for the same Minecraft version and/or mod loader.

**To Reproduce**

1. Set up a Fabric 1.16.5 instance
2. Install AppleSkin
3. Check for AppleSkin updates
4. See that it suggests the version that is already installed.

**Expected behavior**
Updates only show if there is actually an update that can be used with the current instance.

**Screenshots**
![image](https://user-images.githubusercontent.com/5914284/115963838-c89b8200-a4e6-11eb-8d14-d0541923caa6.png)
![image](https://user-images.githubusercontent.com/5914284/115963850-e832aa80-a4e6-11eb-98e6-8815bdb317d8.png)

**System information:**
- OS (including distro/version): MX Linux 19.4
- Java Version: Java 8

**Additional Context:**
Checking for updates for all mods in my instance is annoying when most of the time the popup suggests the version that's already installed.
Mods I've seen that do this on my Fabric 1.16.5 instance:
- AppleSkin
- Applied Energistics 2
- Auto-Run
- Autofish
- Blockshifter
- Bow Infinity Fix
- Cardinal Components
There are more, but I'm sure this should be plenty if you need to try it out with a few different ones.

**Comment by RyanTheAllmighty** [comment]
Fixed and released with version 3.4.3.2
