### ISSUE TITLE
Updating/reinstalling forge on an instance of a Vanilla Pack, permanently deletes the config folder

### ISSUE THREAD

**Issue by Jack-McKalling** [ATLauncher/ATLauncher#468]
**Describe the bug**
If you update or reinstall the forge version of an instance, and that instance was created from a Vanilla Pack (which mods you selected yourself manually using the "Add/Edit Mods" buttons), the whole config folder of that instance will be permanently deleted. This means all configurations made to the mod pack is lost, unless you restore a backup of it.

**To Reproduce**

1. Go to the "Vanilla Packs" tab
2. Click on "New Instance" under "Vanilla Minecraft with Forge", and follow the procedure to install a **previous version of forge**
3. Go to the "Instances" tab
4. Click on the "Add Mods" button
5. Install any mod (that you know has client or server configs, such as JEI)
6. Click the "Play" button to boot the instance once, and then exit it again
6. Now click the "Open Folder" button on this instance, and within the instance directory, open the "config" folder
7. Open any config file present and make some changes (also make note of these)
8. Now click the "Reinstall" button
9. Update to the latest Forge version
10. Click the "Open Folder" button again
  → ❌ Notice the "config" folder is now gone
11. If you restart the instance to actually play it, you'll see the above noted changes you made are also "reverted"

**Expected behavior**
When you create a vanilla pack instance, you're expected to select the mods yourself, and that obviously includes making configuration changes as desired. It makes no sense that these changes are deleted just like with a normal modpack, which can regenerate its configuration. I expected the folder to not be changed by updating the forge version, because these configurations cannot regenerate, as it is a custom design.

**Logs**
N.A.

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Windows 10
- Java Version: 1.8.0_291-b10

**Additional context**
I've talked to you about this on the discord server, and I originally thought #463 would fix it but it didn't actually change anything.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.4.0 of the launcher
