### ISSUE TITLE
Java arguments added, when none specified.

### ISSUE THREAD

**Issue by Redo11** [ATLauncher/ATLauncher#471]
**Describe the bug**
So I want to play on JAVA 11+, but ATLauncher, tries to add arguments, that are incompatible, even though, there were none specified.

**To Reproduce**

1. Go to instance settings
2. Change JAVA to newer version
3. Remove all arguments
4. Save settings
5. Launch instance
6. JAVA VM error

**Expected behavior**
I expect launcher to respect my settings and not change them.

**Logs**
[03/06/2021 13:31:20 PM] OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[03/06/2021 13:31:20 PM] Unrecognized VM option 'CMSIncrementalMode'
[03/06/2021 13:31:20 PM] Error: Could not create the Java Virtual Machine.
[03/06/2021 13:31:20 PM] Error: A fatal exception has occurred. Program will exit.
[03/06/2021 13:31:20 PM] Checking for updated files!

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux
- Java Version: Any JAVA 11+ (Zulu, openjdk etc)

**Additional context**
I have no idea why, but the selection box for JAVA version always shows java-8-openjdk, while text input below shows actually selected version. Might be a visual bug.
Launcher settings have also been checked.

**Comment by RyanTheAllmighty** [comment]
Please provide logs using the Upload Logs button on the launchers console after the issue occurs. They provide much more information

**Comment by Redo11** [comment]
https://paste.atlauncher.com/view/f3b3be66-1d51-4d0a-ba37-edaae58d69eb - Openjdk 11
https://paste.atlauncher.com/view/5bf33208-7ea3-40e9-9f46-48817cb892fc - Zulu 15
https://paste.atlauncher.com/view/01e2a6dd-f595-48b3-842e-1ac0a1533fe7 - Openjdk 8

**Comment by RyanTheAllmighty** [comment]
Looks like it was force adding in some arguments when there are none set. Not sure why that was added, but the logic in it was broken anyway so just completely removed it. Now it won't force add in any specific JVM flags

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.4.0 of the launcher
