### ISSUE TITLE
Adding a possibility to choose java ver on versions 1.17+

### ISSUE THREAD

**Issue by Redo11** [ATLauncher/ATLauncher#476]
**Is your feature request related to a problem? Please describe.**
I want to use custom java builds and it is impossible right now, with how launcher handles it. Also I would prefer to use local, system installed, java anyways.

**Describe the solution you'd like**
Add a posibility to choose java, when versions are limited

**Describe alternatives you've considered**
When a minecraft asks for a specific java version, launcher only could get suggested by it, or refuse to run version 16-, rather than any unofficial, and only if desired version is not available on system, install it itself. It could also ask user, to select a desired action.

**Additional context**
None, tbh.

**Comment by RyanTheAllmighty** [comment]
You can disable it from using the Java provided by Minecraft in the settings of the launcher
