### ISSUE TITLE
Add Technic support

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#477]
Got everything else, may as well add support.

While I'm still against the highly pirated beast that is Technic, having completion and everything available in one place is probably better.

Will need to see how I end up feeling about this once it's mulled for a bit

**Comment by Pyker** [comment]
Hi,

I'd love to hear your reasons as to why you describe us as a "highly pirated beast".

Also, if you need any help interfacing with our APIs, let me know.

**Comment by RyanTheAllmighty** [comment]
Yeah definitely bit harsh wording there on my end. But just basing it on history of the platform, even now just searching for common packs like SkyFactory, FTB, Direwolf, ATM, etc, all show that the issue still exists with reuploads, which is the only reason I'm hesitant at all.

But in saying that similar issues occur on CurseForge (albeit not as much probably because they're just the majority platform), so it really shouldn't be an issue, it's kind of expected in public platforms, and moderation only gets you so far before it becomes a full time job in itself.

**Comment by Pyker** [comment]
I agree with you on the repacks/reuploads. In the end it's a game of whack a mole and we have very limited human resources.
