### ISSUE TITLE
Reinstalling 1.16.5 Forge instance with 1.17 allows selection of older 1.16.5 Forge releases

### ISSUE THREAD

**Issue by Cherry** [ATLauncher/ATLauncher#480]
**Describe the bug**
Reinstalling a 1.16.5 Forge instance and selecting 1.17 will present older Forge 1.16.5 versions in error, and then will trigger another error when attempting to reinstall.

**To Reproduce**

1. Create a 1.16.5 Forge instance
2. Edit instance. Reinstall. Select 1.17
3. Forge version dropdown is populated with old 1.16.5 versions
4. Attempt to reinstall

**Expected behavior**
An error/warning that there are no Forge versions for this Minecraft version.

**Logs**
- https://paste.atlauncher.com/view/0ae31669-3f8c-4dbf-ae4b-99c5f3e683ff
- Another example from Discord: https://paste.atlauncher.com/view/df2a7ca6-76fd-4cca-8804-fbef06c366f0

**Comment by RyanTheAllmighty** [comment]
This has been fixed with version 3.4.4.5
