### ISSUE TITLE
Illegal Reflective Access To Field s11.XToolkit.awtAppClassName

### ISSUE THREAD

**Issue by pofdzm** [ATLauncher/ATLauncher#483]
pofdzm@pofdzm:~$ atlauncher 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.atlauncher.App (file:/home/pofdzm/.local/share/atlauncher/ATLauncher.jar) to field s11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of com.atlauncher.App
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

OS: elementary OS 5.1.7 Hera x86_64 (based on ubuntu 18.04 so installed the deb package)
Kernel: 5.12.13-xanmod1

pofdzm@pofdzm:~$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

**Comment by RyanTheAllmighty** [comment]
Please visit our Discord for support with the launcher. https://atl.pw/discord
