### ISSUE TITLE
Allow disabling discord presence per instance

### ISSUE THREAD

**Issue by StarrFox** [ATLauncher/ATLauncher#485]
**Is your feature request related to a problem? Please describe.**

Some of my instances have their own discord presence that I would like to show instead of the default from ATlauncher 

**Describe the solution you'd like**

An option within instance settings to disable discord presence for that instance

**Additional context**

Originated from support channel in ATlauncher discord: https://discord.com/channels/117047818136322057/193304339941556225/863591326276386826

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.5.0
