### ISSUE TITLE
Add "Play offline" support so LAN play with different names using the same account is possible

### ISSUE THREAD

**Issue by dmp1ce** [ATLauncher/ATLauncher#492]
**Is your feature request related to a problem? Please describe.**
I want to play with friends on LAN with the same account. With MultiMC it is possible to play "offline" and change to another username. This prevents joining most servers, but allows for playing LAN with the same account.

**Describe the solution you'd like**
I would like a "Play Offline" mode which allows the username to be changed. This way I can open a LAN game on one computer and on another computer I can "Play Offline" with a different name and join the LAN game.

**Describe alternatives you've considered**
I cannot think of another alternative.

**Additional context**
MultiMC implements this feature which might be a good example for implementing it in ATLauncher.

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.7.0

**Comment by dmp1ce** [comment]
Wow. Completed already. I'll give this a try.

**Comment by dmp1ce** [comment]
Worked great BTW. Exactly how I expected. 👍
