### ISSUE TITLE
A way to change LWJGL used.

### ISSUE THREAD

**Issue by jtmaston** [ATLauncher/ATLauncher#504]
**Is your feature request related to a problem? Please describe.**
Running minecraft on apple's new M1 chip requires the use of a different version of lwjgl ( compiled for ARM ). Is there any way that we chould switch from within the launcher?

Note: I have the lwjgl files.

**Comment by RyanTheAllmighty** [comment]
There is not.

Once Minecraft supports ARM devices out of the box, the launcher will support it as well. Until then we don't have a way to run on ARM

**Comment by jtmaston** [comment]
Thank you!

**Comment by CoolCat467** [comment]
@jtmaston My script https://github.com/CoolCat467/fix-lwjgl does exactly this. The script has extra stuff to auto-download required files, but the big thing is specifying the LWJGL library path. For example, `-Dorg.lwjgl.librarypath=/home/pi/lwjgl2arm32` and making sure that the folder specified has the .so (shared object) files
