### ISSUE TITLE
Upload Instance ModList as text 

### ISSUE THREAD

**Issue by Targren** [ATLauncher/ATLauncher#510]
**Is your feature request related to a problem? Please describe.**

It's very irritating to help someone looking for support (on /r/feedthebeast, e.g.) when the easiest way they have to provide their list of mods is several screenshots of their windows folder.

**Describe the solution you'd like**
A simple function to "Upload" (like the logs have) a list of the mods used in an instance. 

**Describe alternatives you've considered**
Asking regular players to open a command line, navigate to the instance mods directory and redirect the output of dir/ls to a file - Way too complicated for most non-geeks (and savvy ones will probably balk at running commands on the CLI that they don't understand)

It's really just a QoL request to help people help other people more easily.

**Comment by RyanTheAllmighty** [comment]
Yup agree this would be nice to have and I have thought about it before, just never actioned it, but it would be super helpful to have in
