### ISSUE TITLE
Crash on startup with java 17.0.1 due to PermSize option

### ISSUE THREAD

**Issue by mtb-xt** [ATLauncher/ATLauncher#520]
**Describe the bug**
When an instance is set to use java 17, it immediately crashes on startup with the following error:

```
[16/11/2021 13:56:54 PM] Unrecognized VM option 'PermSize=32M'
[16/11/2021 13:56:54 PM] Error: Could not create the Java Virtual Machine.
[16/11/2021 13:56:54 PM] Error: A fatal exception has occurred. Program will exit.
[16/11/2021 13:56:54 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.

```

**To Reproduce**

1. Go to instance settings
2. Set 'use java provided by minecraft' to no
3. Select 'java-17-openjdk' or 'java-17-jdk'
4. Try to launch game
5. FFFUUU

**Expected behavior**
Minecraft to launch without forcing options. 

**Logs**
https://paste.atlauncher.com/view/e97acbb3-f09b-4224-9e3b-54d382769abf

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): [e.g. Windows 10, OSX Big Sur, Arch Linux]
```
java 17.0.1 2021-10-19 LTS
Linux 5.15.2-zen1-1-zen
```
OS: Arch Linux

- Java Version: [e.g. Java 8, Amazon Coretto 8]
local/jdk 17.0.1-1
    Oracle Java Development Kit
local/jdk-openjdk 17.0.1.u12-1
    OpenJDK Java 17 development kit

**Additional context**

**Comment by RyanTheAllmighty** [comment]
Ah yup looks like something I fixed a few weeks back around this (13c7b77d2c0b0dd9a49ae5375752a91ef681b5c0) didn't actually apply for custom paths.

It's still using the "preferred" Java distribution (in your case 8) and also incorrectly seeing that it's Java 8 and should use PermGen, which is incorrect logic.

Should be a simple enough fix to get out. Thanks for the report

**Comment by Maxo6453** [comment]
I found a way to avoid this problem on MacOS while launching a server at least. Go to LaunchServer.command in the server folder and just delete the PermSize option.

**Comment by mtb-xt** [comment]
Right, now that I think about this - a simple wrapper script would solve it until the release:

```
#!/bin/sh

LAUNCH_ARG=$@
LAUNCH_ARG_FIXED=$(echo $LAUNCH_ARG | sed -e 's/-XX:PermSize=\S*//g')
eval $LAUNCH_ARG_FIXED
```

Place that file somewhere, for example in your ~/bin  - `bin/minecraft-arg.sh` and then in your instance settings add it to the wrapper command: `/home/hawara/bin/minecraft-arg.sh %command%`

![image](https://user-images.githubusercontent.com/11381295/142718651-607da224-7c00-4fdf-90cb-66def8c80d08.png)

**Comment by RyanTheAllmighty** [comment]
I should be pushing out the fixed version tonight. So 3-4 hours if all goes to plan. You can grab the nightly build if you want a fix now (https://atl.pw/launcher-nightly)
