### ISSUE TITLE
Crashes whilst loading up a world (in my case brand new world on a new instance)

### ISSUE THREAD

**Issue by WxvenYT** [ATLauncher/ATLauncher#521]
**Describe the bug**
Mods load and get to the home screen, then go to create world, has building terrain text then shows shutting down internal server and crashes.
**To Reproduce**

1. Go to singleplayer
2. Click on create new or load an already created world
3. shows loading screen, has building terrain text, then shows shutting down internal server and then crashes.

**Expected behavior**

**Logs**
https://paste.atlauncher.com/view/3e8c14d9-c741-46c2-a9e6-c48c33e92b58

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Windows 10 home
- Java Version: Java 8 or whatever is the current

**Additional context**
Laptop specs
Model: Acer Nitro 5 AN515-55-5386
CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
GPU: NVIDIA 1650 ti
RAM: 16.0 GB (15.8 GB usable)

**Comment by RyanTheAllmighty** [comment]
Please visit our Discord for support with the launcher, we don't provide game/launcher support via GitHub. https://atl.pw/discord
