### ISSUE TITLE
Easy use of system installed GLFW/OpenAL

### ISSUE THREAD

**Issue by Redo11** [ATLauncher/ATLauncher#524]
**Is your feature request related to a problem? Please describe.**
Due to [https://github.com/glfw/glfw/issues/1112](GLFW bug) some launchers allow for loading system libraries rather than ones bundled with Minecraft.  

**Describe the solution you'd like**
The solution is already possible, through Java parameters, though it would be appreciated to have easy buttons for enabling/disabling the feature like MultiMC does.

**Describe alternatives you've considered**
Adding the Java parameters manually.

**Additional context**
![image](https://user-images.githubusercontent.com/49594490/142725839-b6ba0f6f-c0a7-4266-92ba-203255aebed3.png)
You can just add those 2 options on the bottom of Java/Minecraft section in settings

**Comment by UltraBlackLinux** [comment]
I'm experiencing the above mentioned bug and the new option does not appear to be working - The input bug has not poofed at least

**Comment by K4sum1** [comment]
> The solution is already possible, through Java parameters

How do I do this with parameters? I can't find anything about this online
