### ISSUE TITLE
Upload Log not working

### ISSUE THREAD

**Issue by Redo11** [ATLauncher/ATLauncher#526]
**Describe the bug**
Upload log returning 403 error

**To Reproduce**

1. Go to 'ATLauncher Console'
2. Click on 'Upload Log'

**Expected behavior**
Copy the logs

**Logs**
https://pastebin.com/NUz3Ab9X

**Screenshots**
![image](https://user-images.githubusercontent.com/49594490/142726671-b856d4e4-1564-4674-bc63-f742dfa90742.png)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux
- Java Version: Zulu 11

**Additional context**
That's why I use Pastebin

**Comment by RyanTheAllmighty** [comment]
Please restart the launcher, then attempt to upload the logs and if still failing, copy the logs into https://paste.ee without clearing the console and provide the link here

**Comment by Redo11** [comment]
https://paste.ee/p/Ooxxa

**Comment by RyanTheAllmighty** [comment]
You're on an old unsupported version of the launcher. Update to the latest to resolve the issue.
