### ISSUE TITLE
How to start without launcher (arm64)

### ISSUE THREAD

**Issue by serbInit** [ATLauncher/ATLauncher#532]
This isn't really a bug report, as amd64 isn't supported at all, but i've downloaded minecraft 1.18 (vanilla) through ATLauncher, and got openjdk-17-jre:amd64 on my system.

I have the command to run the game out of the log (obv missing authentication) but i'd like to start minecraft from the commandline

however it complains about net.minecraft.main.Main not existing

tl;dr;
so where / how do i need to invoke java to start minecraft ? (1.18 installed through ATLauncher)

**Comment by RyanTheAllmighty** [comment]
It completely varies per version as well as there being various pre launch tasks such as extracting native libraries. It's not something we can help you out with as it's a complex thing to do.

Once arm support comes for Minecraft, it should just work out the box, but until then, it won't work sorry
