### ISSUE TITLE
Security Vulnerability in Minecraft Java Edition

### ISSUE THREAD

**Issue by Enderknight2016** [ATLauncher/ATLauncher#536]
According to Mojang there is a vulnerability in Log4j which allows people to hack your computer via Minecraft Text Chat. The Vanilla Launcher has a fix implemented but AT Launcher skips the Vanilla Launcher and therefore a fix should be implemented, or the Vanilla Launcher should run before opening Minecraft for the AT Launcher. https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition

**Comment by RyanTheAllmighty** [comment]
Yes please see the news post in the launcher or on https://atlauncher.com the issue is fixed.
