### ISSUE TITLE
log4j is used in ATLauncher - Incoming fix?

### ISSUE THREAD

**Issue by Smart-Helper** [ATLauncher/ATLauncher#537]
Hello, so i used `wget https://raw.githubusercontent.com/rubo77/log4j_checker_beta/main/log4j_checker_beta.sh -q -O - | bash` to check if my system contains any log4j files and it found that ATLauncher uses that.

Im no dev and i have not enough expertise to assess if this is an issue that is already fixed or not.

Can some1 tell me what i have to do to fix this?

**Comment by RyanTheAllmighty** [comment]
What exactly is it finding?

**Comment by RyanTheAllmighty** [comment]
Seems I actually forgot to upgrade the main applications version of Log4J. This will be fixed and pushed out shortly.

**Comment by Smart-Helper** [comment]
The script doesnt specify what exactly is found.
![image](https://user-images.githubusercontent.com/38812603/146097953-ec92ac75-4bd7-4491-b379-0584fc558d9c.png)

**Comment by RyanTheAllmighty** [comment]
Alright restart your launcher to get the update and it will be good now. If that tool finds anything else, note that it has been patched by Mojang and is safe to play, the tool likely won't account for that.
