### ISSUE TITLE
No Discord Server

### ISSUE THREAD

**Issue by 00001H** [ATLauncher/ATLauncher#542]
**Describe the bug**
The ATLauncher discord link(atl.pw/discord) is BROKEN and it says link invalid.
There are no "ATLauncher" discord servers on the search result list.

**To Reproduce**
visit atl.pw/discord . See it says "invalid invite".
try to search on Discord server list, see no "ATLauncher" server pops up.

**Expected behavior**
Expecting a non-broken link on atl.pw/discord .

**Comment by RyanTheAllmighty** [comment]
Link is fine. You can try the non shortened link (https://discord.com/invite/B7TrrzH) or the vanity invite url (https://discord.com/invite/atlauncher) and if none of those work, that's something you'd need to take up with Discord

**Comment by 00001H** [comment]
@RyanTheAllmighty THANK YOU SO MUCH!!! I FINALLY GOT THE SERVER!!!
