### ISSUE TITLE
[new feature] updating custom modpack

### ISSUE THREAD

**Issue by mastermc05** [ATLauncher/ATLauncher#543]
**Is your feature request related to a problem? Please describe.**
I made a modpack and play with my friends on LAN, every time i want to make an update (add some mods, update some), it's hard enough to work with everyone, so i just have to sent them the new mod folder and they need to replace the old one, but the mod folder is big enough so it's a bit problematic 

**Describe the solution you'd like**
To be able to import the modpack over the old one (with a option to change only the mod folder), maybe this to add function to reinstall button, not just [throwing NullPointerExeption ](https://pastebin.com/3PjScW4Z)

**Describe alternatives you've considered**
To create an own export format for updating/importing 

**Additional context**

**Comment by RyanTheAllmighty** [comment]
Duplicate of #475
