### ISSUE TITLE
Windows Server -> Launch With GUI not working if path has a space in the folder name

### ISSUE THREAD

**Issue by november781** [ATLauncher/ATLauncher#544]
**Describe the bug**
When using an install folder like `AT Launcher` that contains a space in its name the launch server with Gui button fails.

**To Reproduce**

1. Install the launcher in a folder using a space
2. Click on Launch With GUI on a server
4. Command Prompt opens and errors with "is not recognized as an internal or external command,
operable program or batch file."

**Expected behavior**
Server launches with Gui as desired

**Screenshots**
![cmd_xCOuS88R1G](https://user-images.githubusercontent.com/28309327/147889440-f864f1ae-bbaf-4cc7-8937-e4f704e4b3c0.jpg)

**System information (please complete the following information, or remove if not applicable):**

- Windows 10 Pro, Version 21H2, Build 19044.1415
- Java Version: Java 8 update 311

**Additional context**
This is entirely a user caused error, but it is one that should be avoidable with a change to how the command is called. I'm a bit rusty on my batch programming but I remember there was a way to call to folders that contain a space in their name.

**Comment by RyanTheAllmighty** [comment]
Good old windows and spaces. Should be a simple fix, thanks for reporting
