### ISSUE TITLE
While minecraft username is hidden in logs, the player's UUID is not

### ISSUE THREAD

**Issue by PORTB** [ATLauncher/ATLauncher#546]
**Describe the bug**
While the minecraft username is hidden in the logs, the uuid is not, which kind of defeats the purpose of hiding the username

It is shown like this:
ModLauncher running: args [--username, **MINECRAFTUSERNAME**, .... --uuid, **069a79f444e94726a5befca90e38aaf5** --accessToken, â�„â�„â�„â�„â�„â�„â�„â�„, ....]
(it's not my uuid btw)

**To Reproduce**

1. Launch an instance (of a version that uses UUID for players)
2. Look in the console window/upload a log
3. Your UUID will be visible in the ModLauncher running arguments

**Expected behavior**
Hiding the UUID

**Logs**
https://www.toptal.com/developers/hastebin/exapejipuy.yaml

**System information (please complete the following information, or remove if not applicable):**

- OS Windows 10 64 bit
- Java Version: 8

**Comment by RyanTheAllmighty** [comment]
That's odd, I thought it was hidden.

But yeah makes sense to have.

**Comment by RyanTheAllmighty** [comment]
This is odd, I cannot replicate this. I installed a 1.18.1 instance with the current version of the launcher with Forge installed and when it came to the ModLoader arguments, it showed as censored:

```
[05/02/2022 16:25:28 PM] [main/INFO] ModLauncher running: args [--username, **MINECRAFTUSERNAME**, --version, 1.18.1, --gameDir, **USERSDIR**\instances\Minecraft1181withForge, --assetsDir, **USERSDIR**\assets, --assetIndex, 1.18, --uuid, **UUID**, --accessToken, â�„â�„â�„â�„â�„â�„â�„â�„, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.66, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --width=854, --height=480]
```

Please let me know if you're still having this issue or not and if so provide a new set of logs as the last ones you provided are no longer available.

**Comment by PORTB** [comment]
I just checked again, it is definitely happening (1.18.1, forge, mojang account). I think this may be happening because my uuid is printing in the console without dashes for some reason, and the launcher is only replacing uuid in the console _with_ the dashes

**Comment by RyanTheAllmighty** [comment]
Oh that's odd, but thanks for confirming, I'll just make sure both get replaced
