### ISSUE TITLE
Hard to find Modpacks when searching if it doesn't meet one of the existing sort criteria (Popular, Last Updated, Total Download)

### ISSUE THREAD

**Issue by Targren** [ATLauncher/ATLauncher#554]
**Is your feature request related to a problem? Please describe.**

When attempting to search for a modpack by name, too many "near" (and not so "near") hits glut up the search results, so if the pack is neither brand new (and you can sort by Last Updated) nor particularly popular, you've got to vgrep the list looking for it. 

Example: "Magical Mischief Tour (MMT)", "Rustic Waters II" (Though this one was easy to find with "Last Updated") 

**Describe the solution you'd like**

I imagine the extraneous results are Curseforge's API's fault, so if it won't return an exact match: 

Either allow sorting results by name (Alphanumerically), so that users can at least know where in the list they should be looking, or allow us to specify modpacks by ID (similar to what was suggested in #487 )

**Describe alternatives you've considered**

Manually downloading and installing the instance blows up most of the benefits of using ATL in the first place

**Additional context**

![Capture](https://user-images.githubusercontent.com/11566412/157163610-e29e2c59-dfc4-45da-b9cc-b2c8caca9d34.PNG)
![Capture](https://user-images.githubusercontent.com/11566412/157163724-b97bd92a-ee24-4226-94e6-307d9bd88963.PNG)

**Comment by RyanTheAllmighty** [comment]
Ah yup I've been meaning to expand the sort list now that the new CurseForge api is up.

But yeah the fundamental poor search is down to CurseForge api end, but at least exposting A-Z filtering, which it look like you can sort by name, will be helpful.

Alternatively, you can always go to the instances tab and then click Import and give it a link to the pack on CurseForge.com and it will install the latest version, or to a specific versions url (with the files/8378273 at the end) to install a specific version.

Makes sense to have some manual lookup/add button to do the same thing in the pack browser to input a specific project id or url just for these cases

**Comment by Targren** [comment]
That workaround will be great, I hadn't considered it that way. Thank you!

**Comment by RyanTheAllmighty** [comment]
Okay I've added in the new category sorting by name as well as ability to change ascending/descending sorts and also added in id/slug/url manual pack addition for the CurseForge and Modrinth pack browser tabs.

Will go out with the next release, which was supposed to be soon after the forced migration change came into effect by Mojang, but seems to now be a staged rollout which may delay it, will have to see.
