### ISSUE TITLE
Mod updates stuck

### ISSUE THREAD

**Issue by mtb-xt** [ATLauncher/ATLauncher#557]
**Describe the bug**
When I click 'update mods' - and I've selected - enabled mods - the first update gets stuck on checking modrinth. If I close that window, the updates continue fine, but it's impossible to select versions on version select dialogue.

**To Reproduce**

1. Go to instance
2. Click on Enabled mods
3. Click check for updates

**Logs**
this is when the update is stuck
https://paste.atlauncher.com/view/e1914198-96d0-4960-9961-73e30d3213c5

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux
- Java Version: java-17-openjdk

**Additional context**

**Comment by RyanTheAllmighty** [comment]
Yup this was fixed with 3148184871fd2224164d90bf5feac56c715a2900 and will go out with next update
