### ISSUE TITLE
Console pops up on launch

### ISSUE THREAD

**Issue by Madis0** [ATLauncher/ATLauncher#571]
**Describe the bug**
When launching ATLauncher, a console window pops up.

**To Reproduce**

1. Launch ATLauncher
2. Look at the second window that popped up

**Expected behavior**
This window should not appear by default as it would confuse the users, only when some debug option is explicitly enabled.

**Logs**
If applicable, add logs to help explain your problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/8611110/164784163-4535fcb1-cdcb-4d4f-b006-ae11146b9b49.png)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Manjaro Linux 21.2.6
- Java Version: Temurin Java 18

**Additional context**
Installed from https://aur.archlinux.org/packages/atlauncher-bin FWIW.

**Comment by RyanTheAllmighty** [comment]
After contemplating this for some time, I've decided to keep the console window open by default. It's extremely helpful and not something I wish to add a bunch of extra support around by hiding it by default. I've never heard any other complaints about this window, so I don't consider it an issue at this time.
