### ISSUE TITLE
Rename "New Instance" to "Install"

### ISSUE THREAD

**Issue by Madis0** [ATLauncher/ATLauncher#573]
**Is your feature request related to a problem? Please describe.**
"New Instance" is not inherently clear that it is an action the user can take.

**Describe the solution you'd like**
Rename "New Instance" to "Install".

**Describe alternatives you've considered**
"Install instance", "Download instance", "Download"...

**Additional context**
It would also follow the convention of existing buttons like "Edit Instance" and "Reinstall".

**Comment by Doomsdayrs** [comment]
"Download" does not mean the same as "Install". Install is the action that is being taken, download is part of the action.

**Comment by Doomsdayrs** [comment]
Awaiting release
