### ISSUE TITLE
Windows server -> All launch options do not work if windows user folder in file path has a space.

### ISSUE THREAD

**Issue by Connoisseur-Cube** [ATLauncher/ATLauncher#577]
**Describe the bug**
If the windows user has a space in their name, like "john bash", and they install the launcher in their user folder, all launch options fail.

**To Reproduce**

1. Install Atlauncher in a folder which has a space in it.
2. Press any launch option (launch, launch with GUI, etc).
3. See error

**Expected behavior**
Server should start running

**Screenshots**
![image](https://user-images.githubusercontent.com/104766223/166225838-c24ad807-8b12-4b12-adbb-890cefb069d8.png)

**System information**

- Windows 10 Home , Version 21H2 , Build 19044.1645
- Java 8 Update 331 (64-bit)
- Java(TM) SE Development Kit 18.0.1 (64-bit)

**Additional context**
If I press "open folder" and run Launch Server batch file, The server will be up and running. Otherwise, pressing launch from the launcher will not work.

**Comment by RyanTheAllmighty** [comment]
Looks like a regression of #544

**Comment by RyanTheAllmighty** [comment]
Alright when this gets released, you'll need to recreate your servers and that should fix the issue, else you can add double quotes around the `%javapath%` parameter on line 41 and 44 in your servers `LaunchServer.bat` file as shown below if you don't want to recreate it

![image](https://user-images.githubusercontent.com/1723537/167629720-c59006c8-650c-4849-bfc9-c4736662020b.png)

**Comment by Connoisseur-Cube** [comment]
Awesome!
