### ISSUE TITLE
Quilt crash

### ISSUE THREAD

**Issue by GhostIsBeHere** [ATLauncher/ATLauncher#579]
**Describe the bug**
Quilt crashes upon launch. This crash occurs with only Quilt and Quilt Standard Libraries installed. This crash does not occur on other launchers such as PolyMC

**To Reproduce**

1. Create a new 1.18.2 Quilt instance of the latest version
2. Install Quilt Standard Libraries
3. Click Play
4. Crash

**Expected behavior**
Doesn't crash

**Logs**
[https://paste.atlauncher.com/view/602750a5-a6ce-4382-9f82-be1867e34dec](https://paste.atlauncher.com/view/602750a5-a6ce-4382-9f82-be1867e34dec)

**System information (please complete the following information, or remove if not applicable):**

- OS: MacOS 10.14.6
- Java Version: 17

**Comment by RyanTheAllmighty** [comment]
Yeah I fixed it to switch using quilt hashed with the fabric intermediaries but the config toggle was flipped. I've fixed that up now, restart the launcher to pick up the new config and reinstall the instance should do it, else just reinstalling the loader might also be fine.
