### ISSUE TITLE
Allow cracked accounts

### ISSUE THREAD

**Issue by kyngs** [ATLauncher/ATLauncher#580]
**Is your feature request related to a problem? Please describe.**
As a Minecraft plugins developer, I often need to test things including multiple players than only me.
But I do not want to spend money on another account(s) only for testing. Also, I do not wish to use TLauncher for this.

**Describe the solution you'd like**
Ideally, add an option to add cracked accounts.

**Describe alternatives you've considered**
Currently, I've just implemented it in my fork. It is a bit buggy, but it works. However, this is a bit unpractical because I would need to have my fork IDE project open all the time when I need it. I do not have the energy and knowledge to pack it into an OS package and keep it updated.

**Additional context**
I realize that this will get abused. I'm not sure whether there's some kind of compromise we could achieve? **Perhaps only allow this when you have at least one premium account registered?**

**Comment by RyanTheAllmighty** [comment]
No we do not support this and never will

**Comment by kyngs** [comment]
Well, I guess I will just keep maintaining my fork, I just hope you at least read what I wrote and not only the title.

**Comment by RyanTheAllmighty** [comment]
Of course. But we will never allow non premium accounts in the launcher. This has been asked many times, and it will never happen regardless of situation. Heck if Microsoft forced migration didn't do it, nothing will at this point.

Just be aware while maintaining a fork to check the Constants.java file as mentioned in the readme and use your own data sources and not our data and keys.

**Comment by Felix14-v2** [comment]
> I do not wish to use TLauncher for this

If you want, you can use its historically original and clean "version" – TLauncher Legacy (TL Launcher). It has open source and open development group in contrast to its fake (which, in addition to the source code, also stole the name).

> I often need to test things including multiple players than only me.
> But I do not want to spend money on another account(s)

You can use [In-Game Account Switcher](https://modrinth.com/mod/in-game-account-switcher), it supports offline-mode even without the need to log in to Mojang/Microsoft.
