### ISSUE TITLE
Use system glfw settings doesn't work

### ISSUE THREAD

**Issue by FederAndInk** [ATLauncher/ATLauncher#585]
**Describe the bug**
the "use system glfw" settings doesn't work, its needed for instance with Another Quality Modpack 2 on Linux as there is a bug on glfw<3.3.7

**To Reproduce**

1. Download an Another Quality Modpack 2 instance
2. check the "use system glfw" with glfw>=3.3.7 installed on the system.

I've tried setting it on the instance and globally.

**Expected behavior**
Use of the system glfw and thus no more crash

**Logs**
https://paste.atlauncher.com/view/985100cf-0a18-4b21-aa78-2988c8739d08

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux
- Java Version: java openjdk 18.0.1.1 2022-04-22 (use MC provided checked)
- ATLauncher version: 3.4.14.2

**Additional context**

**Comment by RyanTheAllmighty** [comment]
So my understanding of using system glfw/openal is that it's intended to not extract the native dll/so files, to which the launcher definitely doesn't do when the option is disabled, so the launcher, again from my understanding of how the option should work, is working correctly.

I've checked the natives folder on my own system with that setting disabled and it definitely doesn't get extracted.

Can you confirm one thing, When you launch the instance, in the main launchers folder (not the instances) in the temp folder, it should make a folder for the natives for the instance. Check that folder when you launch and see what the contents are and if that does indeed contain the `libglfw.so` file that is contained in the natives.

**Comment by FederAndInk** [comment]
I get this:

![Screenshot_20220521_161711](https://user-images.githubusercontent.com/24270152/169655727-1708b430-83fb-422e-88cc-be0de505f86d.png)

So, no libglfw.so

**Comment by FederAndInk** [comment]
it is working with polymc for example, maybe you can see how they do it: https://github.com/PolyMC/PolyMC/search?q=glfw

**Comment by RyanTheAllmighty** [comment]
Yup we do it the exact same way as PolyMC. Can you provide logs from PolyMC and I can compare what they're loading vs what we are. But the fact there's no glfw binaries in the natives folder shows that the launcher is doing the correct behaviour.

Having logs from both PolyMC and ATLauncher on your system to compare will help to try and pinpoint where the issue lies
