### ISSUE TITLE
Bad SEO for Bing

### ISSUE THREAD

**Issue by Madis0** [ATLauncher/ATLauncher#589]
**Describe the bug**
The website https://atlauncher.com is not optimized for the Microsoft Bing crawler as it does not appear there (at least not within in the first 10 pages!). This also affects other search engines that use Bing's results, including Yahoo, DuckDuckGo, Ecosia. 
Maybe your site once had malware so it got removed and you did not ask them to recheck?

**To Reproduce**

1. Go to Bing or any of the other engines I mentioned
2. Search for "atlauncher"
3. Try to find https://atlauncher.com

**Expected behavior**
Expected the official site to be the first result.

**Logs**
N/A

**Screenshots**
https://ibb.co/album/bR2rz1

**Additional context**
N/A

**Comment by Madis0** [comment]
https://github.com/ATLauncher/meta/issues/1

**Comment by Madis0** [comment]
Issues are now closed on that repo, so re-opening that issue here.

**Comment by RyanTheAllmighty** [comment]
I've done all I can on my end to resolve this. Bing just refuse to index the site no matter how many times I try and no matter what fixes I try. Their own site says it's all good and can be indexed fine without issues, but no matter how many attempts at submitting again and again, it doesn't seem to show up. At this point I've given up

**Comment by Madis0** [comment]
Btw, it seems to be fixed now:

![image](https://user-images.githubusercontent.com/8611110/232294153-ca7b1072-9bb3-4347-92e0-163204c0bd36.png)
![image](https://user-images.githubusercontent.com/8611110/232294270-bbe5928f-b058-45ec-89ee-66196bbd6f83.png)

**Comment by RyanTheAllmighty** [comment]
I guess they finally decided to start indexing, maybe just took some time. I'll take another look at the Bing dashboard just make sure there's nothing else that needs attention before probably forgetting about this again
