### ISSUE TITLE
Visual glitches occurring for a fabric modpack that *don't* show up for the same exact pack in PolyMC

### ISSUE THREAD

**Issue by coolreader18** [ATLauncher/ATLauncher#593]
**Describe the bug**
Some very strange graphical glitches that happen under ATLauncher but not PolyMC. Samples under the screenshots section

**To Reproduce**

1. Install the modpack "merged machinations" from technic
2. Make a test world and place down, like, a chest. cogwheels (especially large cogwheels) from create also seem to be consistent in making it happen.

**Expected behavior**
Normal visuals; I've tried and failed to reproduce these glitches under PolyMC.

**Logs**
If applicable, add logs to help explain your problem.

Compared logs and afaict there's no significant difference in ATLauncher's vs PolyMC's.

**Screenshots**
![2022-06-03_20 50 49](https://user-images.githubusercontent.com/33094578/171980712-361ad115-45af-4d4f-ab6f-273a33e5af16.png)
![2022-05-31_22 48 58](https://user-images.githubusercontent.com/33094578/171980723-a8ef8dc4-4a3a-4eb0-8b8b-970aefff7876.png)
![2022-05-31_22 31 46](https://user-images.githubusercontent.com/33094578/171980728-d1c629d0-b148-4c18-9d4f-3e6e01a78fb9.png)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux
- Java Version: happens both under mojang's Java 17 and the system's Java 18

**Additional context**

I don't really want you to debug my friend's modpack for me, but just wondering if there's anything that you might think "oh! here's the obvious place we set up graphics differently from PolyMC!" Also, it's the same lwjgl version for both launchers; 3.2.2

**Comment by RyanTheAllmighty** [comment]
Would need logs from both launchers launching the instance up until the point where the glitch is seen (or would be seen). Also make sure the same world is used in both (copy over the save folder) to remove that as a variable and then share the 2 logs and I can see if there's anything obvious

**Comment by coolreader18** [comment]
Sorry it took a bit, here's the log. I created the world under polymc, made a chest, closed the client, opened it again, opened the world, closed it, got those logs, copied the world to the atlauncher instance, started it opened the world closed it, got those logs.

**Comment by RyanTheAllmighty** [comment]
Try one thing @coolreader18 for the instance, click on Settings, then in the Java tab, uncheck the `Use Java Provided By Minecraft` and then in the Java path, set it to the same that the PolyMC instance is using (`/usr/lib/jvm/java-18-openjdk/bin/java`) and then save and see if that resolves the issue

**Comment by coolreader18** [comment]
I think I have tried that and it didn't do anything

**Comment by coolreader18** [comment]
I'm gonna try again real quick though.

**Comment by coolreader18** [comment]
Nope, still happening with the system java

**Comment by RyanTheAllmighty** [comment]
@coolreader18 can you grab the `latest.log` for the instance in ATLauncher and provide that. Should be in the logs folder if you click Open Folder on the instance

**Comment by RyanTheAllmighty** [comment]
Both those logs in that gist looks to be from PolyMC @coolreader18

**Comment by coolreader18** [comment]
No, that's definitely from ATLauncher. It's not latest.log, since I opened the game again after opening that world, but it's `logs/2022-06-09-1.log.gz`

**Comment by coolreader18** [comment]
oh wait wtf

**Comment by coolreader18** [comment]
the same log is in both

**Comment by coolreader18** [comment]
Nevermind that's not the case I have no idea what's happened but I've fixed the gist.

**Comment by RyanTheAllmighty** [comment]
Okay so having looked at both logs side by side, they both load and launch exactly the same. The only difference being that PolyMC loads with Java 18 and ATLauncher loads with Java 17.

If you're 100% sure you've unchecked the `Use Java Provided By Minecraft` setting for the instance and saved and pointed it to your Java 18 install, then only next step I can think of is running `ls -al` and `sha1sum *` in both the ATLauncher and PolyMC `mods` folders for each instance and can see if there's something off about any of the mods file permissions, sizes or hashes. Since it's the same pack and version, they should be identical, but this is the only real next thing I can think to check
