### ISSUE TITLE
Skin and Head in launcher Refuse to Update

### ISSUE THREAD

**Issue by Obscure2020** [ATLauncher/ATLauncher#598]
**Describe the bug**
I recently changed my skin on [Minecraft.net](https://minecraft.net). It used to be this:
![image](https://user-images.githubusercontent.com/69320464/172900744-5b6b9f3b-aad2-412e-9e5c-ae4a618453ae.png)
However, it is now this:
![image](https://user-images.githubusercontent.com/69320464/172900820-0e90439c-886b-41b1-866e-2ce3f7a5c851.png)
For some reason, ATLauncher refuses to update my skin as shown in the Accounts menu and in the drop-down list at the bottom of the program:
![image](https://user-images.githubusercontent.com/69320464/172900990-912d85ec-92d4-40de-b4b5-0741ab25acda.png)![image](https://user-images.githubusercontent.com/69320464/172901015-228f69cb-7a32-4d48-bf2b-5e274bb05df9.png)
I've tried right-clicking and hitting `Reload Skin`, I've tried using the `Skin Updater` in the Tools menu... nothing's worked.

**To Reproduce**
1. Observe your skin and head as shown in the launcher.
2. Upload a new skin to [Minecraft.net](https://minecraft.net).
3. Close and reopen ATLauncher. Open the **Accounts** tab, and select your account in the center menu. Observe no change.
4. Right-click your skin and select `Reload Skin`. Observe no change.
5. Open the **Tools** tab, and launch the `Skin Updater`. Observe a popup that says "Successfully updated skins."
6. Go back to the **Accounts** tab. Observe no change.
7. Right-click your skin and select `Reload Skin` one more time for good measure. Observe no change.

**Expected behavior**
ATLauncher should optimally re-check and download new skins for all accounts on startup. In addition, the `Reload Skin` option and the `Skin Updater` should actually do something.

**System information**
- Windows 10
- Java 17

**Comment by RyanTheAllmighty** [comment]
How long did you wait? Skins are cached for some time from memory

**Comment by RyanTheAllmighty** [comment]
I just updated my skin and it instantly updated in the launcher, so I'm not sure what your particular issue is.

Can you go into debug mode (https://atlauncher.com/help/debug-mode) and then update the skin for your account and then share the logs. If you don't want to make the log public, please feel free to dm it to me on Discord (Discord ID is on https://atlauncher.com/humans.txt)

**Comment by Obscure2020** [comment]
Would you like me to use OBS to screen-record what's happening?
Because this seems like exceedingly non-standard behavior.

**Comment by RyanTheAllmighty** [comment]
No. If you say it's happening I believe you. But not being able to replicate an issue makes it pretty hard to try and fix.

Either way I'll take a look and see why it might be happening. Can try removing your account and adding it again which will likely force it to update for sure

**Comment by Obscure2020** [comment]
I'm gonna bet there's some issue involved with downloading new skin data and *not* relying on anything cached.

I just tried deleting my account from ATLauncher and then logging back in. It still pulled up my old skin.

I then tried deleting my account, closing ATLauncher, reopening ATLauncher, closing it again for good measure, and reopening it *again.* Then I logged back in, and... somehow, it STILL pulled up my old skin.

![image](https://user-images.githubusercontent.com/69320464/173126550-b293db94-1b36-4940-9260-b874f8d84ab7.png)

**Comment by Obscure2020** [comment]
OH! Wait! I just tried `Reload Skin` again, after doing the whole process I just described above. And *now*, it finally downloaded my new skin.
![image](https://user-images.githubusercontent.com/69320464/173126764-6e153b18-5ef8-43fa-ab0a-f1d5f3b71521.png)
So it seems `Reload Skin` *can* work, but only after some combination of deleting your account and closing/reopening ATLauncher.

**Comment by RyanTheAllmighty** [comment]
Yes it's a simple skin renderer, I have no interest in making it fully compatable with all skin features. Unfortunately since this isn't something I could replicate, it's not something that can be fixed so I'll close this issue.
