### ISSUE TITLE
Failing to launch an empty forge pack

### ISSUE THREAD

**Issue by armuell** [ATLauncher/ATLauncher#600]
**Describe the bug**
pack fails to launch

**To Reproduce**

1. Launch a "vanilla" pack for 1.18.2 with forge installed

**Expected behavior**
the pack to launch

**Logs**
https://paste.atlauncher.com/view/0412f836-c780-4460-8dc2-3222b5244d36

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- Win10
- Java 17

**Additional context**

**Comment by armuell** [comment]
restarting the launcher fixed the issue, can be closed

**Comment by RyanTheAllmighty** [comment]
Please use discord for any future support.
