### ISSUE TITLE
Search & Sort Box on Edit Mods Page

### ISSUE THREAD

**Issue by ardissaps** [ATLauncher/ATLauncher#630]
![image](https://user-images.githubusercontent.com/82106625/177894923-1380b473-0f3f-4795-8b23-b369808820b9.png)
The sorting can be based on last install time and name. 
Thank you, no need to hurry!

**Comment by RyanTheAllmighty** [comment]
Duplicate of #556 which is for an overhaul of that entire section. Best to post in there

**Comment by ardissaps** [comment]
> Duplicate of #556 which is for an overhaul of that entire section. Best to post in there

Sorry! I tried to search but can't find that post, maybe because it is morning and I drink not enough coffee! :D
