### ISSUE TITLE
Stuck on "Checking For Updates" when trying to update mods sometimes

### ISSUE THREAD

**Issue by Nelly1234567** [ATLauncher/ATLauncher#633]
When trying to update my mods via ATLauncher's "Check For Update" option under "Edit Mods", it will start scanning just fine but once it does find a mod that can be updated it sometimes causes the "Checking For Updates" box to glitch out not allowing you to interact with any boxes below it that do pop up with an update for a mod.

I have recorded a video demonstrating the issue from a fresh start up of AT Launcher. Restarting the application doesn't always fix the issue as well.
 
 https://youtu.be/8mEHsPipNiI

**Comment by RyanTheAllmighty** [comment]
Duplicate it #608
