### ISSUE TITLE
Configure preferred modhosting site

### ISSUE THREAD

**Issue by supersaiyansubtlety** [ATLauncher/ATLauncher#636]
**Is your feature request related to a problem? Please describe.**
I sometimes forget to select modrinth when I search for and add mods. 
There's no at-a-glance way to see what site a mod was installed from.
There's no way to switch all mods possible to one mod hosting site.

**Describe the solution you'd like**
1) Configure preferred mod hosting site
2) Default the add mods search interface to that site
3) Show an indicator in mod lists when a mod is installed from a non-preferred site, but *could be* installed from the preferred site
4) Provide a way to switch all possible mods (or all selected possible mods) to the preferred site.

**Describe alternatives you've considered**
Currently I just right click and select "Reinstall from modrinth" if I'm unsure if a mods is installed from curseforge or not.

**Additional context**
N/A

**Comment by RyanTheAllmighty** [comment]
There is already a setting to set the default mod platform. #556 would cover your other points as that section will be completely rewritten
