### ISSUE TITLE
**USRDIR**/temp folder being created as read only - cannot remove temp/native files

### ISSUE THREAD

**Issue by kylerhenry** [ATLauncher/ATLauncher#639]
**Describe the bug**
Upon trying to join a server the launcher will occasionally crash with "Error trying to delete the directory \*\*USERDIR\*\*/temp/natives-####" 

**To Reproduce**

1. Launch mc instance
2. Attempt to join multiplayer instance
3. Wait for connection to be established - crash occurs _after_ establishing connection.
4. Client will then be unresponsive
5. Close game, error will be in log.

Note that this is not always the case. Sometimes this issue just doesn't show up, and others it happens several times in a row.

**Expected behavior**
No crash, able to join server. Expected launcher to be able to delete the files inside of the temp folder.

**Logs**
```
20:56:18.518 [ATL-Logging-Thread] ERROR - Error trying to delete the directory **USERSDIR**\temp\natives-965ba33f401145509ba9f9682b3ded31

20:56:18.519 [ATL-Logging-Thread] ERROR - java.nio.file.AccessDeniedException: **USERSDIR**\temp\natives-965ba33f401145509ba9f9682b3ded31\SAPIWrapper_x64.dll

20:56:18.520 [ATL-Logging-Thread] ERROR - 	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)

20:56:18.521 [ATL-Logging-Thread] ERROR - 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)

20:56:18.522 [ATL-Logging-Thread] ERROR - 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)

20:56:18.522 [ATL-Logging-Thread] ERROR - 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)

20:56:18.522 [ATL-Logging-Thread] ERROR - 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)

20:56:18.522 [ATL-Logging-Thread] ERROR - 	at java.base/java.nio.file.Files.delete(Unknown Source)

20:56:18.522 [ATL-Logging-Thread] ERROR - 	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:30)

20:56:18.522 [ATL-Logging-Thread] ERROR - 	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:27)

20:56:18.526 [ATL-Logging-Thread] ERROR - 	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)

20:56:18.526 [ATL-Logging-Thread] ERROR - 	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)

20:56:18.526 [ATL-Logging-Thread] ERROR - 	at com.atlauncher.utils.FileUtils.deleteDirectory(FileUtils.java:91)

20:56:18.527 [ATL-Logging-Thread] ERROR - 	at com.atlauncher.data.Instance.lambda$launch$19(Instance.java:1142)

20:56:18.528 [ATL-Logging-Thread] ERROR - 	at java.base/java.lang.Thread.run(Unknown Source)

20:56:18.529 [ATL-Logging-Thread] ERROR - java.nio.file.AccessDeniedException: **USERSDIR**\temp\natives-965ba33f401145509ba9f9682b3ded31\SAPIWrapper_x64.dll
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.base/java.nio.file.Files.delete(Unknown Source)
	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:30)
	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:27)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at com.atlauncher.utils.FileUtils.deleteDirectory(FileUtils.java:91)
	at com.atlauncher.data.Instance.lambda$launch$19(Instance.java:1142)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**System information (please complete the following information, or remove if not applicable):**

- OS: Windows 10
- Java Version: Java 17 (MC version 1.18.2)

**Additional context**
AT Launcher creates the `temp` folder as readonly
![image](https://user-images.githubusercontent.com/48518018/180861246-e2217ea1-7a25-4dd8-9e39-aef95e7dd139.png)
Setting the folder as R/W from the command line is the only way I have found to fix it. Permissions on the folder are set to full access for all users and system, but this is not enough.

**Comment by RyanTheAllmighty** [comment]
Note that the crash is not related to not being able to delete the natives directory. The natives folder is deleted after the instance process ends. Windows shows every folder for every application as being read only for me, so seems to be the standard for Windows.

Failing to delete that directory isn't an issue and shouldn't really show in the logs as it doesn't affect anything, I'll hide it from the logs to prevent people from thinking it's actually an error when it's not
