### ISSUE TITLE
cannot be opened because developer cannot be verified

### ISSUE THREAD

**Issue by bevv10** [ATLauncher/ATLauncher#644]
<!--

developer cannot be verified macos

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS MACOS Monterey 12.4
- Java Version: [e.g. Java 8, Amazon Coretto 8]

**Additional context**
may be something stupid on my end but lmk

**Comment by RyanTheAllmighty** [comment]
Duplicate of #501
