### ISSUE TITLE
launcher not seeing new downloads

### ISSUE THREAD

**Issue by bevv10** [ATLauncher/ATLauncher#645]
**Describe the bug**
I download the requested mods but it is not seeing them in the downloads folder. I also allowed access to all folders

In order to continue downloading this modpack, you must manually download the following mods. Simply click the Open button to open them in your browser, or alternatively you can copy the url to your clipboard to open in another browser. 
**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): [e.g. Windows 10, OSX Big Sur, Arch Linux] Macos
- Java Version: 8

**Additional context**

**Comment by RyanTheAllmighty** [comment]
Yup part of issues with OSX security which duplicates #502 You need to use the Jar version of the launcher to get around the issue or download directly into the launchers own download folder (which may also not work)

**Comment by SevenChords** [comment]
> Yup part of issues with OSX security which duplicates #502 You need to use the Jar version of the launcher to get around the issue or download directly into the launchers own download folder (which may also not work)

the jar version of the launcher no longer works as a workaround for the issues, the jar version cannot move files from the users download folder, even after the jar itself and the java executable have been given full disk access.
