### ISSUE TITLE
add auto update mods

### ISSUE THREAD

**Issue by CyberFIowey** [ATLauncher/ATLauncher#648]
so that you don't have to manually select the version to click update mods and he did everything himself and then he can give out a list of mods that he updated from which version to which, and add the ability to both turn this function on and off

**Comment by RyanTheAllmighty** [comment]
We won't add in auto updating mods. It's bad for so many reasons and would very likely break packs and increase support if that were the case.

**Comment by CyberFIowey** [comment]
again, I'm talking about a function that can be turned on or off, just select the version higher in the list all the time and click add, it's a very long time if you have a build of 200+ mods

**Comment by CyberFIowey** [comment]
or tell me where you can update all the mods so if it's not a secret?

**Comment by CyberFIowey** [comment]
😢  :sadpepe:

**Comment by CyberFIowey** [comment]
:pepehands:
