### ISSUE TITLE
UI Improvement Brainstorm

### ISSUE THREAD

**Issue by LuciusofLegend** [ATLauncher/ATLauncher#653]
In my experience, ATLauncher has more unique features and useful tools than any other custom Minecraft launcher I've seen :clap:.  However, I feel the one thing it's truly lacking is a nice user interface.

The purpose of this issue is not to demand immediate changes, instead, it's to get some priorities about how we could tackle this problem when we're ready.

If you have any ideas on how the UI could be improved *in the long run*, please be clear and succinct about sharing them.  Thank you.

**Comment by RyanTheAllmighty** [comment]
Be aware that #556 exists to track improvements to the mod browsing/installing/management side of things, so where possible, keep those in that issue.

But I welcome any thoughts you or anyone else has
