### ISSUE TITLE
Failed to set the Dock icon when using jar version of launcher

### ISSUE THREAD

**Issue by whitebear60** [ATLauncher/ATLauncher#655]
**Describe the bug**
The launcher fails to set its icon into the dock and displays standard Java icon instead
Also the app name is simply "java", and not ATLauncher

**To Reproduce**

1. Start the launcher
2. Lock at the Dock

**Expected behavior**
The icon should be ATLauncher's, but it is standard Java one

**Logs**
[See log file, the launcher throws an exception regarding this at the top](https://paste.atlauncher.com/view/32f6b41e-3353-41ad-96bb-758f386a7a1c)

**Screenshots**
jar version:
<img width="155" alt="image" src="https://user-images.githubusercontent.com/42472132/196614115-a16b93e0-a804-4cc1-bd1a-732a9393d137.png">
*.app version (still throws the same exception at the start though)
<img width="148" alt="image" src="https://user-images.githubusercontent.com/42472132/196614982-455f3ad2-3403-4c7e-8a48-8266f5b92297.png">

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): macOS Monterey 12.5.1
- CPU: Intel
- Java Version: Java 17
- ATLauncher 3.4.20.2

**Comment by RyanTheAllmighty** [comment]
Yup Java 9 removed this internal api used for setting the icon, so will need a workaround I imagine

**Comment by whitebear60** [comment]
Probably look around for how Mojang implemented this into Minecraft, as this issue was there too and was fixed only in recent versions of Minecraft...
