### ISSUE TITLE
An option to change default instances location

### ISSUE THREAD

**Issue by 1280px** [ATLauncher/ATLauncher#657]
**Is your feature request related to a problem? Please describe.**
Use different path for all Minecraft instances rather than default one

**Describe the solution you'd like**
An option to change default instances location (maybe add an option to change the indivial instances location as well, #654

**Describe alternatives you've considered**
-

**Additional context**
![изображение](https://user-images.githubusercontent.com/71165491/197686861-286825c8-00b8-4092-8521-7d8c3e21e4de.png)

**Comment by RyanTheAllmighty** [comment]
Duplicate of #654

**Comment by 1280px** [comment]
> Duplicate of #654

Not really, as #654 is only about changing an instance's location, and I suggest an option to change the DEFAULT location for ALL instances (speaking roughly, the place where the .minecraft folder will be stored)

**Comment by RyanTheAllmighty** [comment]
That issue will cover both scenarios

**Comment by Smealm** [comment]
still waiting for this to be added

**Comment by RyanTheAllmighty** [comment]
Yes #654 is the issue it will be done in
