### ISSUE TITLE
Modrinth mods under mod browser does not select primary download by default when multiple are provided

### ISSUE THREAD

**Issue by KJP12** [ATLauncher/ATLauncher#661]
**Describe the bug**
When downloading mods from the built in browser, some mods with multiple downloads for sources and javadocs don't use the primary jar by default.

**To Reproduce**

1. On an instance in the instances tab...
2. Click on `Add mods`
3. Scroll down to or search for `Sodium Extra` (live example, other mods may work here).
4. Click add & note that no file is selected by default
   - If the bug doesn't show, try selecting `mc1.19.2-0.4.11`, named `Sodium Extra 0.4.11 for Minecraft 1.19.2`

**Expected behavior**
For the primary file to be selected if applicable. *There is on the page, see: <https://modrinth.com/mod/sodium-extra/version/mc1.19.2-0.4.11>*

**Logs**
Logs aren't applicable here.

<details><summary><b>Screenshots</b></summary>

In launcher:
![image](https://user-images.githubusercontent.com/8528256/200409669-ff951e14-6a66-4b4c-96b3-17b071af134b.png)

On Modrinth:
![image](https://user-images.githubusercontent.com/8528256/200409701-f0f77c35-1914-4ae1-b46b-66cd31340669.png)

</details>

**System information (please complete the following information, or remove if not applicable):**
*Not really applicable but providing anyways*
- OS (including distro/version): Arch Linux + KDE Plasma.
- Java Version: Graal 22.2.0 + Java 17.0.4

**Additional context**
 - ATLauncher Version: 3.4.20.4

**Comment by RyanTheAllmighty** [comment]
Makes sense to auto select the primary file (assuming there is always 1 primary)
