### ISSUE TITLE
Collapsing instances freezes for a bit when not logged into a Microsoft account

### ISSUE THREAD

**Issue by epic0421** [ATLauncher/ATLauncher#665]
**Describe the bug**
I cannot vouch for what happens with Mojang accounts but can say my experience using a Microsoft account.

First thing I noticed is that with no account logged in, all the instances are uncollapsed when normally, the launcher remembers the collapsed state when relaunching the launcher. 

 The first instance collapses fine but any other actions (collapsing or uncollapsing) freezes the launcher each time.

**To Reproduce**

Log out of any accounts that are currently logged in and make sure there are multiple instances in the launcher. Then try to collapse multiple instances and the launcher freezes each time.

**Expected behavior**
I expect the same behavior that is normally present when logged into an account.

**Logs**
https://paste.atlauncher.com/view/5f5f7db7-fd01-4080-9eea-69834157f621

**Comment by RyanTheAllmighty** [comment]
Collapse state is stored per account, so while it won't remember it if you have no accounts, it shouldn't be ok laggy I'd say
