### ISSUE TITLE
No default app

### ISSUE THREAD

**Issue by JustFoxx** [ATLauncher/ATLauncher#667]
I have problem with atlauncher not openning default apps on linux when clicking open link on atlauncher it doesnt open the default browser,
If i click anything that is link releated on atlauncher it wont work. I have installed web browser, i used official RPM package to install app.
Debug logs: https://canary.discord.com/channels/117047818136322057/1038898525569822740/1038898786518441984

**Comment by RyanTheAllmighty** [comment]
Please provide more information, especially about your OS, OS version, Java type, Java version, desktop environment and version, window manager and version.

You also mention that it doesn't open the default browser, does that mean it opens a browser, just not your default?
