### ISSUE TITLE
Allow imports of pre-existing servers

### ISSUE THREAD

**Issue by JJeeff248** [ATLauncher/ATLauncher#678]
**Description of problem**
I started using ATLauncher today and like the simplicity of importing instances. I then tried to do the same thing with some servers I run and found no import option. I spent 2ish hours trying to get them imported manually which eventually worked but it could be made easier.

**The solution I'd like**
An added option to import pre-existing servers into the launcher. An implementation as seen when importing instances would be perfect.

**Alternatives I've considered**
Manually importing using a file explorer - It took a while to work out.

**Comment by RyanTheAllmighty** [comment]
Going to roll this into #421
