### ISSUE TITLE
A version of Geckolib for the wrong modloader is selected to be installed by default

### ISSUE THREAD

**Issue by SuperStormer** [ATLauncher/ATLauncher#683]
**Describe the bug**
The Quilt version of Geckolib is selected by default when you try to add it to an instance from the "Add Mods" menu, even though the instance is a **Forge** instance.

**To Reproduce**

1. Create a new Vanilla Pack on 1.18.2 Forge 40.1.86
2. Go to the "Instances" tab and click on "Add Mods" for the newly created instance.
3. Search for "Geckolib" and click "Add".
4. Observe that the version of geckolib selected by default is a quilt version (`geckolib-quilt-1.18-3.0.44.jar`).

**Expected behavior**

The Forge version of geckolib (`geckolib-forge-1.18-3.0.56.jar`)  should be selected by default when you try to install it.

**Logs**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/41648788/208044251-71a111c7-e183-426c-a5c3-f3698e6628d1.png)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Windows 10

**Additional context**
n/a

**Comment by RyanTheAllmighty** [comment]
Yup this was fixed with commit a80294a7b6c0dd44763ce56b80b9234bac84496f just awaiting next release
