### ISSUE TITLE
[Bug] ATLauncher Flatpak crashing on startup when specifically when run as a non steam game on Steam Deck

### ISSUE THREAD

**Issue by WMan22** [ATLauncher/ATLauncher#685]
**Describe the bug**
When attempting to launch ATLauncher's Flatpak through Steam on Steam Deck. It works just fine when launched standalone, however.

**To Reproduce**
1. Add game as non steam game
2. Launch, only to see it crash before you can even see the mod loader interface
3. Launch again independently of steam to see that this is a problem specific to this context

**Expected behavior**
Running through Steam so I have access to Steam Input and thus my Steam Deck controls.

**Logs**
I would love to give you logs but the [Instructions I found on this website](https://docs.mjrlegends.com/General%20Minecraft/crash-log/) point to logs for specific instances to troubleshoot specific mod packs, when I can't even get into the launcher itself unless I launch it independently of steam where it will work just fine. I checked the logs folder anyway under /home/deck/.var/app/com.atlauncher.ATLauncher/data/logs and nothing was in that folder.

**Screenshots**
Kinda hard to screenshot a crash.

**System information (please complete the following information, or remove if not applicable):**
- Hardware: Steam Deck 512GB
- OS: SteamOS 3.4
- Java Version: The one that comes with Flatpak version 3.4.22.1

**Additional context**
In Steam Deck's game mode, it will result in infinite loading, on desktop mode it will simply not start. It will launch perfectly fine when not run through steam.

After running into this issue, I attempted to add /home/deck/.local/share/Steam and /home/deck/.steam/Steam to flatseal's directory permission manager for ATLauncher and this did not fix it, still had the same issues.

**Comment by Doomsdayrs** [comment]
> My apologies, I don't mean to trouble you further, but could you please post the solution in this github issue? The discord link you posted is giving me a [weird error](https://i.imgur.com/1jPypmQ.png) and it'd be especially helpful for future people looking for a solution but are at their 100 channel cap.
> 
> You don't need to write up a whole tutorial, just copy and paste the contents of that discord post here, please.

I'm the developer who handles flatpak, can we move to the flatpak repo and continue the issue there, as I am also trying to figure this out

**Comment by WMan22** [comment]
So doing [this](https://github.com/flathub/com.atlauncher.ATLauncher/issues/48#issuecomment-1364578659) got it fixed, thanks for the help Doomsdayrs. I'm documenting the fix here for future google people who are looking for the solution to this problem instead of just going "nvm fixed it ;)"
