### ISSUE TITLE
Custom modpack platform plugin support for ATLauncher

### ISSUE THREAD

**Issue by Lauriichan** [ATLauncher/ATLauncher#692]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A feature that would be great for the ATLauncher would be the possibility to write plugins to add support for new modpack platforms.
For example if someone would like to host a modpack on their own website or something they could add support for that using a plugin and then people would only need to install that plugin.

I got this idea when I revisited my own modpack launcher however it is very basic and limited therefore I thought it would be great if AT could provide such an API.

**Describe alternatives you've considered**
If adding support for plugins is too much then maybe some kind of support for custom websites with a defined description file that has to be accessible per http/https something like that would also do the job I think.

**Additional context**
After looking at the current code my guess is that the alternative would be the easiest to add compared to my original solution.
It would also be fine if this would be too big of a request to be implemented and I just thought it might be a great thing to have even if not many people might use this kind of feature.

**Comment by RyanTheAllmighty** [comment]
There's no plan to add plugin support, for such a niche thing, it's not something I see ever happening. If it is, it's more likely to just be trimmed down into a simple http request for #475 which is to conver updating custom packs
