### ISSUE TITLE
Add support for adding Fabric Loader to Minecraft versions 1.3-1.13.2 with the Legacy Fabric Maven

### ISSUE THREAD

**Issue by YakisikliBaran** [ATLauncher/ATLauncher#698]
**Is your feature request related to a problem? Please describe.**
I want to play Minecraft with Fabric mods on ATLauncher for 1.8.9.

**Describe the solution you'd like**
Allowing to create an Instance with the Fabric Loader for 1.8.9 with the Legacy Fabric Maven.

**Describe alternatives you've considered**
There is an MultiMC pack for the versions they support by the Legacy Fabric team that has the Fabric Loader but with the maven set to the Legacy Fabric one.

**Additional context**
I know that there is #529 but instead of custom jars or jsons, allowing Fabric to be added on Minecraft versions 1.3-1.13.2 with the Legacy Fabric Maven would probably work.
The Legacy Fabric Maven is available from https://repo.legacyfabric.net/

**Comment by RyanTheAllmighty** [comment]
Looks like they have a meta server at https://meta.legacyfabric.net/ so can follow the same pattern as current Fabric assuming it installs the same way.

I assume this is not endorsed by the Fabric team and is essentially a fork, so I'll likely just add another loader option for "Legacy Fabric" to separate it since it is 2 separate projects by 2 separate teams I'm guessing

**Comment by YakisikliBaran** [comment]
> Looks like they have a meta server at https://meta.legacyfabric.net/ so can follow the same pattern as current Fabric assuming it installs the same way.
> 
> I assume this is not endorsed by the Fabric team and is essentially a fork, so I'll likely just add another loader option for "Legacy Fabric" to separate it since it is 2 separate projects by 2 separate teams I'm guessing

Yes its a fork

**Comment by RyanTheAllmighty** [comment]
Yeah, so I'll take a look at adding it as another loader type, hopefully it should be fairly straight forward like how Quilt was

**Comment by YakisikliBaran** [comment]
> Yeah, so I'll take a look at adding it as another loader type, hopefully it should be fairly straight forward like how Quilt was

Also it would be nice if the launcher reminded the user to see if the mod installed works correctly according to the mod list in the Legacy Fabric website

**Comment by YakisikliBaran** [comment]
> Does Legacy Fabric use a mod similar to QSL or Fabric API? Or is that just built in do you know?
Yes it does it uses the Legacy Fabric API.
Its available from:
https://beta.curseforge.com/minecraft/mc-mods/legacy-fabric-api/files/4126229
https://github.com/Legacy-Fabric/fabric/releases

**Comment by RyanTheAllmighty** [comment]
Ah perfect.

Strange they don't have it listed in Modrinth. Oh well it'll do, thanks for that. Should be all the info I need :)

**Comment by YakisikliBaran** [comment]
> Ah perfect.
> 
> Strange they don't have it listed in Modrinth. Oh well it'll do, thanks for that. Should be all the info I need :)

They have it,i forget to add it to the list.
Sorry about that :c
**https://modrinth.com/mod/legacy-fabric-api**

**Comment by RyanTheAllmighty** [comment]
Odd, I did look for it on Modrinth, but nothing came up. Oh well, thanks again

**Comment by RyanTheAllmighty** [comment]
Alright so that was fairly simple. Both client and server generation working. Will package up and release over the next couple days.

**Comment by YakisikliBaran** [comment]
Thanks for this quick addition, now i can use ATLauncher as my only Minecraft Launcher :)
