### ISSUE TITLE
"No versions found for this mod" when installing a Resource Pack from Modrinth

### ISSUE THREAD

**Issue by Obscure2020** [ATLauncher/ATLauncher#700]
**Describe the bug**
If you have your settings set to `Show mods for all Minecraft versions`, then installing Resource Packs from Modrinth works fine. However, If you are instead using `Show mods for the current major Minecraft version (eg: 1.16.x)` or `Only show mods for the current Minecraft version`, you will get this popup:

![image](https://user-images.githubusercontent.com/69320464/211160691-441eefb1-f172-4843-a10a-662a3e88e2af.png)

**To Reproduce**
1. Have a 1.19.3 Fabric instance.
1. Change settings to `Show mods for all Minecraft versions`.
1. Attempt to install the latest version of VanillaXBR, which is a Resource Pack on Modrinth. This process should complete without error.
1. Use the `Edit Mods` menu to remove VanilaXBR.
2. Change settings to `Show mods for the current major Minecraft version (eg: 1.16.x)`.
3. Attempt to install VanillaXBR again. You should be greeted by the popup.
4. Change settings to `Only show mods for the current Minecraft version`.
5. Attempt to install VanillaXBR again. You should be greeted by the popup.

**Expected behavior**
Installing VanillaXBR should always work regardless of this setting.\
When the setting is set to `Show mods for the current major Minecraft version (eg: 1.16.x)`, I would expect that the list should still come up, and the list should include the versions for `1.19 (Release)`, `1.19.2 (Release)`, and `1.19.3 (Beta)`.\
When the setting is set to `Only show mods for the current Minecraft version`, I would expect that the list should still come up, and the list should include solely the version for `1.19.3 (Beta)`.

**System information:**
- OS: Windows 11 Home 22H2
- Java Version: Java 19 (19.0.1)

**Additional context**
- ATLauncher Version: 3.4.23.0 [bb8bd6d1adefa5517d7ff893ae13818452e6899b]

**Comment by RyanTheAllmighty** [comment]
Yeah looks like it's filtering out everything since resource packs don't have loaders assigned, thanks for the report
