### ISSUE TITLE
Modlist breaks (kinda) when adding the same mod multiple times

### ISSUE THREAD

**Issue by whitebear60** [ATLauncher/ATLauncher#702]
**Describe the bug**
When trying to add the same mod twice (for example, from jar file), the modlist shows it as many times as you added it, despite in the fs it doesn't create copies, leading to "ghost" entries in the modlist

**To Reproduce**

1. Go to Edit Mods menu for any instance
2. Click on Add Mod
4. Add any mod to the instance
5. Add the same mod to the instance again
6. The mod should appear twice in the modlist
7. Open the mods folder
8. There should be one file with the mod you added twice (or there will be two files of different versions of the mod, if you added two different versions)

**Expected behavior**
Refusing to add new file if the mod already exists in the instance / removing the old version if adding the new version of the mod that exists in instance

**Logs**
[If applicable, add logs to help explain your problem.](https://paste.atlauncher.com/view/5cdad96a-7698-4232-85cd-5c3d889bf254)

**Screenshots**
![mod-duplicate](https://user-images.githubusercontent.com/42472132/211203014-ba995bd1-6fa0-4c2b-aa49-bee0bc0e28c1.jpg)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): macOS Ventura 13.0.1
- Java Version: Microsoft OpenJDK 17.0.5

**Comment by RyanTheAllmighty** [comment]
Yikes, yeah shouldn't do that

**Comment by whitebear60** [comment]
Also sometimes it copies a 0kb file when adding the mod to the instance, but, for now, I haven't managed to investigate, exactly under what circumstances that happens... Anyways, this probably will go to another issue, if I will manage to understand, when that happen...
