### ISSUE TITLE
Checksum mismatch when trying to install via flatpak

### ISSUE THREAD

**Issue by winkelnp** [ATLauncher/ATLauncher#706]
I'm on Fedora 37 with GNOME 43.2 and flatpak version 1.14.1.

I tried installing the ATLauncher via flatpak and it gave me this response:
```
Error: While pulling app/com.atlauncher.ATLauncher/x86_64/stable from remote flathub: Checksum mismatch in static delta part; expected=7a55673892ac8b3f354c433affaa6ff957753ee9459e36e650faf9d10de3a71a actual=c22738448ba839fbca6452cbe758d93a5c1c2631701c4c558eda5f48702cc4c7
error: Failed to install com.atlauncher.ATLauncher: While pulling app/com.atlauncher.ATLauncher/x86_64/stable from remote flathub: Checksum mismatch in static delta part; expected=7a55673892ac8b3f354c433affaa6ff957753ee9459e36e650faf9d10d
```

Please do let me know if this is a user error and something I would need to fix myself

**Comment by RyanTheAllmighty** [comment]
We don't have control over flathub systems, you'd need to report this to them. Likely this is a download issue on your end though. I'd suggest reaching out to flatpak/flathub support

**Comment by Doomsdayrs** [comment]
I'll investigation

**Comment by RyanTheAllmighty** [comment]
Yeah looks like an issue on flathub's side https://status.flathub.org/issues/2023-01-14-deltas/
