### ISSUE TITLE
Exporting to MultiMC produce broken profiles

### ISSUE THREAD

**Issue by KJP12** [ATLauncher/ATLauncher#710]
**Describe the bug**
When exporting any profile for MultiMC, the profile isn't importable into Prism Launcher.

**To Reproduce**

1. Create any profile. Quilt Loader was included as part of the test.
2. Export the profile as is.
3. Import the export into Prism or any other MultiMC derivative.
4. Try either launching the new instance or look at the version page to see missing data.

**Expected behavior**
Minecraft and Intermediary to be correctly defined.

**Logs**
No logs applicable, but here's the exports' `mmc-pack.json` from both ATLauncher and Prism Launcher.

<details><summary>ATLauncher's <code>mmc-pack.json</code>. Known faulted.</summary>

```json
{
  "components": [
    {
      "cachedName": "LWJGL 3",
      "cachedVersion": "3.2.2",
      "cachedVolatile": true,
      "dependencyOnly": true,
      "uid": "org.lwjgl3",
      "version": "3.2.2"
    },
    {
      "cachedName": "Minecraft",
      "cachedRequires": [
        {
          "equals": "3.2.2",
          "suggests": "3.2.2",
          "uid": "org.lwjgl3"
        }
      ],
      "cachedVersion": "1.19.3",
      "cachedVolatile": true,
      "dependencyOnly": true,
      "uid": "org.lwjgl3",
      "version": "3.2.2"
    },
    {
      "cachedName": "Hashed Mappings",
      "cachedRequires": [
        {
          "equals": "1.19.3",
          "uid": "net.minecraft"
        }
      ],
      "cachedVersion": "1.19.3",
      "cachedVolatile": true,
      "dependencyOnly": true,
      "uid": "org.quiltmc.hashed",
      "version": "1.19.3"
    },
    {
      "cachedName": "Fabric Loader",
      "cachedRequires": [
        {
          "uid": "org.quiltmc.hashed"
        }
      ],
      "cachedVersion": "0.18.1-beta.46",
      "cachedVolatile": false,
      "dependencyOnly": false,
      "uid": "org.quiltmc.quilt-loader",
      "version": "0.18.1-beta.46"
    }
  ],
  "formatVersion": 1
}
```

</details>

<details><summary>Prism Launcher's <code>mmc-pack.json</code>. Known working.</summary>

```json
{
    "components": [
        {
            "cachedName": "LWJGL 3",
            "cachedVersion": "3.3.1",
            "cachedVolatile": true,
            "dependencyOnly": true,
            "uid": "org.lwjgl3",
            "version": "3.3.1"
        },
        {
            "cachedName": "Minecraft",
            "cachedRequires": [
                {
                    "suggests": "3.3.1",
                    "uid": "org.lwjgl3"
                }
            ],
            "cachedVersion": "1.19.3",
            "important": true,
            "uid": "net.minecraft",
            "version": "1.19.3"
        },
        {
            "cachedName": "Intermediary Mappings",
            "cachedRequires": [
                {
                    "equals": "1.19.3",
                    "uid": "net.minecraft"
                }
            ],
            "cachedVersion": "1.19.3",
            "cachedVolatile": true,
            "dependencyOnly": true,
            "uid": "net.fabricmc.intermediary",
            "version": "1.19.3"
        },
        {
            "cachedName": "Quilt Loader",
            "cachedRequires": [
                {
                    "uid": "net.fabricmc.intermediary"
                }
            ],
            "cachedVersion": "0.17.8",
            "uid": "org.quiltmc.quilt-loader",
            "version": "0.17.8"
        }
    ],
    "formatVersion": 1
}
```

</details>

It is notable that ATLauncher exports with Hashed as the intermediary in the case of Quilt Loader, and defines LWJGL twice, once with the correct metadata, and again with Minecraft's metadata.
It also fails to mark what is supposed to be Minecraft's entry as important.

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux with Linux 6.1.1-arch1-1
- Java Version: GraalVM CE 22.2.0 Java 17

**Comment by RyanTheAllmighty** [comment]
Yeah looking at it the lwjgl component is hardcoded to always be 3.2.2, should probably be taken from the actual version used by Minecraft I imagine. Also the use of hashed is from some old change where Quilt tells us to use hashed in their json files, but we have to manually switch it from what they tell us to intermediary.

They should be easy enough to fix up.
