### ISSUE TITLE
Switch to page 0 after changing mod search query

### ISSUE THREAD

**Issue by CodeF53** [ATLauncher/ATLauncher#714]
**Describe the bug**
The currently selected page doesn't get reset after changing your search. 

**To Reproduce**
1. Go to instances
2. Click add mods
3. Click next page 10 times
4. Search 'zoom' and press enter
5. See error

**Expected behavior**
After changing the search query, it should go back to page zero like every search thing on earth.

**Screenshots**

https://user-images.githubusercontent.com/37855219/213896695-f0377387-efb4-4b5c-be79-c8ffd6113b2e.mp4

**Comment by RyanTheAllmighty** [comment]
lol, that's stupid behaviour. Will fix up
