### ISSUE TITLE
ATLauncher fails to respond when adding mods.

### ISSUE THREAD

**Issue by Muhammed-Al-Abdul-Gader** [ATLauncher/ATLauncher#730]
**Describe the bug**

ATLauncher "Adding Mods For Minecraft X.x.x with X" fails to respond when adding mods. Meaning when a mod is being installed, it randomly stops responding to mouse inputs. No response or highlight to any buttons of the window. Only mouse input  visible is the scrolling of the bar.

**To Reproduce**

1. Go to Instances
2. Click on Add Mods
3. Start adding / installing mods, it may take some time or no time for the bug to take.

**Expected behavior**

Add a mod, install it. Keep adding mods, or close the window.

**Logs**

I do not know if the problem is shown in the log, but here it is:

[atlauncher.log](https://github.com/ATLauncher/ATLauncher/files/10878133/atlauncher.log)

**Screenshots**

https://user-images.githubusercontent.com/72892223/222633478-17ab82f4-f2fc-4532-92ec-a601007843a9.mp4

**System information

- OS:  Windows 11
- Java Version:  Java 19.0.2

**Additional context**

It only occured once. A CMD window opened and instantly closed. It was impossible to read its contents. Also, in the recording provided. My mouse briefly disappeared and returned.

**Comment by RyanTheAllmighty** [comment]
Are you adding mods to the instance? The screen recording doesn't show it properly. Are you able to screen record a region of your screen instead of the application maybe to show those windows.

It could be related to https://github.com/ATLauncher/ATLauncher/issues/715 but the video isn't completely clear on what's going on

**Comment by Muhammed-Al-Abdul-Gader** [comment]
> Are you adding mods to the instance? The screen recording doesn't show it properly. Are you able to screen record a region of your screen instead of the application maybe to show those windows.
> 
> It could be related to #715 but the video isn't completely clear on what's going on

It could be, but here is another video to make sure.

https://user-images.githubusercontent.com/72892223/222639354-b5bd38e9-2d11-400e-be7f-3b12be359215.mp4

**Comment by RyanTheAllmighty** [comment]
Try one thing, when it happens again, can you try going to the ATLauncher icon in the taskbar, bottom right by your clock, right clicking it and going `Kill Open Dialogs` and see if that makes the UI interactive and working again?

**Comment by Muhammed-Al-Abdul-Gader** [comment]
I had the icon disabled initially. Thankfully the issue has been resolved, but unfortunately the mods window is killed too, meaning I lose track of any page I was in. Is it possible to retain the mod window / page? Anyhow, the general issue has been resolved. Thank you.

**Comment by RyanTheAllmighty** [comment]
Yeah I'm going to say this is definitely part of #715 which is an annoying ongoing issue at the moment.
