### ISSUE TITLE
Open website and open folder buttons not working on Arch Linux

### ISSUE THREAD

**Issue by kyngs** [ATLauncher/ATLauncher#736]
**Describe the bug**
When I try to press the open folder button, nothing happens. Looking at the terminal output, I can spot this error:
/usr/bin/dolphin: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
When I press the open website button, nothing happens. Also, nothing appears in the logs.
btw, I do not have apparmor installed

**To Reproduce**
Press the open folder or open website button on some instance in the launcher.

**Expected behavior**
Dolphin/Firefox opens.

**Logs**
Logs from terminal:  https://pastebin.com/2KYZHWKA
ATLauncher logs: https://paste.atlauncher.com/view/3bf494e0-7ac9-480e-8c51-b76125857d58

**Screenshots**
Not applicable.

**System information (please complete the following information, or remove if not applicable):**

- OS: Arch Linux x86_64 6.2.7-zen1-1-zen
- DE: KDE Plasma 5.27.3
- Java Version: openjdk 17.0.6 2023-01-17 (using java 8 does not help)
- Drivers: Nvidia Proprietary (525.89.02)
- File Manager: Dolphin
- Web Browser: Firefox

**Additional context**
This may be my system setup issue, tell me what other system info you need.

**Comment by RyanTheAllmighty** [comment]
Closing as didn't realise there is already an open issue for this, #713
