### ISSUE TITLE
Can‘t open Main Window on latest source code

### ISSUE THREAD

**Issue by zeng-github01** [ATLauncher/ATLauncher#741]
**Describe the bug**

Build and run the latest source code, it will stuck on loading. 

**To Reproduce**

1. Git clone the source code and open idea.
2. Add configuration: build and run it.
3. Run ATLauncher-3.4.28.0.exe in dist.
4. See error.

**Expected behavior**

Open The Main Window/Form

**Logs**
If applicable, add logs to help explain your problem.

https://paste.atlauncher.com/view/ac1a88eb-467d-4867-ba19-280b30d6ece3

**Screenshots**

![image](https://user-images.githubusercontent.com/95841646/228268545-e4b3f62a-8398-4c8d-b295-6e8a47926204.png)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version):Windows 11 22H2
- Java Version: Java 8_361 [jre]
- Idea JDK Version: jbr-17

**Additional context**

**Comment by Doomsdayrs** [comment]
Try #733 ?

**Comment by zeng-github01** [comment]
> 尝试 #733 ？

Thanks, I'll try it out

**Comment by zeng-github01** [comment]
> Try #733 ?

Thanks, I'll try it out

**Comment by RyanTheAllmighty** [comment]
Yeah I imagine it's something in the current masters minimise rules. #733 will likely fix it, but not sure if that'll go in yet, still need to look at it and decide.

**Comment by zeng-github01** [comment]
> Try #733 ?

This PR fixes the issue.
