### ISSUE TITLE
Add a button to open the folder to Minecraft.jar

### ISSUE THREAD

**Issue by 00001H** [ATLauncher/ATLauncher#762]
### The Problem

I sometimes can't find the downloaded minecraft.jar.

### The Solution

A button is added to open the path to the version folders containing minecraft client jars for the installed versions.

### Additional Information

Currently found under INSTALL_DIR\libraries\net\minecraft\client\VERSION

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
For what purpose?

**Comment by 00001H** [comment]
@RyanTheAllmighty Not to modify, but to extract the resources, as I need the textures to render the mod model correctly in Blockbench. I will not include it in the final release(as the mod can just access it), of course.

While adding this feature, a reminder to not distribute the resources could also be added.
