### ISSUE TITLE
Blank ATLauncher window(s) on Linux (DWM)

### ISSUE THREAD

**Issue by RedLeader167** [ATLauncher/ATLauncher#774]
### What happened?

When opening ATLauncher on Linux Mint with DWM, there is nothing present both in launcher and console windows. However, it works fine on XFCE - the problem appears only on DWM.

### Operating System

Linux

### Relevant log output

```shell
(no logs)
```

### Additional Information

![Screenshot](https://github.com/ATLauncher/ATLauncher/assets/59973962/77b3a70e-bd7d-480b-b468-dc44504b8c06)

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Very likely a duplicate of https://github.com/ATLauncher/ATLauncher/issues/373 can you check the solutions in there, mainly the `_JAVA_AWT_WM_NONREPARENTING=1` env variable, but think there's other solutions in there

**Comment by RedLeader167** [comment]
Yep, it helped, thanks! AFAIK this is a Java issue, so I think it is okay to close this as solved :)

**Comment by Doomsdayrs** [comment]
Speaking of, how did you install ATLauncher?

**Comment by RedLeader167** [comment]
With a .deb package (deb -i <pkg>) from official website.

**Comment by Doomsdayrs** [comment]
> With a .deb package (deb -i ) from official website.

Can you try the version that is in the software store?

**Comment by ThePython10110** [comment]
Still happening with me (Linux Mint 21.3, DWM 6.4, ATLauncher installed via .deb from website), and `_JAVA_AWT_WM_NONREPARENTING=1` doesn't seem to help.

**Comment by Doomsdayrs** [comment]
> Still happening with me (Linux Mint 21.3, DWM 6.4, ATLauncher installed via .deb from website), and `_JAVA_AWT_WM_NONREPARENTING=1` doesn't seem to help.

May you try the flatpak version?

**Comment by geckwwo** [comment]
> Still happening with me (Linux Mint 21.3, DWM 6.4, ATLauncher installed via .deb from website), and `_JAVA_AWT_WM_NONREPARENTING=1` doesn't seem to help.

You need to either run
> _JAVA_AWT_WM_NONREPARENTING=1 atlauncher
or
> export _JAVA_AWT_WM_NONREPARENTING=1
> atlauncher
or just make sure that variable is in the environment (e.g. same shell session)

**Comment by ThePython10110** [comment]
I know; that's what I meant. The Flatpak version works though.
