### ISSUE TITLE
ATLauncher closes itself when Minecraft launches, even when the "Keep launcher open" option is toggled.

### ISSUE THREAD

**Issue by MCAlexisYT** [ATLauncher/ATLauncher#786]
### What happened?

1. Open ATLauncher
2. Tick the checkbox named "Keep launcher opened" if it isn't already
3. Launch Minecraft
4. Launcher disappears, and then reappears when Minecraft is exited.
5. Expected behavior: The launcher window is still open when Minecraft is launched.

### Operating System

Windows

### Relevant log output

```shell
I don't have any ¯\_(●_●)_/¯
```

### Additional Information

https://github.com/ATLauncher/ATLauncher/assets/78766083/c35f62fa-70b8-4496-b8fa-81fe18a906d3

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
This is not a bug, this is how the launcher works, #551 will fix that
