### ISSUE TITLE
Suggestion: add minecraft bedrock support.

### ISSUE THREAD

**Issue by kingmaj0r** [ATLauncher/ATLauncher#799]
### The Problem

theres no probelm.

### The Solution

theres no solution

### Additional Information

Hello,

I would like to propose the inclusion of Minecraft Bedrock/Minecraft for Windows 10 support for Linux on ATLauncher. Given the advantages of Minecraft Bedrock and its compatibility, this addition could greatly enhance user experience. Your consideration of this suggestion is greatly appreciated.

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Doomsdayrs** [comment]
Out of scope for a Java modpack Launcher. 

I suggest the following instead: https://flathub.org/apps/io.mrarm.mcpelauncher

**Comment by RyanTheAllmighty** [comment]
Correct, we're only concerned with Java Edition.
