### ISSUE TITLE
ui.BasicLauncherUiTest fails on update from aur

### ISSUE THREAD

**Issue by JacobFrodermann** [ATLauncher/ATLauncher#802]
### What happened?

1. I updated my system using yay -Syu
2. atlauncher-git compiled succefully
3. the tests run
4. the Launcher windows opens
5. It crashes on clicking the Ok button on the msg that an instance was created and can be found in the instances Tab

### Operating System

Windows

### Relevant log output

```shell
https://pastebin.com/Hmf42t73
```

### Additional Information

Arch
Wayland (hyprland) 
java -version
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (build 25.382-b05, mixed mode)

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Red-S2** [comment]
this has been happening for quite some time and in the testing of my pr yesterday the UI of the current source worked, maybe skip the test for the AUR?
