### ISSUE TITLE
Edit Mods Tab Difficult to Read - Add Icons + Colour Coding

### ISSUE THREAD

**Issue by J05HY06** [ATLauncher/ATLauncher#808]
### The Problem

Browsing the current mods in a pack is confusing when all mods are just lines of monotone text

### The Solution

adding icons would make it much easier to see what mods are installed and presenting the titles in colours can show more information at a glance e.g green text = Modrinth or grey = Curseforge etc

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Duplicate of #556
