### ISSUE TITLE
Ely.by skins support

### ISSUE THREAD

**Issue by deargosep** [ATLauncher/ATLauncher#813]
### The Problem

Is it possible to add ely.by skins support? Like in "Legacy Launcher"

### The Solution

Add ely.by authorization

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
No we will not implement any type of alternative authentication or skin services
