### ISSUE TITLE
Automatic Snapshot updating.

### ISSUE THREAD

**Issue by some-du6e** [ATLauncher/ATLauncher#831]
### The Problem

Its annoying updating a "experimental" pack (example: Auto crafter testing)

### The Solution

A option somewhere in the "Create Pack" section.

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
There's no plans to do any sort of auto updating of instances between Minecraft versions or modpack versions. Updates will always be a manual process sorry.
