### ISSUE TITLE
i cant add mods in 1.20.2 

### ISSUE THREAD

**Issue by AlirezaParsi** [ATLauncher/ATLauncher#833]
### What happened?

![image](https://github.com/ATLauncher/ATLauncher/assets/29276037/b76094a3-75be-467d-83c0-99913415667e)
there is no option to add mods 

ATLauncher Version: 3.4.34.2 [47a8b83ebee65f53f68f63ccc309bb2ebbc845e9]

 Java Version: Java 17 (17.0.3)
 Java Path: C:\Program Files\Java\jre-1.8
 64 Bit Java: true

### Operating System

Windows

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
If there's no option to add mods it's because you don't have a mod loader installed. If that's not the case, please see the above to visit our Discord to get support

**Comment by AlirezaParsi** [comment]
i added mod loader and its fixed 
thanks.
