### ISSUE TITLE
Sorting options for "Edit mods" list

### ISSUE THREAD

**Issue by Jawzper** [ATLauncher/ATLauncher#844]
### The Problem

Currently the "Edit mods" list for instances shows an alphabetized list of enabled and disabled mods. 

Once you have many mods installed (and/or disabled), it can start getting difficult to find and roll back recent changes to your mod list. Building a mod pack, I've been frequently finding it necessary to open the instance's folder in your file manager to sort by date modified and then move files around manually.

### The Solution

Add list sorting options for the instance "Edit mods" lists, in particular to allow for sorting by last modified date. Maybe other sorting options would be useful too?

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
This is planned to be implemented in #556

**Comment by Jawzper** [comment]
Oh, excellent. Thanks for letting me know, is there any timeline on when this feature will be added?

**Comment by RyanTheAllmighty** [comment]
There is not

**Comment by Jawzper** [comment]
Fair enough. I'll be looking forward to the day then :)
