### ISSUE TITLE
Keep launcher open while Minecraft is running

### ISSUE THREAD

**Issue by gustav-langer** [ATLauncher/ATLauncher#847]
### The Problem

Whenever you start an instance, the launcher closes. This is really annoying because I often want to look at the installed mods or launch another instance and I have to start a new launcher process for that.

### The Solution

Add an option to keep the launcher open. Right now there is just an option to reopen it after Minecraft has exited.

### Have you checked this issue doesn't already exist?

- [x] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
This will be done as part of #551
