### ISSUE TITLE
Horrible lag on MacOS 14.1.1

### ISSUE THREAD

**Issue by some-du6e** [ATLauncher/ATLauncher#848]
### What happened?

1. Open atl
2. Profit

Instances take a lot of time to load and it uses ALOT of ram (see images).

i dont know if its relevant but im running on opencore patcher.

### Operating System

macOS

### Additional Information

![empty instances](https://github.com/ATLauncher/ATLauncher/assets/103129948/31f5b665-2302-4687-9d06-3b974fc60166)

![Screenshot 2023-11-13 at 3 45 02 PM](https://github.com/ATLauncher/ATLauncher/assets/103129948/8521abbe-5bc3-46db-ad8c-681120342148)

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Doomsdayrs** [comment]
How many instances do you have?

**Comment by some-du6e** [comment]
65~

**Comment by Doomsdayrs** [comment]
I believe I have a few solutions.

I'll be working on it and a release should be possible in a few hours.

**Comment by some-du6e** [comment]
#849 fixed my issue.
I hope it gets merged.
