### ISSUE TITLE
Launching server does not work through the launcher but it works by using the launch scripts

### ISSUE THREAD

**Issue by Edvaize** [ATLauncher/ATLauncher#873]
### What happened?

To preface this, I make a lot of servers on a lot of different versions so I have installed multiple different java versions and made my own envirnmental variables for them for easy access. So the first thing I do is usually to change "java" to my variable for the java that I need. Also I created my files system when I was younger so I didn't think about spaces in folder names but this isn't a problem if you use more quotation marks.
1. Open ATLauncher
2. Install a server of any kind
3. Go to servers and to the server of choice
4. Open server folder
5. Open up the launch scripts and change java path to the needed java path
6. Click any of the launch options and see that the server doesn't launch because it's trying to use a different path than the one you set java to
![image](https://github.com/ATLauncher/ATLauncher/assets/102916578/20ebc5b1-9f60-408c-b95d-03259eb1f248)

7. Open server folder
8. Launch server using the launch scripts directly and then the server launches fine

In other words, for some reason there is a difference between using the launch buttons in the launcher compared to just launching the scripts. I can still launch the server of course but I have to open the folder and use a script which is no issue but it seems a little weird and oviously I should be able to use the buttons in the launcher. There must be something else that those buttons use to run the server which seem to not have enough quotation marks for the computer to be able to use spaces in the path according to the image

### Operating System

Windows

### Additional Information

![image](https://github.com/ATLauncher/ATLauncher/assets/102916578/4c3e4611-6c92-4aba-9e89-3c41b36237f5)

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Yeah because where you've installed the launcher (`D:\Games and Launchers`) has a space in it, that is causing issues. I thought this was fixed previously, but looks like it's come back

**Comment by Edvaize** [comment]
> Yeah because where you've installed the launcher (`D:\Games and Launchers`) has a space in it, that is causing issues. I thought this was fixed previously, but looks like it's come back

Ah, yes that would seem to make sense. It is a common occurence that issues come of that, it makes me wish i was a bit smarter a few years ago when I created my file system and now it is a bit too much of a hassle to change. Hope you are able to fix it

**Comment by RyanTheAllmighty** [comment]
@Edvaize this should be fixed now. In order to get the fixed scripts, you'll need to install the server again
