### ISSUE TITLE
server installer does not make launch script executable 

### ISSUE THREAD

**Issue by StanberyTrask** [ATLauncher/ATLauncher#876]
### What happened?

1. install https://www.curseforge.com/minecraft/modpacks/mc-chocolate-edition server through atlauncher
2. try to run server through server tab
3. terminal pops up with child error window that says "failed to execute child"

### Operating System

Linux

### Additional Information

went into the server files to manually run the start script for the server and found it was not set as executable, running ``chmod +x`` fixed the issue and let me run the server. looks like this could just be an oversight in the server installer

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Yup this was an oversight when I implemented CurseForge servers. Will fix it up this weekend
