### ISSUE TITLE
Support for "duplicated" instances

### ISSUE THREAD

**Issue by seriousfreezing** [ATLauncher/ATLauncher#879]
### The Problem

Well, I'm a modpack creator and I use ATlauncher to make the modpacks, so every time I make a version I have to make it for 3 different versions, but how can I work efficiently when all the versions have the same name?

ATlauncher doesn't allow me to import the version I want to work on with name "A" from 1.19.2 and another with name "A" also from 1.20.1.

For me to be able to do what I want, I have to delete the instance I'm working on to go to the other instance.

### The Solution

You could have a system that allows you to have several instances but already adds a variation to the instance name, for example:
- Version
- Or with a term called copy

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
When you import an instance you can choose what name to import it as. Does this not work for you?

**Comment by seriousfreezing** [comment]
This only appears if the instance doesn't already exist. If the instance you're going to import has the same name, it just tells you that you already have that instance, even if it's from another version

**Comment by RyanTheAllmighty** [comment]
It doesn't work like that for me.

If I import the instance it creates fine, if I then import it again, or even a different zip/mrpack file with the same name, I'm still prompted to give it a name. Yes the default is what is defined in the export, but it can be changed.

Not seeing what the issue is here sorry

**Comment by seriousfreezing** [comment]
Hm, I tested what you said and it really works.
I thought that part of the name was something about exporting or something, even though it didn't make sense.

But I think it should at least have something automatic so you don't have to think about the instance.
