### ISSUE TITLE
The jar without excluding some dependencies in shadowJar is a little bit less

### ISSUE THREAD

**Issue by ellet0** [ATLauncher/ATLauncher#897]
### What happened?

1. Go to `build.gradle` in the shadowJar block
2. Run `./gradlew shadowJar` and rename the output jar to anything different so it won't replaced with the new one
3. Replace `minimize` block that has `exlcude` (inside it) with only `minimize()`
4. Run `./gradlew shadowJar` once again

You will notice the old jar size is (26.2 MB) while the new one is (21 MB)

and it is supposed to be the exact opposite, excluding some dependencies should save some space, not making the jar file size a little bit bigger, I might be wrong (I'm not sure if this issue from my side) or it might be a bug in the shadow jar or it could be that excluding some dependencies manually would disable the `minimize()` process provided by shadow jar and will only exclude what you want to exclude

```grovy

minimize {
        exclude(dependency('org.apache.logging.log4j:.*:.*'))
        exclude(dependency('com.formdev:.*:.*'))
        exclude(dependency('com.github.jnr:.*:.*'))
        exclude(dependency('com.github.hypfvieh:.*:.*'))
        exclude(dependency('org.apache.commons:commons-compress:.*'))
    }

```

What the [docs](https://imperceptiblethoughts.com/shadow/configuration/minimizing/) say:

![image](https://github.com/ATLauncher/ATLauncher/assets/73608287/52a8b98e-f3d6-47a6-a8ae-851d9d71d6ed)

In either case, it is worth the try, usually the jar file size should be as less as possible

### Operating System

macOS

### Relevant log output

```shell
This is not a bug
```

### Additional Information

![image](https://github.com/ATLauncher/ATLauncher/assets/73608287/020be8c9-c188-405d-a6f9-dea3b63dd1af)

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellet0** [comment]
Since this is not really a bug and we have more important things in the project, closing this issue, I will try to focus on more important things next time.

Thank you for your understanding.

**Comment by Doomsdayrs** [comment]
I am a bit confused, why close this?

**Comment by ellet0** [comment]
> I am a bit confused, why close this?

It might be misleading because `exclude` in the `minimize` might exclude things from being minimized, because of a reflection for example, and not exclude extra things from the jar, I tested both versions of the jars, and both work without any errors like `ClassNotFoundException` etc...
