### ISSUE TITLE
Remove Mojang account support

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#906]
Now that Mojang accounts are no more, and MIcrosoft are the only working accounts, we should remove support for it.

Currently the accounts system uses an abstract account which is of either MojangAccount or MicrosoftAccount class, so that adds in some complexity.

Accounts screen should just have one button to login to microsoft, no more username/password fields.

**Comment by Doomsdayrs** [comment]
FINALLY I CAN DO IT

**Comment by RyanTheAllmighty** [comment]
I think we just need to nuke Mojang accounts at all. When we load in accounts on boot, I think we just throw out any Mojang accounts.

This will definitely cause an issue for some people who didn't migrate, but I'd rather be completely removed of all Mojang account code and logic than still try and support accounts that we know don't work anymore and cannot authenticate anymore, so are technically invalid accounts

**Comment by RyanTheAllmighty** [comment]
It seems people still manage to add Mojang accounts through the launcher somehow, but the numbers are tiny:

![image](https://github.com/ATLauncher/ATLauncher/assets/1723537/0cc03341-4039-4d4a-8a4a-59f9c2b4dc2d)

Digging deeper, it's only 4 users who actually did this, and they never came back to use the launcher afterwards, so happy to just delete it.

**Comment by Doomsdayrs** [comment]
Currently gutting the code base.

This will require UI logic rework as well, handling it rn.

**Comment by RyanTheAllmighty** [comment]
Feel free to do #755 if you want at the same time, since it's switching away from oauth callbacks to a local server to using device flow. I have a branch with it done, was waiting to remove mojang accounts before pushing it out.

But if not, happy to follow up after you've done this, I'll leave it up to you what you want to do
