### ISSUE TITLE
When I remove Forge from a modpack to change it into Neoforge it deletes random mods

### ISSUE THREAD

**Issue by LittKingLoser** [ATLauncher/ATLauncher#913]
### What happened?

Remove forge from a modpack that uses forge and change it into neoforge, and there will be missing mods without warning and it doesn't tell you what's gone

### Operating System

Windows

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Forge mods are not compatible with NeoForge. What is likely is you're just not seeing the mods that are not compatible anymore. The launcher wont remove or touch your mods when changing loader.

If this is not the case, please do the following:

- Install Forge instance with your mods
- Launch the instance and confirm mods are fine
- Remove Forge and install NeoForge
- Launch the instance and confirm the mods are fine (or not)
- Upload logs using the launchers console, without clearing it between any of the steps above

If that is provided and confirmed this is still an issue, I'll reopen, but for now going to close.
