### ISSUE TITLE
unresponsizeness

### ISSUE THREAD

**Issue by JasimAlrawie** [ATLauncher/ATLauncher#920]
### What happened?

i open at launcher
i installed a mod
mod installtion complete
then it freeze cant click anything and i should force close it with task manager 
its happen some times\

heres a video

https://github.com/ATLauncher/ATLauncher/assets/40839702/42d98248-b759-42cb-a211-aaddf3b34404

### Operating System

Windows

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Duplicate of #715
