### ISSUE TITLE
My CPU runs at 80-84 degrees while downloading any modpack.

### ISSUE THREAD

**Issue by RippAlex** [ATLauncher/ATLauncher#926]
### What happened?

1. I opened ATLauncher 2. I click to download any modpack 3. When it starts downloading it instantly spikes to 84 degrees celcius from around 47-55 (idle). My CPU never runs that hot on anything.

### Operating System

Windows

### Additional Information

My CPU is the Ryzen 7 7800X3D and my cooler is the Thermalright Phantom Spirit 120

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RippAlex** [comment]
Also I tried Prism Launcher for the first time and my CPU stays pretty much the exact same temp as when it's idle so it's definitely the launcher's fault.

**Comment by RyanTheAllmighty** [comment]
This is pretty normal behaviour. Installing modpacks is heavily CPU intensive, especially due to the hashing process for revers mod lookup. Going to close this as again it's pretty normal behaviour when there is a large CPU usage and there's nothing we'd really do to fix this sorry

**Comment by RippAlex** [comment]
alright but unfortunately I'm going to have to use Prism Launcher going forward
