### ISSUE TITLE
Create Pack text boxes don't wrap & drop inputs on Windows, buggy "Select All" behavior in text inputs

### ISSUE THREAD

**Issue by kam106** [ATLauncher/ATLauncher#931]
### What happened?

Excuse the formatting, this is my first time submitting a Github issue.

There are several things to note about the text fields on the Create Pack tab, but there's two main issues with the text fields I want to bring up first.

1. Inputs appear to be dropped/buggy on Windows.

I don't remember when I started experiencing this, but it was recently. I type fast (i'd say ~80 WPM) and I have noticed that some key inputs are being "dropped". I've shown this in the video, sometimes a character will not register at all.
I have replicated this on Windows 10 and a Windows 11 machine. The windows 10 machine is on the latest feature update, 22H2, and I have also replicated this on an initial release Windows 10 virtual machine, so I don't think the version of the OS is what matters.

There is no helpful console input where this happens. This was likely caused by a Launcher Update, as I did not have this issue before. I'm unsure when this started happening, I can confirm it to be a few month old issue, I will likely try to track down the original date of the issue later for better reference.

I have been able to trigger this consistently on three Windows versions. Linux is untested. I can confirm somebody else has this issue too, however I'm unsure how many experience this, it doesn't seem to be many.

2. CTRL + A is buggy and inconsistent

I believe this also happens in some other text fields (specifically Edit Description), but this is better shown in the text fields in Create Pack. Trying to select all with CTRL + A and trying to backspace sometimes leads to the text being unselected, or only Backspace registering, making only one character delete. I'm unsure why this happens.

3. Instance Description box doesn't wrap text

Additionally, it seems that the text box for the Instance description in Create Pack also wraps text incorrectly, it scrolls the box vertically instead of wrapping the text around the space provided by the box. Most of these issues do not occur in other text fields with the exception of buggy CTRL + A behavior, which happens in other text fields, but at a smaller rate.

This was originally brought to attention from a Discord thread, so here's a small blurb from that:
"I am having an issue where pressing keys on input fields too fast causes some characters to not enter. It seems to also cause a side issue where sometimes, ctrl + a then trying to backspace characters does not work. I can live without these inputs, but as I use them a lot, I would prefer to not have this issue.

I have been able to replicate this issue on both a Windows 11 and a Windows 10 machine. I have not had this issue before.

Some extra details that may be of note:
I have only been experiencing this issue recently, this used to not be an issue. I don't remember exactly if this happened following an update or a system change, just that this behavior is now replicated.

java -version reports back with Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing) on my main Windows 11 machine. I'm using a JDK 17 build, and have a few portable Java builds on the side for other Minecraft versions (specifically Java 8 and Java 21). JDK 17.0.8 is installed with the installer, not a portable build. I obtained JDK 17 from oracle.com. The Windows 10 machine uses 17.0.9."

### Operating System

Windows

### Additional Information

I have submitted a video of this issue to YouTube that demonstrates this issue, with StreamKB showing my keyboard inputs. I was originally going to show images, but a video is likely better.
Here's that video: https://www.youtube.com/watch?v=uyAgp1mPyLQ

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Doomsdayrs** [comment]
Knew this would come eventually, Time to do performance tweaking.

**Comment by kam106** [comment]
Accidently closed issue.

**Comment by Doomsdayrs** [comment]
Awaiting release

**Comment by kam106** [comment]
Good to know. Thank you.
