### ISSUE TITLE
Duplicate mods in CurseForge expprt

### ISSUE THREAD

**Issue by Killer-xz** [ATLauncher/ATLauncher#932]
### What happened?

Manifest:

{"author":"","files":[{"fileID":4405665,"projectID":575248,"required":true},{"fileID":4121643,"projectID":257814,"required":true},{"fileID":5327503,"projectID":954140,"required":true},{"fileID":5143086,"projectID":882911,"required":true},{"fileID":4081312,"projectID":551453,"required":true},{"fileID":4572858,"projectID":852533,"required":true},{"fileID":4363719,"projectID":690161,"required":true},{"fileID":4592588,"projectID":484967,"required":true},{"fileID":4665253,"projectID":852987,"required":true},{"fileID":5195554,"projectID":984689,"required":true},{"fileID":4037228,"projectID":291874,"required":true},{"fileID":5341287,"projectID":1013669,"required":true},{"fileID":4362206,"projectID":667520,"required":true},{"fileID":5433901,"projectID":1027025,"required":true},{"fileID":5260829,"projectID":1002985,"required":true},{"fileID":5154424,"projectID":244830,"required":true},{"fileID":5137942,"projectID":419699,"required":true},{"fileID":4534619,"projectID":639842,"required":true},{"fileID":4749000,"projectID":382216,"required":true},{"fileID":4556697,"projectID":228525,"required":true},{"fileID":4057605,"projectID":443034,"required":true},{"fileID":4388535,"projectID":597562,"required":true},{"fileID":4973444,"projectID":348521,"required":true},{"fileID":5157030,"projectID":316582,"required":true},{"fileID":4451885,"projectID":840788,"required":true},{"fileID":4143529,"projectID":337243,"required":true},{"fileID":4813397,"projectID":695021,"required":true},{"fileID":4404949,"projectID":448233,"required":true},{"fileID":4418462,"projectID":579545,"required":true},{"fileID":5051241,"projectID":398521,"required":true},{"fileID":4117906,"projectID":429235,"required":true},{"fileID":5143989,"projectID":333287,"required":true},{"fileID":5154414,"projectID":244844,"required":true},{"fileID":4407241,"projectID":388172,"required":true},{"fileID":5116175,"projectID":360203,"required":true},{"fileID":4426743,"projectID":377572,"required":true},{"fileID":4478201,"projectID":592449,"required":true},{"fileID":4009744,"projectID":510974,"required":true},{"fileID":4712866,"projectID":238222,"required":true},{"fileID":5149215,"projectID":916334,"required":true},{"fileID":4983974,"projectID":499980,"required":true},{"fileID":4847008,"projectID":627986,"required":true},{"fileID":4418149,"projectID":658587,"required":true},{"fileID":4287899,"projectID":433068,"required":true},{"fileID":4101942,"projectID":235729,"required":true},{"fileID":4802808,"projectID":917700,"required":true},{"fileID":5029331,"projectID":959784,"required":true},{"fileID":5429194,"projectID":521480,"required":true},{"fileID":5209370,"projectID":886997,"required":true},{"fileID":3836016,"projectID":526854,"required":true},{"fileID":5529111,"projectID":1028108,"required":true},{"fileID":5489516,"projectID":1001299,"required":true},{"fileID":5536675,"projectID":923133,"required":true},{"fileID":5125389,"projectID":416089,"required":true},{"fileID":4876062,"projectID":421850,"required":true},{"fileID":4876097,"projectID":389665,"required":true},{"fileID":4572859,"projectID":852533,"required":true},{"fileID":5542851,"projectID":964969,"required":true}],"manifestType":"minecraftModpack","manifestVersion":1,"minecraft":{"modLoaders":[{"id":"forge-43.4.2","primary":true}],"version":"1.19.2"},"name":"1.19.2","overrides":"overrides","version":"1.0.0"}

### Operating System

Windows

### Relevant log output

```shell
The status of the file Nightmare revenge 1.0.0 (Nightmare revenge) has been changed to Rejected

Invalid file reference in manifest: File ID 4572859 (From-The-Fog-1.19-v1.9.1-Data-Resource-Pack.zip) references project ID 852533 (), which appears more than once.
You can read more about this at https://support.curseforge.com/en/support/solutions/articles/9000197279-moderation-policies.

If you have any questions please contact our support team https://support.curseforge.com.
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
> {"fileID":4572859,"projectID":852533,"required":true},
> {"fileID":4572858,"projectID":852533,"required":true},

You have the same mod in your pack twice, but with different versions. You need to remove one. This is not a launcher issue.
