### ISSUE TITLE
Search feature for editing mods

### ISSUE THREAD

**Issue by Yabitom** [ATLauncher/ATLauncher#944]
### The Problem

I regularly check whether mods are up to date and the select all feature helps a lot. But since majority of the mods I use are either beta or alpha releases, I find myself spending too much time scrolling through the list. It being in alphabetical order helps but sometimes it just isn't enough.

### The Solution

There should be a search feature when editing mods to quickly find enabled and disabled mods

### Additional Information

![javaw_Wx3nkadSGt](https://github.com/user-attachments/assets/20cab06a-3789-4cf7-8a41-7c5454f1344e)

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
#556
