### ISSUE TITLE
Connected Instances

### ISSUE THREAD

**Issue by NiktoBerg** [ATLauncher/ATLauncher#965]
### The Problem

**every Instances** have its own resource pack , mod , screenshot , ... folder and there isn't an way to have it connected to the .minecraft folders

### The Solution

but if there was an option in the Instances settings that you can make the Instances folder connected to the .minecraft folders it will be awesome :D

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
The instance folder is the .minecraft folder. We do not use the .minecraft folder in any way and don't have any plans to change that
