### ISSUE TITLE
ATLauncher home directory

### ISSUE THREAD

**Issue by NP-Hardass** [ATLauncher/ATLauncher#97]
I would recommend that ATLauncher preferentially use a directory in $HOME, like $HOME/.atlauncher (generally), or %APPDATA%/atlauncher (Windows specifically).  This allows a system to keep the executable/jar in a more appropriate location of their choosing rather than its own directory.  For instance, on a Linux system, the binary/jar might be best placed in a directory that has no write permissions, but a normal user can still execute the binary/jar, or on a Windows system, the binary placed in the Program Files heirarchy, but has no write permissions to those folders (windows vista+)

**Comment by Baughn** [comment]
This problem is hitting me hard, right now. I'm trying to package ATLauncher for NixOS, although admittedly only for my own use--

The launcher script ends up looking like this:
```
  #!/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42/bin/bash
  source /nix/store/m991siyzqwk6vcv7mdp2qmm7vxbzs73m-mcenv-1/bin/mcenv
  /nix/store/v7vify4s5ib3kc1s14na1jsrdz63apd1-openjdk-8u76b00/bin/java -jar /nix/store/znyjlff16cl370srw7rzq56pq2b606nh-ATLauncher.jar "$@"
```

And, of course, /nix/store is not writable. I could really use the option of pointing it at somewhere in my homedir.

**Comment by dgelessus** [comment]
The launcher now has a `--working-dir` option, which you can use to tell it where to put its files.

**Comment by Baughn** [comment]
Aha.

Can we also have a `--help` option? :)
